// Decompiled functions in address range 0x00610000 - 0x0061FFFF
// Source: civ2.exe (Civilization II Multiplayer Gold Edition)
// Generated by Ghidra 12.0.3 headless decompiler

// ============================================================
// Function: FUN_0061a000 @ 0x0061A000
// Size: 326 bytes
// ============================================================

/* WARNING: Unable to track spacebase fully for stack */

void FUN_0061a000(void)

{
  uint *puVar1;
  undefined2 *puVar2;
  short *psVar3;
  undefined4 *puVar4;
  short *psVar5;
  short *psVar6;
  ushort *puVar7;
  ushort *puVar8;
  int *piVar9;
  char *pcVar10;
  undefined1 *puVar11;
  undefined2 *puVar12;
  char cVar13;
  short sVar14;
  short sVar15;
  uint uVar16;
  short sVar17;
  short sVar18;
  short sVar19;
  short sVar20;
  undefined2 unaff_SI;
  undefined2 unaff_DI;
  undefined2 in_SS;
  undefined2 in_DS;
  undefined2 uVar22;
  int unaff_FS_OFFSET;
  undefined1 auStack_2 [2];
  int iVar21;
  
  sVar20 = (short)auStack_2;
  sVar18 = (short)auStack_2;
  iVar21 = CONCAT22((short)((uint)auStack_2 >> 0x10),sVar20 + -0x16);
  *(undefined2 *)(iVar21 + -4) = in_DS;
  *(undefined2 *)(iVar21 + -6) = unaff_SI;
  *(undefined2 *)(iVar21 + -8) = unaff_DI;
  puVar1 = (uint *)segment(in_SS,sVar20 + 0x1a);
  uVar16 = *puVar1;
  puVar1 = (uint *)segment(in_SS,sVar20 + -8);
  *puVar1 = uVar16 & 0xffff;
  puVar2 = (undefined2 *)segment(in_SS,sVar20 + -2);
  *puVar2 = (short)(uVar16 >> 0x10);
  puVar1 = (uint *)segment(in_SS,sVar20 + 0x1e);
  uVar16 = *puVar1;
  puVar1 = (uint *)segment(in_SS,sVar20 + -0xc);
  *puVar1 = uVar16 & 0xffff;
  puVar2 = (undefined2 *)segment(in_SS,sVar20 + -4);
  *puVar2 = (short)(uVar16 >> 0x10);
  segment(in_SS,sVar20 + 10);
  segment(in_SS,sVar20 + 0xe);
  psVar3 = (short *)segment(in_SS,sVar20 + 0x28);
  sVar19 = *psVar3;
  do {
    psVar3 = (short *)segment(in_SS,sVar20 + -0x10);
    *psVar3 = sVar19;
    psVar3 = (short *)segment(in_SS,sVar20 + 0x24);
    sVar19 = *psVar3;
    do {
      puVar4 = (undefined4 *)segment(in_SS,sVar20 + 0x16);
      uVar22 = (undefined2)((uint)*puVar4 >> 0x10);
      sVar17 = (short)*puVar4;
      psVar3 = (short *)segment(in_SS,sVar20 + 0x28);
      psVar5 = (short *)segment(in_SS,sVar20 + -0x10);
      psVar6 = (short *)segment(in_SS,sVar20 + 0x22);
      puVar12 = (undefined2 *)segment(uVar22,((*psVar3 - *psVar5) + *psVar6) * 2 + sVar17);
      puVar2 = (undefined2 *)segment(in_SS,sVar20 + -0xe);
      *puVar2 = *puVar12;
      psVar3 = (short *)segment(in_SS,sVar20 + 0x26);
      sVar14 = *psVar3;
      psVar3 = (short *)segment(in_SS,sVar20 + 0x24);
      sVar15 = *psVar3;
      psVar3 = (short *)segment(in_SS,sVar20 + -0x14);
      *psVar3 = sVar15 - sVar19;
      psVar5 = (short *)segment(uVar22,(sVar15 - sVar19) * 2 + sVar17 + sVar14);
      psVar3 = (short *)segment(in_SS,sVar20 + -0xe);
      puVar7 = (ushort *)segment(in_SS,sVar20 + 0x26);
      puVar8 = (ushort *)segment(in_SS,sVar20 + -0x12);
      *puVar8 = (ushort)(*psVar3 + *psVar5) % *puVar7;
      psVar3 = (short *)segment(in_SS,sVar20 + -0x12);
      psVar5 = (short *)segment(in_SS,sVar20 + 0x2c);
      piVar9 = (int *)segment(in_SS,sVar20 + -8);
      segment(in_SS,sVar20 + -2);
      puVar7 = (ushort *)segment(in_SS,sVar20 + 0x2a);
      puVar8 = (ushort *)segment(in_SS,sVar20 + -0x14);
      cVar13 = *(char *)(*(int *)(unaff_FS_OFFSET +
                                 *piVar9 + (uint)(ushort)((*psVar3 + *psVar5) * 4)) + (uint)*puVar7
                        + (uint)*puVar8);
      psVar3 = (short *)segment(in_SS,sVar20 + 0x32);
      if ((*psVar3 < 0) || (cVar13 != (char)*psVar3)) {
        pcVar10 = (char *)segment(in_SS,sVar20 + -0x16);
        *pcVar10 = cVar13;
        psVar3 = (short *)segment(in_SS,sVar18 + -0x12);
        psVar5 = (short *)segment(in_SS,sVar18 + 0x30);
        piVar9 = (int *)segment(in_SS,sVar18 + -0xc);
        segment(in_SS,sVar18 + -4);
        puVar7 = (ushort *)segment(in_SS,sVar18 + 0x2e);
        puVar8 = (ushort *)segment(in_SS,sVar18 + -0x14);
        puVar11 = (undefined1 *)segment(in_SS,sVar18 + -0x16);
        *(undefined1 *)
         (*(int *)(unaff_FS_OFFSET + *piVar9 + (uint)(ushort)((*psVar3 + *psVar5) * 4)) +
          (uint)*puVar7 + (uint)*puVar8) = *puVar11;
      }
      sVar19 = sVar19 + -1;
    } while (0 < sVar19);
    psVar3 = (short *)segment(in_SS,sVar18 + -0x10);
    sVar19 = *psVar3 + -1;
  } while (0 < sVar19);
  return;
}



// ============================================================
// Function: FUN_0061a759 @ 0x0061A759
// Size: 423 bytes
// ============================================================

/* WARNING: Unable to track spacebase fully for stack */

void FUN_0061a759(void)

{
  uint *puVar1;
  undefined4 *puVar2;
  undefined2 *puVar3;
  short *psVar4;
  short *psVar5;
  ushort *puVar6;
  undefined2 *puVar7;
  short *psVar8;
  short *psVar9;
  int *piVar10;
  char *pcVar11;
  char cVar12;
  char cVar13;
  undefined2 uVar14;
  uint uVar15;
  undefined4 uVar16;
  short sVar17;
  short sVar18;
  ushort uVar19;
  int iVar20;
  undefined2 uVar21;
  int iVar22;
  short sVar23;
  undefined2 unaff_SI;
  short sVar25;
  undefined2 unaff_DI;
  char *pcVar26;
  undefined2 in_SS;
  undefined2 in_DS;
  undefined1 auStack_2 [2];
  int iVar24;
  
  sVar23 = (short)auStack_2;
  sVar17 = (short)auStack_2;
  iVar24 = CONCAT22((short)((uint)auStack_2 >> 0x10),sVar23 + -0x18);
  *(undefined2 *)(iVar24 + -4) = in_DS;
  *(undefined2 *)(iVar24 + -6) = unaff_SI;
  *(undefined2 *)(iVar24 + -8) = unaff_DI;
  puVar1 = (uint *)segment(in_SS,sVar23 + 10);
  uVar15 = *puVar1;
  puVar2 = (undefined4 *)segment(in_SS,sVar23 + 0x12);
  uVar16 = *puVar2;
  puVar3 = (undefined2 *)segment(in_SS,sVar23 + -6);
  *puVar3 = (short)((uint)uVar16 >> 0x10);
  puVar3 = (undefined2 *)segment(in_SS,sVar23 + -8);
  *puVar3 = (short)uVar16;
  puVar2 = (undefined4 *)segment(in_SS,sVar23 + 0x16);
  uVar16 = *puVar2;
  puVar3 = (undefined2 *)segment(in_SS,sVar23 + -10);
  *puVar3 = (short)((uint)uVar16 >> 0x10);
  puVar3 = (undefined2 *)segment(in_SS,sVar23 + -0xc);
  *puVar3 = (short)uVar16;
  puVar1 = (uint *)segment(in_SS,sVar23 + 0xe);
  psVar4 = (short *)segment(in_SS,sVar23 + 0x20);
  iVar22 = (int)*psVar4;
  if (iVar22 < 1) {
    iVar22 = -iVar22;
    psVar4 = (short *)segment(in_SS,sVar23 + 0x22);
    psVar5 = (short *)segment(in_SS,sVar23 + 0x1e);
    uVar19 = (*psVar4 + -1) - *psVar5;
  }
  else {
    puVar6 = (ushort *)segment(in_SS,sVar23 + 0x1e);
    uVar19 = *puVar6;
  }
  puVar6 = (ushort *)segment(in_SS,sVar23 + 0x1c);
  pcVar26 = (char *)((*puVar1 & 0xffff) + (uint)uVar19 * iVar22 + (uint)*puVar6);
  puVar3 = (undefined2 *)segment(in_SS,sVar23 + 0x2e);
  puVar7 = (undefined2 *)segment(in_SS,sVar23 + -0xe);
  *puVar7 = *puVar3;
  psVar4 = (short *)segment(in_SS,sVar23 + 0x2a);
  psVar5 = (short *)segment(in_SS,sVar23 + 0x32);
  psVar8 = (short *)segment(in_SS,sVar23 + -0xc);
  psVar9 = (short *)segment(in_SS,sVar17 + -0x10);
  *psVar9 = (*psVar4 + *psVar5) * 2 + *psVar8;
  piVar10 = (int *)segment(in_SS,sVar17 + -4);
  *piVar10 = (uVar15 & 0xffff) + 4;
  psVar4 = (short *)segment(in_SS,sVar17 + 0x26);
  sVar25 = *psVar4;
  uVar21 = 0;
  do {
    *(short *)(iVar24 + -10) = sVar25;
    piVar10 = (int *)segment(in_SS,sVar17 + -4);
    iVar22 = *piVar10;
    puVar3 = (undefined2 *)segment(in_SS,sVar17 + -0xe);
    iVar20 = CONCAT22(uVar21,*puVar3);
    puVar3 = (undefined2 *)segment(in_SS,sVar17 + -10);
    puVar7 = (undefined2 *)segment(in_SS,sVar17 + -0x10);
    while( true ) {
      psVar4 = (short *)segment(*puVar3,*puVar7);
      sVar25 = (short)iVar20;
      uVar21 = (undefined2)((uint)iVar20 >> 0x10);
      if (*psVar4 <= sVar25) break;
      iVar22 = iVar22 + *(ushort *)(iVar22 + -2) + 4;
      iVar20 = CONCAT22(uVar21,sVar25 + 1);
    }
    psVar4 = (short *)segment(in_SS,sVar17 + -0xe);
    *psVar4 = sVar25;
    piVar10 = (int *)segment(in_SS,sVar17 + -4);
    *piVar10 = iVar22;
    puVar3 = (undefined2 *)segment(in_SS,sVar17 + -0x14);
    *puVar3 = *(undefined2 *)(iVar22 + -4);
    sVar25 = *(short *)(iVar22 + -2);
    psVar4 = (short *)segment(in_SS,sVar17 + -0x16);
    *psVar4 = sVar25;
    if (sVar25 != 0) {
      psVar4 = (short *)segment(in_SS,sVar17 + 0x28);
      psVar5 = (short *)segment(in_SS,sVar17 + 0x30);
      psVar8 = (short *)segment(in_SS,sVar17 + -8);
      psVar9 = (short *)segment(in_SS,sVar17 + -0x12);
      *psVar9 = (*psVar4 + *psVar5) * 2 + *psVar8;
      *(char **)(iVar24 + -0xe) = pcVar26;
      psVar4 = (short *)segment(in_SS,sVar17 + -0x14);
      iVar20 = CONCAT22(uVar21,*psVar4);
      puVar3 = (undefined2 *)segment(in_SS,sVar23 + -6);
      uVar14 = *puVar3;
      psVar5 = (short *)segment(in_SS,sVar23 + -0x12);
      sVar25 = *psVar5;
      psVar5 = (short *)segment(in_SS,sVar23 + 0x24);
      sVar18 = *psVar5;
      while (psVar5 = (short *)segment(uVar14,sVar25), *psVar5 < *psVar4) {
        sVar25 = sVar25 + 2;
        pcVar26 = pcVar26 + 1;
        sVar18 = sVar18 + -1;
      }
      psVar4 = (short *)segment(in_SS,sVar23 + -0x12);
      *psVar4 = sVar25;
      psVar4 = (short *)segment(in_SS,sVar23 + -0x18);
      *psVar4 = sVar18;
      if (0 < sVar18) {
        iVar20 = CONCAT22(uVar21,sVar18);
        pcVar11 = (char *)segment(in_SS,sVar23 + 0x1a);
        cVar12 = *pcVar11;
        piVar10 = (int *)segment(in_SS,sVar23 + -4);
        iVar22 = *piVar10;
        do {
          psVar8 = (short *)segment(uVar14,sVar25);
          psVar4 = (short *)segment(in_SS,sVar23 + -0x14);
          psVar5 = (short *)segment(in_SS,sVar23 + -0x16);
          if (*psVar5 <= (short)(*psVar8 - *psVar4)) break;
          cVar13 = *(char *)((uint)(ushort)(*psVar8 - *psVar4) + iVar22);
          if (cVar13 != cVar12) {
            *pcVar26 = cVar13;
          }
          sVar25 = sVar25 + 2;
          pcVar26 = pcVar26 + 1;
          iVar20 = iVar20 + -1;
        } while (iVar20 != 0);
      }
      pcVar26 = *(char **)(iVar24 + -0xe);
    }
    psVar4 = (short *)segment(in_SS,sVar23 + 0x20);
    pcVar26 = pcVar26 + *psVar4;
    psVar4 = (short *)segment(in_SS,sVar23 + -0x10);
    psVar5 = (short *)segment(in_SS,sVar23 + -0x10);
    *psVar5 = *psVar4 + 2;
    uVar21 = (undefined2)((uint)iVar20 >> 0x10);
    sVar25 = *(short *)(iVar24 + -10) + -1;
    if (sVar25 < 1) {
      return;
    }
  } while( true );
}



