// ═══════════════════════════════════════════════════════════════════
// extern-stubs.js — Stub implementations for external functions
//
// Win32 API, C runtime, MFC, and Ghidra-named functions that
// exist in the binary but have no JS equivalent.
// Each stub logs when called so we can see what the binary wanted.
//
// Generated by transform.cjs — 383 stubs
// ═══════════════════════════════════════════════════════════════════

import { stubCall } from './devlog.js';
import { G } from './globals.js';

// ── GDI layer: real implementations replace stubCall for rendering ──
export {
  BitBlt, StretchBlt, CreateCompatibleDC, CreateCompatibleBitmap,
  CreateDIBSection, SelectObject, DeleteObject, DeleteDC,
  GetDC, ReleaseDC, GetDeviceCaps, GetStockObject,
  CreateSolidBrush, CreatePen, FillRect, FrameRect,
  LineTo, MoveToEx, SetPixel, GetPixel,
  SetBkMode, SetBkColor, SetTextColor, SetTextAlign, GetTextAlign,
  CreateFontIndirectA, DrawTextA, GetTextExtentPointA, GetTextMetricsA,
  SetRect, CopyRect, OffsetRect, InflateRect, IntersectRect,
  UnionRect, PtInRect, IsRectEmpty, EqualRect,
  CreatePalette, SelectPalette, RealizePalette, AnimatePalette,
  SetDIBColorTable, GetDIBColorTable,
  InvalidateRect, ValidateRect, UpdateWindow, BeginPaint, EndPaint,
  GetClientRect, GdiFlush,
} from './gdi.js';

// ── Heap bump allocator for GlobalAlloc/GlobalLock ──
// Map gen and other init functions allocate memory via Win32 heap APIs.
// We bump-allocate from the end of the _MEM buffer downward.
let _heapPtr = G._MEM.length; // starts at top of buffer
const _heapAllocs = new Map(); // handle → {ptr, size}

export function AVIFileExit(...args) { return stubCall('AVIFileExit', args); }
export function AVIFileGetStream(...args) { return stubCall('AVIFileGetStream', args); }
export function AVIFileInit(...args) { return stubCall('AVIFileInit', args); }
export function AVIFileOpenA(...args) { return stubCall('AVIFileOpenA', args); }
export function AVIFileRelease(...args) { return stubCall('AVIFileRelease', args); }
export function AVIStreamFindSample(...args) { return stubCall('AVIStreamFindSample', args); }
export function AVIStreamInfoA(...args) { return stubCall('AVIStreamInfoA', args); }
export function AVIStreamLength(...args) { return stubCall('AVIStreamLength', args); }
export function AVIStreamRead(...args) { return stubCall('AVIStreamRead', args); }
export function AVIStreamReadFormat(...args) { return stubCall('AVIStreamReadFormat', args); }
export function AVIStreamRelease(...args) { return stubCall('AVIStreamRelease', args); }
export function AVIStreamSampleToTime(...args) { return stubCall('AVIStreamSampleToTime', args); }
export function AVIStreamStart(...args) { return stubCall('AVIStreamStart', args); }
export function AVIStreamTimeToSample(...args) { return stubCall('AVIStreamTimeToSample', args); }
export function AddFontResourceA(...args) { return stubCall('AddFontResourceA', args); }
// GDI: export function AnimatePalette(...args) { return stubCall('AnimatePalette', args); }
export function AppendMenuA(...args) { return stubCall('AppendMenuA', args); }
export function ArrayUnwindFilter(...args) { return stubCall('ArrayUnwindFilter', args); }
// GDI: export function BeginPaint(...args) { return stubCall('BeginPaint', args); }
// GDI: export function BitBlt(...args) { return stubCall('BitBlt', args); }
export function BringWindowToTop(...args) { return stubCall('BringWindowToTop', args); }
export function CARRY4(...args) { return stubCall('CARRY4', args); }
export function CArchive__SetObjectSchema(...args) { return stubCall('CArchive__SetObjectSchema', args); }
export function CBitmapButton(...args) { return stubCall('CBitmapButton', args); }
export function CBitmapButton__CBitmapButton(...args) { return stubCall('CBitmapButton__CBitmapButton', args); }
export function CCheckListBox__GetCheckStyle(...args) { return stubCall('CCheckListBox__GetCheckStyle', args); }
export function CCommandLineInfo(...args) { return stubCall('CCommandLineInfo', args); }
export function CCommandLineInfo__CCommandLineInfo(...args) { return stubCall('CCommandLineInfo__CCommandLineInfo', args); }
export function CControlBarInfo(...args) { return stubCall('CControlBarInfo', args); }
export function CControlBarInfo__CControlBarInfo(...args) { return stubCall('CControlBarInfo__CControlBarInfo', args); }
export function CDaoFieldInfo(...args) { return stubCall('CDaoFieldInfo', args); }
export function CDaoFieldInfo__CDaoFieldInfo(...args) { return stubCall('CDaoFieldInfo__CDaoFieldInfo', args); }
export function CDataBoundProperty(...args) { return stubCall('CDataBoundProperty', args); }
export function CDataBoundProperty___scalar_deleting_destructor_(...args) { return stubCall('CDataBoundProperty___scalar_deleting_destructor_', args); }
export function CDialog__SetHelpID(...args) { return stubCall('CDialog__SetHelpID', args); }
export function CHtmlStream__Reset(...args) { return stubCall('CHtmlStream__Reset', args); }
export function CMiniDockFrameWnd__OnClose(...args) { return stubCall('CMiniDockFrameWnd__OnClose', args); }
export function CMiniFrameWnd(...args) { return stubCall('CMiniFrameWnd', args); }
export function CMiniFrameWnd__CMiniFrameWnd(...args) { return stubCall('CMiniFrameWnd__CMiniFrameWnd', args); }
export function COleClientItem__GetActiveView(...args) { return stubCall('COleClientItem__GetActiveView', args); }
export function COleCntrFrameWnd(...args) { return stubCall('COleCntrFrameWnd', args); }
export function COleCntrFrameWnd__COleCntrFrameWnd(...args) { return stubCall('COleCntrFrameWnd__COleCntrFrameWnd', args); }
export function COleControlSite__SetDlgCtrlID(...args) { return stubCall('COleControlSite__SetDlgCtrlID', args); }
export function CPropertySheet__EnableStackedTabs(...args) { return stubCall('CPropertySheet__EnableStackedTabs', args); }
export function CRichEditCntrItem__GetActiveView(...args) { return stubCall('CRichEditCntrItem__GetActiveView', args); }
export function CRichEditDoc__InvalidateObjectCache(...args) { return stubCall('CRichEditDoc__InvalidateObjectCache', args); }
export function CSocket__Create(...args) { return stubCall('CSocket__Create', args); }
export function CSplitterWnd__IsTracking(...args) { return stubCall('CSplitterWnd__IsTracking', args); }
export function CString__CString(...args) { return stubCall('CString__CString', args); }
export function CallWindowProcA(...args) { return stubCall('CallWindowProcA', args); }
export function CharLowerA(...args) { return stubCall('CharLowerA', args); }
export function CharUpperA(...args) { return stubCall('CharUpperA', args); }
export function CheckMenuItem(...args) { return stubCall('CheckMenuItem', args); }
export function ClientToScreen(...args) { return stubCall('ClientToScreen', args); }
export function CloseHandle(...args) { return stubCall('CloseHandle', args); }
export function CommDlgExtendedError(...args) { return stubCall('CommDlgExtendedError', args); }
export function CompareStringA(...args) { return stubCall('CompareStringA', args); }
export function CompareStringW(...args) { return stubCall('CompareStringW', args); }
// GDI: export function CopyRect(...args) { return stubCall('CopyRect', args); }
export function CreateBitmap(...args) { return stubCall('CreateBitmap', args); }
// GDI: export function CreateCompatibleBitmap(...args) { return stubCall('CreateCompatibleBitmap', args); }
// GDI: export function CreateCompatibleDC(...args) { return stubCall('CreateCompatibleDC', args); }
// GDI: export function CreateDIBSection(...args) { return stubCall('CreateDIBSection', args); }
export function CreateDirectoryA(...args) { return stubCall('CreateDirectoryA', args); }
export function CreateFileA(...args) { return stubCall('CreateFileA', args); }
export function CreateFileMappingA(...args) { return stubCall('CreateFileMappingA', args); }
// GDI: export function CreateFontIndirectA(...args) { return stubCall('CreateFontIndirectA', args); }
export function CreateMenu(...args) { return stubCall('CreateMenu', args); }
export function CreateMutexA(...args) { return stubCall('CreateMutexA', args); }
// GDI: export function CreatePalette(...args) { return stubCall('CreatePalette', args); }
// GDI: export function CreatePen(...args) { return stubCall('CreatePen', args); }
export function CreatePopupMenu(...args) { return stubCall('CreatePopupMenu', args); }
// GDI: export function CreateSolidBrush(...args) { return stubCall('CreateSolidBrush', args); }
export function CreateWindowExA(...args) { return stubCall('CreateWindowExA', args); }
export function DEVIATION(...args) { return stubCall('DEVIATION', args); }
export function DebugBreak(...args) { return stubCall('DebugBreak', args); }
export function DefWindowProcA(...args) { return stubCall('DefWindowProcA', args); }
// GDI: export function DeleteDC(...args) { return stubCall('DeleteDC', args); }
export function DeleteFileA(...args) { return stubCall('DeleteFileA', args); }
export function DeleteMenu(...args) { return stubCall('DeleteMenu', args); }
// GDI: export function DeleteObject(...args) { return stubCall('DeleteObject', args); }
export function DestroyCursor(...args) { return stubCall('DestroyCursor', args); }
export function DestroyIcon(...args) { return stubCall('DestroyIcon', args); }
export function DestroyMenu(...args) { return stubCall('DestroyMenu', args); }
export function DestroyWindow(...args) { return stubCall('DestroyWindow', args); }
export function DirectDrawCreate(...args) { return stubCall('DirectDrawCreate', args); }
export function DrawIcon(...args) { return stubCall('DrawIcon', args); }
export function DrawMenuBar(...args) { return stubCall('DrawMenuBar', args); }
// GDI: export function DrawTextA(...args) { return stubCall('DrawTextA', args); }
export function EnableMenuItem(...args) { return stubCall('EnableMenuItem', args); }
export function EnableWindow(...args) { return stubCall('EnableWindow', args); }
// GDI: export function EndPaint(...args) { return stubCall('EndPaint', args); }
export function EnumFontFamiliesA(...args) { return stubCall('EnumFontFamiliesA', args); }
export function ExitProcess(...args) { return stubCall('ExitProcess', args); }
// GDI: export function FillRect(...args) { return stubCall('FillRect', args); }
export function FindFirstFileA(...args) { return stubCall('FindFirstFileA', args); }
export function FindNextFileA(...args) { return stubCall('FindNextFileA', args); }
export function FindResourceA(...args) { return stubCall('FindResourceA', args); }
export function FindWindowA(...args) { return stubCall('FindWindowA', args); }
export function FlushFileBuffers(...args) { return stubCall('FlushFileBuffers', args); }
// GDI: export function FrameRect(...args) { return stubCall('FrameRect', args); }
export function FrameUnwindFilter(...args) { return stubCall('FrameUnwindFilter', args); }
export function FreeEnvironmentStringsA(...args) { return stubCall('FreeEnvironmentStringsA', args); }
export function FreeEnvironmentStringsW(...args) { return stubCall('FreeEnvironmentStringsW', args); }
export function FreeLibrary(...args) { return stubCall('FreeLibrary', args); }
export function FreeResource(...args) { return stubCall('FreeResource', args); }
export function GetACP(...args) { return stubCall('GetACP', args); }
export function GetAsyncKeyState(...args) { return stubCall('GetAsyncKeyState', args); }
export function GetBitmapDimensionEx(...args) { return stubCall('GetBitmapDimensionEx', args); }
export function GetCPInfo(...args) { return stubCall('GetCPInfo', args); }
export function GetClassLongA(...args) { return stubCall('GetClassLongA', args); }
export function GetClassNameA(...args) { return stubCall('GetClassNameA', args); }
// GDI: export function GetClientRect(...args) { return stubCall('GetClientRect', args); }
export function GetCommandLineA(...args) { return stubCall('GetCommandLineA', args); }
export function GetCurrentDirectoryA(...args) { return stubCall('GetCurrentDirectoryA', args); }
export function GetCurrentProcess(...args) { return stubCall('GetCurrentProcess', args); }
export function GetCursorPos(...args) { return stubCall('GetCursorPos', args); }
// GDI: export function GetDC(...args) { return stubCall('GetDC', args); }
// GDI: export function GetDIBColorTable(...args) { return stubCall('GetDIBColorTable', args); }
// GDI: export function GetDeviceCaps(...args) { return stubCall('GetDeviceCaps', args); }
export function GetDriveTypeA(...args) { return stubCall('GetDriveTypeA', args); }
export function GetEnvironmentStrings(...args) { return stubCall('GetEnvironmentStrings', args); }
export function GetEnvironmentStringsW(...args) { return stubCall('GetEnvironmentStringsW', args); }
export function GetFileAttributesA(...args) { return stubCall('GetFileAttributesA', args); }
export function GetFileSize(...args) { return stubCall('GetFileSize', args); }
export function GetFileType(...args) { return stubCall('GetFileType', args); }
export function GetFocus(...args) { return stubCall('GetFocus', args); }
export function GetFullPathNameA(...args) { return stubCall('GetFullPathNameA', args); }
export function GetKeyState(...args) { return stubCall('GetKeyState', args); }
export function GetLastError(...args) { return stubCall('GetLastError', args); }
export function GetLocalTime(...args) { return stubCall('GetLocalTime', args); }
export function GetLogicalDriveStringsA(...args) { return stubCall('GetLogicalDriveStringsA', args); }
export function GetLogicalDrives(...args) { return stubCall('GetLogicalDrives', args); }
export function GetMenu(...args) { return stubCall('GetMenu', args); }
export function GetMenuItemCount(...args) { return stubCall('GetMenuItemCount', args); }
export function GetMenuItemID(...args) { return stubCall('GetMenuItemID', args); }
export function GetModuleFileNameA(...args) { return stubCall('GetModuleFileNameA', args); }
export function GetModuleHandleA(...args) { return stubCall('GetModuleHandleA', args); }
export function GetNearestPaletteIndex(...args) { return stubCall('GetNearestPaletteIndex', args); }
export function GetOEMCP(...args) { return stubCall('GetOEMCP', args); }
export function GetOpenFileNameA(...args) { return stubCall('GetOpenFileNameA', args); }
export function GetPaletteEntries(...args) { return stubCall('GetPaletteEntries', args); }
export function GetParent(...args) { return stubCall('GetParent', args); }
// GDI: export function GetPixel(...args) { return stubCall('GetPixel', args); }
export function GetPrivateProfileIntA(...args) { return stubCall('GetPrivateProfileIntA', args); }
export function GetProcAddress(...args) { return stubCall('GetProcAddress', args); }
export function GetSaveFileNameA(...args) { return stubCall('GetSaveFileNameA', args); }
export function GetScrollPos(...args) { return stubCall('GetScrollPos', args); }
export function GetScrollRange(...args) { return stubCall('GetScrollRange', args); }
export function GetStartupInfoA(...args) { return stubCall('GetStartupInfoA', args); }
export function GetStdHandle(...args) { return stubCall('GetStdHandle', args); }
// GDI: export function GetStockObject(...args) { return stubCall('GetStockObject', args); }
export function GetStringTypeA(...args) { return stubCall('GetStringTypeA', args); }
export function GetStringTypeW(...args) { return stubCall('GetStringTypeW', args); }
export function GetSubMenu(...args) { return stubCall('GetSubMenu', args); }
export function GetSystemPaletteEntries(...args) { return stubCall('GetSystemPaletteEntries', args); }
export function GetSystemTime(...args) { return stubCall('GetSystemTime', args); }
// GDI: export function GetTextAlign(...args) { return stubCall('GetTextAlign', args); }
// GDI: export function GetTextExtentPointA(...args) { return stubCall('GetTextExtentPointA', args); }
// GDI: export function GetTextMetricsA(...args) { return stubCall('GetTextMetricsA', args); }
export function GetTimeZoneInformation(...args) { return stubCall('GetTimeZoneInformation', args); }
export function GetVersion(...args) { return stubCall('GetVersion', args); }
export function GetWindow(...args) { return stubCall('GetWindow', args); }
export function GetWindowLongA(...args) { return stubCall('GetWindowLongA', args); }
export function GetWindowRect(...args) { return stubCall('GetWindowRect', args); }
export function GlobalAlloc(flags, size) {
  // Bump-allocate from top of _MEM buffer
  const aligned = (size + 15) & ~15; // 16-byte align
  _heapPtr -= aligned;
  if (_heapPtr < G._MEM.length / 2) {
    console.error('GlobalAlloc: heap exhausted at', _heapPtr);
    return 0;
  }
  const handle = _heapPtr; // use ptr as handle
  _heapAllocs.set(handle, { ptr: _heapPtr, size: aligned });
  // Zero the allocated region
  G._MEM.fill(0, _heapPtr, _heapPtr + aligned);
  return handle;
}
export function GlobalCompact(...args) { return stubCall('GlobalCompact', args); }
export function GlobalFree(handle) {
  _heapAllocs.delete(handle);
  return 0;
}
export function GlobalHandle(...args) { return stubCall('GlobalHandle', args); }
export function GlobalLock(handle) {
  // Returns the pointer (same as handle in our model)
  const alloc = _heapAllocs.get(handle);
  return alloc ? alloc.ptr : handle;
}
export function GlobalSize(handle) {
  const alloc = _heapAllocs.get(handle);
  return alloc ? alloc.size : 0;
}
export function GlobalUnlock(handle) { return 0; }
export function HELPERS(...args) { return stubCall('HELPERS', args); }
export function HeapAlloc(...args) { return stubCall('HeapAlloc', args); }
export function HeapCreate(...args) { return stubCall('HeapCreate', args); }
export function HeapDestroy(...args) { return stubCall('HeapDestroy', args); }
export function HeapFree(...args) { return stubCall('HeapFree', args); }
export function HeapReAlloc(...args) { return stubCall('HeapReAlloc', args); }
export function HeapValidate(...args) { return stubCall('HeapValidate', args); }
export function ICClose(...args) { return stubCall('ICClose', args); }
export function ICLocate(...args) { return stubCall('ICLocate', args); }
export function ICSendMessage(...args) { return stubCall('ICSendMessage', args); }
// GDI: export function InflateRect(...args) { return stubCall('InflateRect', args); }
export function InitCommonControls(...args) { return stubCall('InitCommonControls', args); }
export function InsertMenuA(...args) { return stubCall('InsertMenuA', args); }
export function InterlockedDecrement(...args) { return stubCall('InterlockedDecrement', args); }
export function InterlockedIncrement(...args) { return stubCall('InterlockedIncrement', args); }
// GDI: export function IntersectRect(...args) { return stubCall('IntersectRect', args); }
// GDI: export function InvalidateRect(...args) { return stubCall('InvalidateRect', args); }
export function Iostream_init(...args) { return stubCall('Iostream_init', args); }
export function Iostream_init__Iostream_init(...args) { return stubCall('Iostream_init__Iostream_init', args); }
export function IsBadCodePtr(...args) { return stubCall('IsBadCodePtr', args); }
export function IsBadHugeReadPtr(...args) { return stubCall('IsBadHugeReadPtr', args); }
export function IsBadReadPtr(...args) { return stubCall('IsBadReadPtr', args); }
export function IsBadWritePtr(...args) { return stubCall('IsBadWritePtr', args); }
export function IsChild(...args) { return stubCall('IsChild', args); }
export function IsIconic(...args) { return stubCall('IsIconic', args); }
export function IsWindow(...args) { return stubCall('IsWindow', args); }
export function IsWindowVisible(...args) { return stubCall('IsWindowVisible', args); }
export function IsZoomed(...args) { return stubCall('IsZoomed', args); }
export function KillTimer(...args) { return stubCall('KillTimer', args); }
export function LCMapStringA(...args) { return stubCall('LCMapStringA', args); }
export function LCMapStringW(...args) { return stubCall('LCMapStringW', args); }
export function LOCK(...args) { return stubCall('LOCK', args); }
// GDI: export function LineTo(...args) { return stubCall('LineTo', args); }
export function LoadBitmapA(...args) { return stubCall('LoadBitmapA', args); }
export function LoadCursorA(...args) { return stubCall('LoadCursorA', args); }
export function LoadIconA(...args) { return stubCall('LoadIconA', args); }
export function LoadLibraryA(...args) { return stubCall('LoadLibraryA', args); }
export function LoadLibraryExA(...args) { return stubCall('LoadLibraryExA', args); }
export function LoadMenuA(...args) { return stubCall('LoadMenuA', args); }
export function LoadResource(...args) { return stubCall('LoadResource', args); }
export function LocalAlloc(...args) { return stubCall('LocalAlloc', args); }
export function LocalFree(...args) { return stubCall('LocalFree', args); }
export function LocalLock(...args) { return stubCall('LocalLock', args); }
export function LocalUnlock(...args) { return stubCall('LocalUnlock', args); }
export function LockResource(...args) { return stubCall('LockResource', args); }
export function MCIWndCreateA(...args) { return stubCall('MCIWndCreateA', args); }
export function MapViewOfFile(...args) { return stubCall('MapViewOfFile', args); }
export function MapWindowPoints(...args) { return stubCall('MapWindowPoints', args); }
export function MessageBeep(...args) { return stubCall('MessageBeep', args); }
export function MessageBoxA(...args) { return stubCall('MessageBoxA', args); }
export function ModifyMenuA(...args) { return stubCall('ModifyMenuA', args); }
export function MoveFileA(...args) { return stubCall('MoveFileA', args); }
// GDI: export function MoveToEx(...args) { return stubCall('MoveToEx', args); }
export function MoveWindow(...args) { return stubCall('MoveWindow', args); }
export function MultiByteToWideChar(...args) { return stubCall('MultiByteToWideChar', args); }
// GDI: export function OffsetRect(...args) { return stubCall('OffsetRect', args); }
export function OpenFile(...args) { return stubCall('OpenFile', args); }
export function OutputDebugStringA(...args) { return stubCall('OutputDebugStringA', args); }
// GDI: export function PtInRect(...args) { return stubCall('PtInRect', args); }
export function ROUND(...args) { return stubCall('ROUND', args); }
export function ReadFile(...args) { return stubCall('ReadFile', args); }
// GDI: export function RealizePalette(...args) { return stubCall('RealizePalette', args); }
export function RegCloseKey(...args) { return stubCall('RegCloseKey', args); }
export function RegCreateKeyExA(...args) { return stubCall('RegCreateKeyExA', args); }
export function RegOpenKeyExA(...args) { return stubCall('RegOpenKeyExA', args); }
export function RegQueryValueExA(...args) { return stubCall('RegQueryValueExA', args); }
export function RegSetValueExA(...args) { return stubCall('RegSetValueExA', args); }
export function RegisterClassA(...args) { return stubCall('RegisterClassA', args); }
export function ReleaseCapture(...args) { return stubCall('ReleaseCapture', args); }
// GDI: export function ReleaseDC(...args) { return stubCall('ReleaseDC', args); }
export function RemoveFontResourceA(...args) { return stubCall('RemoveFontResourceA', args); }
export function RemoveMenu(...args) { return stubCall('RemoveMenu', args); }
export function RtlUnwind(...args) { return stubCall('RtlUnwind', args); }
export function SCARRY1(...args) { return stubCall('SCARRY1', args); }
export function ScreenToClient(...args) { return stubCall('ScreenToClient', args); }
// GDI: export function SelectObject(...args) { return stubCall('SelectObject', args); }
// GDI: export function SelectPalette(...args) { return stubCall('SelectPalette', args); }
// GDI: export function SetBkColor(...args) { return stubCall('SetBkColor', args); }
// GDI: export function SetBkMode(...args) { return stubCall('SetBkMode', args); }
export function SetCapture(...args) { return stubCall('SetCapture', args); }
export function SetClassLongA(...args) { return stubCall('SetClassLongA', args); }
export function SetConsoleCtrlHandler(...args) { return stubCall('SetConsoleCtrlHandler', args); }
export function SetCurrentDirectoryA(...args) { return stubCall('SetCurrentDirectoryA', args); }
export function SetCursor(...args) { return stubCall('SetCursor', args); }
// GDI: export function SetDIBColorTable(...args) { return stubCall('SetDIBColorTable', args); }
export function SetEndOfFile(...args) { return stubCall('SetEndOfFile', args); }
export function SetEnvironmentVariableA(...args) { return stubCall('SetEnvironmentVariableA', args); }
export function SetErrorMode(...args) { return stubCall('SetErrorMode', args); }
export function SetFilePointer(...args) { return stubCall('SetFilePointer', args); }
export function SetFocus(...args) { return stubCall('SetFocus', args); }
export function SetHandleCount(...args) { return stubCall('SetHandleCount', args); }
export function SetMenu(...args) { return stubCall('SetMenu', args); }
export function SetPaletteEntries(...args) { return stubCall('SetPaletteEntries', args); }
// GDI: export function SetPixel(...args) { return stubCall('SetPixel', args); }
export function SetScrollPos(...args) { return stubCall('SetScrollPos', args); }
export function SetScrollRange(...args) { return stubCall('SetScrollRange', args); }
export function SetStdHandle(...args) { return stubCall('SetStdHandle', args); }
// GDI: export function SetTextAlign(...args) { return stubCall('SetTextAlign', args); }
// GDI: export function SetTextColor(...args) { return stubCall('SetTextColor', args); }
export function SetTimer(...args) { return stubCall('SetTimer', args); }
export function SetUnhandledExceptionFilter(...args) { return stubCall('SetUnhandledExceptionFilter', args); }
export function SetWindowLongA(...args) { return stubCall('SetWindowLongA', args); }
export function SetWindowPos(...args) { return stubCall('SetWindowPos', args); }
export function SetWindowTextA(...args) { return stubCall('SetWindowTextA', args); }
export function SetWindowsHookExA(...args) { return stubCall('SetWindowsHookExA', args); }
export function ShowCursor(...args) { return stubCall('ShowCursor', args); }
export function ShowScrollBar(...args) { return stubCall('ShowScrollBar', args); }
export function ShowWindow(...args) { return stubCall('ShowWindow', args); }
export function Sleep(...args) { return stubCall('Sleep', args); }
// GDI: export function StretchBlt(...args) { return stubCall('StretchBlt', args); }
export function TerminateProcess(...args) { return stubCall('TerminateProcess', args); }
export function TrackPopupMenu(...args) { return stubCall('TrackPopupMenu', args); }
export function UNLOCK(...args) { return stubCall('UNLOCK', args); }
export function UnhandledExceptionFilter(...args) { return stubCall('UnhandledExceptionFilter', args); }
export function UnhookWindowsHookEx(...args) { return stubCall('UnhookWindowsHookEx', args); }
// GDI: export function UnionRect(...args) { return stubCall('UnionRect', args); }
export function UnmapViewOfFile(...args) { return stubCall('UnmapViewOfFile', args); }
export function UnregisterClassA(...args) { return stubCall('UnregisterClassA', args); }
// GDI: export function UpdateWindow(...args) { return stubCall('UpdateWindow', args); }
// GDI: export function ValidateRect(...args) { return stubCall('ValidateRect', args); }
export function VirtualAlloc(...args) { return stubCall('VirtualAlloc', args); }
export function VirtualFree(...args) { return stubCall('VirtualFree', args); }
export function WideCharToMultiByte(...args) { return stubCall('WideCharToMultiByte', args); }
export function WinExec(...args) { return stubCall('WinExec', args); }
export function WriteFile(...args) { return stubCall('WriteFile', args); }
export function WritePrivateProfileStringA(...args) { return stubCall('WritePrivateProfileStringA', args); }
export function XD_ActivateServer(...args) { return stubCall('XD_ActivateServer', args); }
export function XD_CloseConnection(...args) { return stubCall('XD_CloseConnection', args); }
export function XD_FlushSendBuffer(...args) { return stubCall('XD_FlushSendBuffer', args); }
export function XD_GetCurrentProtoAddr(...args) { return stubCall('XD_GetCurrentProtoAddr', args); }
export function XD_GetXDaemonVersion(...args) { return stubCall('XD_GetXDaemonVersion', args); }
export function XD_InFlushSendBuffer(...args) { return stubCall('XD_InFlushSendBuffer', args); }
export function XD_InitializeModem(...args) { return stubCall('XD_InitializeModem', args); }
export function XD_InitializeSerial(...args) { return stubCall('XD_InitializeSerial', args); }
export function XD_InitializeSocketsIPXSPX(...args) { return stubCall('XD_InitializeSocketsIPXSPX', args); }
export function XD_InitializeSocketsTCP(...args) { return stubCall('XD_InitializeSocketsTCP', args); }
export function XD_LaunchedByLobby(...args) { return stubCall('XD_LaunchedByLobby', args); }
export function XD_LobbySendMessage(...args) { return stubCall('XD_LobbySendMessage', args); }
export function XD_OpenConnection(...args) { return stubCall('XD_OpenConnection', args); }
export function XD_ResetLibrary(...args) { return stubCall('XD_ResetLibrary', args); }
export function XD_SendBroadcastData(...args) { return stubCall('XD_SendBroadcastData', args); }
export function XD_SendSecureData(...args) { return stubCall('XD_SendSecureData', args); }
export function XD_ServerCloseConnection(...args) { return stubCall('XD_ServerCloseConnection', args); }
export function XD_SetBroadcastReceive(...args) { return stubCall('XD_SetBroadcastReceive', args); }
export function XD_SetNewClientConnection(...args) { return stubCall('XD_SetNewClientConnection', args); }
export function XD_SetOnClientConnectionToServer(...args) { return stubCall('XD_SetOnClientConnectionToServer', args); }
export function XD_SetOnConnectionLost(...args) { return stubCall('XD_SetOnConnectionLost', args); }
export function XD_SetOversizedMessageCB(...args) { return stubCall('XD_SetOversizedMessageCB', args); }
export function XD_SetSecureReceive(...args) { return stubCall('XD_SetSecureReceive', args); }
export function XD_ShutdownModem(...args) { return stubCall('XD_ShutdownModem', args); }
export function XD_ShutdownSockets(...args) { return stubCall('XD_ShutdownSockets', args); }
export function XD_ShutdownTEN(...args) { return stubCall('XD_ShutdownTEN', args); }
export function XD_StopConnections(...args) { return stubCall('XD_StopConnections', args); }
export function _BLOCK_TYPE(...args) { return stubCall('_BLOCK_TYPE', args); }
export function _BLOCK_TYPE_IS_VALID(...args) { return stubCall('_BLOCK_TYPE_IS_VALID', args); }
export function _CallMemberFunction1(...args) { return stubCall('_CallMemberFunction1', args); }
export function _CallMemberFunction2(...args) { return stubCall('_CallMemberFunction2', args); }
export function _CrtCheckMemory(...args) { return stubCall('_CrtCheckMemory', args); }
export function _CrtIsValidHeapPointer(...args) { return stubCall('_CrtIsValidHeapPointer', args); }
export function _T(...args) { return stubCall('_T', args); }
export function _Timevec(...args) { return stubCall('_Timevec', args); }
export function _Timevec___Timevec(...args) { return stubCall('_Timevec___Timevec', args); }
export function __atodbl(...args) { return stubCall('__atodbl', args); }
export function __ld12tod(...args) { return stubCall('__ld12tod', args); }
export function __mkdir(...args) { return stubCall('__mkdir', args); }
export function __wrename(...args) { return stubCall('__wrename', args); }
export function _hread(...args) { return stubCall('_hread', args); }
export function _llseek(...args) { return stubCall('_llseek', args); }
export function _vector_deleting_destructor_(...args) { return stubCall('_vector_deleting_destructor_', args); }
export function block(...args) { return stubCall('block', args); }
export function exe(...args) { return stubCall('exe', args); }
export function hs(...args) { return stubCall('hs', args); }
export function int(...args) { return stubCall('int', args); }
export function ios__delbuf(...args) { return stubCall('ios__delbuf', args); }
export function ios__lockptr(...args) { return stubCall('ios__lockptr', args); }
export function ios__tie(...args) { return stubCall('ios__tie', args); }
export function ios__width(...args) { return stubCall('ios__width', args); }
export function ios_base__precision(...args) { return stubCall('ios_base__precision', args); }
export function ios_base__width(...args) { return stubCall('ios_base__width', args); }
export function lstrcpyA(...args) { return stubCall('lstrcpyA', args); }
export function lstrlenA(...args) { return stubCall('lstrlenA', args); }
export function mciGetDeviceIDA(...args) { return stubCall('mciGetDeviceIDA', args); }
export function mciSendCommandA(...args) { return stubCall('mciSendCommandA', args); }
export function mmioAdvance(...args) { return stubCall('mmioAdvance', args); }
export function mmioAscend(...args) { return stubCall('mmioAscend', args); }
export function mmioClose(...args) { return stubCall('mmioClose', args); }
export function mmioDescend(...args) { return stubCall('mmioDescend', args); }
export function mmioGetInfo(...args) { return stubCall('mmioGetInfo', args); }
export function mmioOpenA(...args) { return stubCall('mmioOpenA', args); }
export function mmioRead(...args) { return stubCall('mmioRead', args); }
export function mmioSeek(...args) { return stubCall('mmioSeek', args); }
export function segment(...args) { return stubCall('segment', args); }
export function sndPlaySoundA(...args) { return stubCall('sndPlaySoundA', args); }
export function streambuf__egptr(...args) { return stubCall('streambuf__egptr', args); }
export function swi(...args) { return stubCall('swi', args); }
export function timeBeginPeriod(...args) { return stubCall('timeBeginPeriod', args); }
export function timeEndPeriod(...args) { return stubCall('timeEndPeriod', args); }
export function timeGetTime(...args) { return stubCall('timeGetTime', args); }
export function timeKillEvent(...args) { return stubCall('timeKillEvent', args); }
export function timeSetEvent(...args) { return stubCall('timeSetEvent', args); }
export function waveOutClose(...args) { return stubCall('waveOutClose', args); }
export function waveOutGetDevCapsA(...args) { return stubCall('waveOutGetDevCapsA', args); }
export function waveOutGetErrorTextA(...args) { return stubCall('waveOutGetErrorTextA', args); }
export function waveOutGetNumDevs(...args) { return stubCall('waveOutGetNumDevs', args); }
export function waveOutGetPosition(...args) { return stubCall('waveOutGetPosition', args); }
export function waveOutOpen(...args) { return stubCall('waveOutOpen', args); }
export function waveOutPrepareHeader(...args) { return stubCall('waveOutPrepareHeader', args); }
export function waveOutReset(...args) { return stubCall('waveOutReset', args); }
export function waveOutUnprepareHeader(...args) { return stubCall('waveOutUnprepareHeader', args); }
export function waveOutWrite(...args) { return stubCall('waveOutWrite', args); }
export function wsprintfA(...args) { return stubCall('wsprintfA', args); }