// ═══════════════════════════════════════════════════════════════════
// globals.js — Flat memory model for Civ2 MGE binary transpilation
//
// ONE shared ArrayBuffer backs all DAT_ array addresses.
// Writes at any address are visible at neighboring addresses,
// matching the binary's flat memory model.
//
// Generated by build-globals.cjs — do not edit manually.
//
// Memory range: 0x61c068..0x7069f0 (938 KB)
// ═══════════════════════════════════════════════════════════════════

// ── Single flat memory buffer ──
const _BUF = new ArrayBuffer(960904);
const _MEM = new Uint8Array(_BUF);

export const G = {
  // Internal state
  _tileData: null,
  _MEM,  // exposed for debugging

  // ═══ Array views into flat memory ═══
  DAT_0061c068: new Uint8Array(_BUF, 0),  // 0x61c068
  DAT_0061c06c: new Uint8Array(_BUF, 4),  // 0x61c06c
  DAT_0061c070: new Uint8Array(_BUF, 8),  // 0x61c070
  DAT_0061c074: new Uint8Array(_BUF, 12),  // 0x61c074
  DAT_0061c128: new Uint8Array(_BUF, 192),  // 0x61c128
  DAT_0061c12c: new Uint8Array(_BUF, 196),  // 0x61c12c
  DAT_0061c168: new Uint8Array(_BUF, 256),  // 0x61c168
  DAT_0061c16c: new Uint8Array(_BUF, 260),  // 0x61c16c
  DAT_0061c170: new Uint8Array(_BUF, 264),  // 0x61c170
  DAT_0061c174: new Uint8Array(_BUF, 268),  // 0x61c174
  DAT_0061c228: new Uint8Array(_BUF, 448),  // 0x61c228
  DAT_0061c22c: new Uint8Array(_BUF, 452),  // 0x61c22c
  DAT_0061c230: new Uint8Array(_BUF, 456),  // 0x61c230
  DAT_0061c234: new Uint8Array(_BUF, 460),  // 0x61c234
  DAT_0061c268: new Uint8Array(_BUF, 512),  // 0x61c268
  DAT_0061c26c: new Uint8Array(_BUF, 516),  // 0x61c26c
  DAT_0061c270: new Uint8Array(_BUF, 520),  // 0x61c270
  DAT_0061c274: new Uint8Array(_BUF, 524),  // 0x61c274
  DAT_0061c360: new Uint8Array(_BUF, 760),  // 0x61c360
  DAT_0061c364: new Uint8Array(_BUF, 764),  // 0x61c364
  DAT_0061c368: new Uint8Array(_BUF, 768),  // 0x61c368
  DAT_0061c36c: new Uint8Array(_BUF, 772),  // 0x61c36c
  DAT_0061c580: new Uint8Array(_BUF, 1304),  // 0x61c580
  DAT_0061c584: new Uint8Array(_BUF, 1308),  // 0x61c584
  DAT_0061c588: new Uint8Array(_BUF, 1312),  // 0x61c588
  DAT_0061c58c: new Uint8Array(_BUF, 1316),  // 0x61c58c
  DAT_0061c740: new Uint8Array(_BUF, 1752),  // 0x61c740
  DAT_0061d1e8: new Uint8Array(_BUF, 4480),  // 0x61d1e8
  DAT_0061d200: new Uint8Array(_BUF, 4504),  // 0x61d200
  DAT_0061d2a8: new Uint8Array(_BUF, 4672),  // 0x61d2a8
  DAT_0061d2b0: new Uint8Array(_BUF, 4680),  // 0x61d2b0
  DAT_0061e748: new Uint8Array(_BUF, 9952),  // 0x61e748
  DAT_00624f10: new Uint8Array(_BUF, 36520),  // 0x624f10
  DAT_00625128: new Uint8Array(_BUF, 37056),  // 0x625128
  DAT_0062512c: new Uint8Array(_BUF, 37060),  // 0x62512c
  DAT_00625150: new Uint8Array(_BUF, 37096),  // 0x625150
  DAT_00625154: new Uint8Array(_BUF, 37100),  // 0x625154
  DAT_00625160: new Uint8Array(_BUF, 37112),  // 0x625160
  DAT_00625164: new Uint8Array(_BUF, 37116),  // 0x625164
  DAT_00625188: new Uint8Array(_BUF, 37152),  // 0x625188
  DAT_00625190: new Uint8Array(_BUF, 37160),  // 0x625190
  DAT_00625e70: new Uint8Array(_BUF, 40456),  // 0x625e70
  DAT_00625e74: new Uint8Array(_BUF, 40460),  // 0x625e74
  DAT_00626810: new Uint8Array(_BUF, 42920),  // 0x626810
  DAT_00627680: new Uint8Array(_BUF, 46616),  // 0x627680
  DAT_00627684: new Uint8Array(_BUF, 46620),  // 0x627684
  DAT_00627689: new Uint8Array(_BUF, 46625),  // 0x627689
  DAT_0062768a: new Uint8Array(_BUF, 46626),  // 0x62768a
  DAT_0062768b: new Uint8Array(_BUF, 46627),  // 0x62768b
  DAT_0062768c: new Uint8Array(_BUF, 46628),  // 0x62768c
  DAT_0062768d: new Uint8Array(_BUF, 46629),  // 0x62768d
  DAT_0062768e: new Uint8Array(_BUF, 46630),  // 0x62768e
  DAT_0062768f: new Uint8Array(_BUF, 46631),  // 0x62768f
  DAT_00627cc0: new Uint8Array(_BUF, 48216),  // 0x627cc0
  DAT_00627cc4: new Uint8Array(_BUF, 48220),  // 0x627cc4
  DAT_00627cc8: new Uint8Array(_BUF, 48224),  // 0x627cc8
  DAT_00627cc9: new Uint8Array(_BUF, 48225),  // 0x627cc9
  DAT_00627cca: new Uint8Array(_BUF, 48226),  // 0x627cca
  DAT_00627ccb: new Uint8Array(_BUF, 48227),  // 0x627ccb
  DAT_00627ccc: new Uint8Array(_BUF, 48228),  // 0x627ccc
  DAT_00627ccd: new Uint8Array(_BUF, 48229),  // 0x627ccd
  DAT_00627cce: new Uint8Array(_BUF, 48230),  // 0x627cce
  DAT_00627ccf: new Uint8Array(_BUF, 48231),  // 0x627ccf
  DAT_00627cd0: new Uint8Array(_BUF, 48232),  // 0x627cd0
  DAT_00627cd1: new Uint8Array(_BUF, 48233),  // 0x627cd1
  DAT_00627cd2: new Uint8Array(_BUF, 48234),  // 0x627cd2
  DAT_00627cd3: new Uint8Array(_BUF, 48235),  // 0x627cd3
  DAT_00627cd4: new Uint8Array(_BUF, 48236),  // 0x627cd4
  DAT_00627cd5: new Uint8Array(_BUF, 48237),  // 0x627cd5
  DAT_00627fe0: new Uint8Array(_BUF, 49016),  // 0x627fe0
  DAT_00628010: new Uint8Array(_BUF, 49064),  // 0x628010
  DAT_00628338: new Uint8Array(_BUF, 49872),  // 0x628338
  DAT_0062833b: new Uint8Array(_BUF, 49875),  // 0x62833b
  DAT_0062833c: new Uint8Array(_BUF, 49876),  // 0x62833c
  DAT_00628343: new Uint8Array(_BUF, 49883),  // 0x628343
  DAT_00628344: new Uint8Array(_BUF, 49884),  // 0x628344
  DAT_00628350: new Uint8Array(_BUF, 49896),  // 0x628350
  DAT_00628351: new Uint8Array(_BUF, 49897),  // 0x628351
  DAT_00628360: new Uint8Array(_BUF, 49912),  // 0x628360
  DAT_00628361: new Uint8Array(_BUF, 49913),  // 0x628361
  DAT_00628370: new Uint8Array(_BUF, 49928),  // 0x628370
  DAT_006283a0: new Uint8Array(_BUF, 49976),  // 0x6283a0
  DAT_006283d0: new Uint8Array(_BUF, 50024),  // 0x6283d0
  DAT_006283e0: new Uint8Array(_BUF, 50040),  // 0x6283e0
  DAT_00628420: new Uint8Array(_BUF, 50104),  // 0x628420
  DAT_0062b87c: new Uint8Array(_BUF, 63508),  // 0x62b87c
  DAT_0062bcb8: new Uint8Array(_BUF, 64592),  // 0x62bcb8
  DAT_0062bcc8: new Uint8Array(_BUF, 64608),  // 0x62bcc8
  DAT_0062c468: new Uint8Array(_BUF, 66560),  // 0x62c468
  DAT_0062c490: new Uint8Array(_BUF, 66600),  // 0x62c490
  DAT_0062c494: new Uint8Array(_BUF, 66604),  // 0x62c494
  DAT_0062c498: new Uint8Array(_BUF, 66608),  // 0x62c498
  DAT_0062c4cc: new Uint8Array(_BUF, 66660),  // 0x62c4cc
  DAT_0062c4d0: new Uint8Array(_BUF, 66664),  // 0x62c4d0
  DAT_0062c4d4: new Uint8Array(_BUF, 66668),  // 0x62c4d4
  DAT_0062c990: new Uint8Array(_BUF, 67880),  // 0x62c990
  DAT_0062c994: new Uint8Array(_BUF, 67884),  // 0x62c994
  DAT_0062ca48: new Uint8Array(_BUF, 68064),  // 0x62ca48
  DAT_0062ca50: new Uint8Array(_BUF, 68072),  // 0x62ca50
  DAT_0062cd38: new Uint8Array(_BUF, 68816),  // 0x62cd38
  DAT_0062cd3c: new Uint8Array(_BUF, 68820),  // 0x62cd3c
  DAT_0062cd60: new Uint8Array(_BUF, 68856),  // 0x62cd60
  DAT_0062cd64: new Uint8Array(_BUF, 68860),  // 0x62cd64
  DAT_0062cd68: new Uint8Array(_BUF, 68864),  // 0x62cd68
  DAT_0062cd6c: new Uint8Array(_BUF, 68868),  // 0x62cd6c
  DAT_0062ced0: new Uint8Array(_BUF, 69224),  // 0x62ced0
  DAT_0062d7d0: new Uint8Array(_BUF, 71528),  // 0x62d7d0
  DAT_0062d7d4: new Uint8Array(_BUF, 71532),  // 0x62d7d4
  DAT_0062d870: new Uint8Array(_BUF, 71688),  // 0x62d870
  DAT_0062e250: new Uint8Array(_BUF, 74216),  // 0x62e250
  DAT_0062e254: new Uint8Array(_BUF, 74220),  // 0x62e254
  DAT_0062e258: new Uint8Array(_BUF, 74224),  // 0x62e258
  DAT_0062e25c: new Uint8Array(_BUF, 74228),  // 0x62e25c
  DAT_0062e2d0: new Uint8Array(_BUF, 74344),  // 0x62e2d0
  DAT_0062e398: new Uint8Array(_BUF, 74544),  // 0x62e398
  DAT_0062e39c: new Uint8Array(_BUF, 74548),  // 0x62e39c
  DAT_0062e3b0: new Uint8Array(_BUF, 74568),  // 0x62e3b0
  DAT_0062e3b4: new Uint8Array(_BUF, 74572),  // 0x62e3b4
  DAT_0062e3c0: new Uint8Array(_BUF, 74584),  // 0x62e3c0
  DAT_0062e3c4: new Uint8Array(_BUF, 74588),  // 0x62e3c4
  DAT_0062e3e8: new Uint8Array(_BUF, 74624),  // 0x62e3e8
  DAT_0062e3f0: new Uint8Array(_BUF, 74632),  // 0x62e3f0
  DAT_0062e658: new Uint8Array(_BUF, 75248),  // 0x62e658
  DAT_0062e698: new Uint8Array(_BUF, 75312),  // 0x62e698
  DAT_00630d38: new Uint8Array(_BUF, 85200),  // 0x630d38
  DAT_00630d50: new Uint8Array(_BUF, 85224),  // 0x630d50
  DAT_00631acc: new Uint8Array(_BUF, 88676),  // 0x631acc
  DAT_00631b80: new Uint8Array(_BUF, 88856),  // 0x631b80
  DAT_00631b84: new Uint8Array(_BUF, 88860),  // 0x631b84
  DAT_00631bb0: new Uint8Array(_BUF, 88904),  // 0x631bb0
  DAT_00631bb4: new Uint8Array(_BUF, 88908),  // 0x631bb4
  DAT_00631bf8: new Uint8Array(_BUF, 88976),  // 0x631bf8
  DAT_00631bfc: new Uint8Array(_BUF, 88980),  // 0x631bfc
  DAT_00631c70: new Uint8Array(_BUF, 89096),  // 0x631c70
  DAT_00631ca0: new Uint8Array(_BUF, 89144),  // 0x631ca0
  DAT_006335f8: new Uint8Array(_BUF, 95632),  // 0x6335f8
  DAT_00633680: new Uint8Array(_BUF, 95768),  // 0x633680
  DAT_00634590: new Uint8Array(_BUF, 99624),  // 0x634590
  DAT_006345e8: new Uint8Array(_BUF, 99712),  // 0x6345e8
  DAT_00634f60: new Uint8Array(_BUF, 102136),  // 0x634f60
  DAT_00634f64: new Uint8Array(_BUF, 102140),  // 0x634f64
  DAT_00634f68: new Uint8Array(_BUF, 102144),  // 0x634f68
  DAT_00635a58: new Uint8Array(_BUF, 104944),  // 0x635a58
  DAT_00635df8: new Uint8Array(_BUF, 105872),  // 0x635df8
  DAT_00635dfc: new Uint8Array(_BUF, 105876),  // 0x635dfc
  DAT_00635e20: new Uint8Array(_BUF, 105912),  // 0x635e20
  DAT_00635e24: new Uint8Array(_BUF, 105916),  // 0x635e24
  DAT_00635e60: new Uint8Array(_BUF, 105976),  // 0x635e60
  DAT_00635e64: new Uint8Array(_BUF, 105980),  // 0x635e64
  DAT_00635eb8: new Uint8Array(_BUF, 106064),  // 0x635eb8
  DAT_00635ed8: new Uint8Array(_BUF, 106096),  // 0x635ed8
  DAT_006365c0: new Uint8Array(_BUF, 107864),  // 0x6365c0
  DAT_006365f8: new Uint8Array(_BUF, 107920),  // 0x6365f8
  DAT_00637eb0: new Uint8Array(_BUF, 114248),  // 0x637eb0
  DAT_006385c4: new Uint8Array(_BUF, 116060),  // 0x6385c4
  DAT_006385c8: new Uint8Array(_BUF, 116064),  // 0x6385c8
  DAT_006385d0: new Uint8Array(_BUF, 116072),  // 0x6385d0
  DAT_006397e8: new Uint8Array(_BUF, 120704),  // 0x6397e8
  DAT_00639f70: new Uint8Array(_BUF, 122632),  // 0x639f70
  DAT_0063a038: new Uint8Array(_BUF, 122832),  // 0x63a038
  DAT_0063a048: new Uint8Array(_BUF, 122848),  // 0x63a048
  DAT_0063a09a: new Uint8Array(_BUF, 122930),  // 0x63a09a
  DAT_0063a2b0: new Uint8Array(_BUF, 123464),  // 0x63a2b0
  DAT_0063a2bc: new Uint8Array(_BUF, 123476),  // 0x63a2bc
  DAT_0063ac68: new Uint8Array(_BUF, 125952),  // 0x63ac68
  DAT_0063afa0: new Uint8Array(_BUF, 126776),  // 0x63afa0
  DAT_0063afa1: new Uint8Array(_BUF, 126777),  // 0x63afa1
  DAT_0063b0b0: new Uint8Array(_BUF, 127048),  // 0x63b0b0
  DAT_0063b0c0: new Uint8Array(_BUF, 127064),  // 0x63b0c0
  DAT_0063b0cc: new Uint8Array(_BUF, 127076),  // 0x63b0cc
  DAT_0063b1b8: new Uint8Array(_BUF, 127312),  // 0x63b1b8
  DAT_0063b36c: new Uint8Array(_BUF, 127748),  // 0x63b36c
  DAT_0063b370: new Uint8Array(_BUF, 127752),  // 0x63b370
  DAT_0063b3a4: new Uint8Array(_BUF, 127804),  // 0x63b3a4
  DAT_0063b3a8: new Uint8Array(_BUF, 127808),  // 0x63b3a8
  DAT_0063cbb4: new Uint8Array(_BUF, 133964),  // 0x63cbb4
  DAT_0063cc30: new Uint8Array(_BUF, 134088),  // 0x63cc30
  DAT_0063e9a0: new Uint8Array(_BUF, 141624),  // 0x63e9a0
  DAT_0063ea28: new Uint8Array(_BUF, 141760),  // 0x63ea28
  DAT_0063efb8: new Uint8Array(_BUF, 143184),  // 0x63efb8
  DAT_0063f050: new Uint8Array(_BUF, 143336),  // 0x63f050
  DAT_0063f0c8: new Uint8Array(_BUF, 143456),  // 0x63f0c8
  DAT_0063f0ca: new Uint8Array(_BUF, 143458),  // 0x63f0ca
  DAT_0063f0cc: new Uint8Array(_BUF, 143460),  // 0x63f0cc
  DAT_0063f0ce: new Uint8Array(_BUF, 143462),  // 0x63f0ce
  DAT_0063f0d0: new Uint8Array(_BUF, 143464),  // 0x63f0d0
  DAT_0063f0d2: new Uint8Array(_BUF, 143466),  // 0x63f0d2
  DAT_0063f0d4: new Uint8Array(_BUF, 143468),  // 0x63f0d4
  DAT_0063f0d6: new Uint8Array(_BUF, 143470),  // 0x63f0d6
  DAT_0063f0d8: new Uint8Array(_BUF, 143472),  // 0x63f0d8
  DAT_0063f0da: new Uint8Array(_BUF, 143474),  // 0x63f0da
  DAT_0063f0dc: new Uint8Array(_BUF, 143476),  // 0x63f0dc
  DAT_0063f0de: new Uint8Array(_BUF, 143478),  // 0x63f0de
  DAT_0063f540: new Uint8Array(_BUF, 144600),  // 0x63f540
  DAT_0063f544: new Uint8Array(_BUF, 144604),  // 0x63f544
  DAT_0063f580: new Uint8Array(_BUF, 144664),  // 0x63f580
  DAT_0063f668: new Uint8Array(_BUF, 144896),  // 0x63f668
  DAT_0063f66c: new Uint8Array(_BUF, 144900),  // 0x63f66c
  DAT_00640a18: new Uint8Array(_BUF, 149936),  // 0x640a18
  DAT_00640ad8: new Uint8Array(_BUF, 150128),  // 0x640ad8
  DAT_00642b48: new Uint8Array(_BUF, 158432),  // 0x642b48
  DAT_00642c48: new Uint8Array(_BUF, 158688),  // 0x642c48
  DAT_00643978: new Uint8Array(_BUF, 162064),  // 0x643978
  DAT_00643a38: new Uint8Array(_BUF, 162256),  // 0x643a38
  DAT_0064b0f0: new Uint8Array(_BUF, 192648),  // 0x64b0f0
  DAT_0064b104: new Uint8Array(_BUF, 192668),  // 0x64b104
  DAT_0064b168: new Uint8Array(_BUF, 192768),  // 0x64b168
  DAT_0064b1b8: new Uint8Array(_BUF, 192848),  // 0x64b1b8
  DAT_0064b1bc: new Uint8Array(_BUF, 192852),  // 0x64b1bc
  DAT_0064b1bd: new Uint8Array(_BUF, 192853),  // 0x64b1bd
  DAT_0064b1c0: new Uint8Array(_BUF, 192856),  // 0x64b1c0
  DAT_0064b1c1: new Uint8Array(_BUF, 192857),  // 0x64b1c1
  DAT_0064b1c2: new Uint8Array(_BUF, 192858),  // 0x64b1c2
  DAT_0064b1c3: new Uint8Array(_BUF, 192859),  // 0x64b1c3
  DAT_0064b1c4: new Uint8Array(_BUF, 192860),  // 0x64b1c4
  DAT_0064b1c5: new Uint8Array(_BUF, 192861),  // 0x64b1c5
  DAT_0064b1c6: new Uint8Array(_BUF, 192862),  // 0x64b1c6
  DAT_0064b1c7: new Uint8Array(_BUF, 192863),  // 0x64b1c7
  DAT_0064b1c8: new Uint8Array(_BUF, 192864),  // 0x64b1c8
  DAT_0064b1c9: new Uint8Array(_BUF, 192865),  // 0x64b1c9
  DAT_0064b1ca: new Uint8Array(_BUF, 192866),  // 0x64b1ca
  DAT_0064b1cb: new Uint8Array(_BUF, 192867),  // 0x64b1cb
  DAT_0064b9a0: new Uint8Array(_BUF, 194872),  // 0x64b9a0
  DAT_0064b9c0: new Uint8Array(_BUF, 194904),  // 0x64b9c0
  DAT_0064b9e8: new Uint8Array(_BUF, 194944),  // 0x64b9e8
  DAT_0064ba01: new Uint8Array(_BUF, 194969),  // 0x64ba01
  DAT_0064ba10: new Uint8Array(_BUF, 194984),  // 0x64ba10
  DAT_0064ba28: new Uint8Array(_BUF, 195008),  // 0x64ba28
  DAT_0064ba48: new Uint8Array(_BUF, 195040),  // 0x64ba48
  DAT_0064ba4c: new Uint8Array(_BUF, 195044),  // 0x64ba4c
  DAT_0064ba50: new Uint8Array(_BUF, 195048),  // 0x64ba50
  DAT_0064ba54: new Uint8Array(_BUF, 195052),  // 0x64ba54
  DAT_0064ba58: new Uint8Array(_BUF, 195056),  // 0x64ba58
  DAT_0064ba5c: new Uint8Array(_BUF, 195060),  // 0x64ba5c
  DAT_0064bc2a: new Uint8Array(_BUF, 195522),  // 0x64bc2a
  DAT_0064bcb4: new Uint8Array(_BUF, 195660),  // 0x64bcb4
  DAT_0064bcbc: new Uint8Array(_BUF, 195668),  // 0x64bcbc
  DAT_0064bcf8: new Uint8Array(_BUF, 195728),  // 0x64bcf8
  DAT_0064c488: new Uint8Array(_BUF, 197664),  // 0x64c488
  DAT_0064c48c: new Uint8Array(_BUF, 197668),  // 0x64c48c
  DAT_0064c48d: new Uint8Array(_BUF, 197669),  // 0x64c48d
  DAT_0064c48e: new Uint8Array(_BUF, 197670),  // 0x64c48e
  DAT_0064c5a4: new Uint8Array(_BUF, 197948),  // 0x64c5a4
  DAT_0064c5a6: new Uint8Array(_BUF, 197950),  // 0x64c5a6
  DAT_0064c5c0: new Uint8Array(_BUF, 197976),  // 0x64c5c0
  DAT_0064c600: new Uint8Array(_BUF, 198040),  // 0x64c600
  DAT_0064c6a0: new Uint8Array(_BUF, 198200),  // 0x64c6a0
  DAT_0064c6a2: new Uint8Array(_BUF, 198202),  // 0x64c6a2
  DAT_0064c6a6: new Uint8Array(_BUF, 198206),  // 0x64c6a6
  DAT_0064c6a8: new Uint8Array(_BUF, 198208),  // 0x64c6a8
  DAT_0064c6aa: new Uint8Array(_BUF, 198210),  // 0x64c6aa
  DAT_0064c6ac: new Uint8Array(_BUF, 198212),  // 0x64c6ac
  DAT_0064c6ae: new Uint8Array(_BUF, 198214),  // 0x64c6ae
  DAT_0064c6b0: new Uint8Array(_BUF, 198216),  // 0x64c6b0
  DAT_0064c6b1: new Uint8Array(_BUF, 198217),  // 0x64c6b1
  DAT_0064c6b2: new Uint8Array(_BUF, 198218),  // 0x64c6b2
  DAT_0064c6b3: new Uint8Array(_BUF, 198219),  // 0x64c6b3
  DAT_0064c6b4: new Uint8Array(_BUF, 198220),  // 0x64c6b4
  DAT_0064c6b5: new Uint8Array(_BUF, 198221),  // 0x64c6b5
  DAT_0064c6b6: new Uint8Array(_BUF, 198222),  // 0x64c6b6
  DAT_0064c6b7: new Uint8Array(_BUF, 198223),  // 0x64c6b7
  DAT_0064c6bc: new Uint8Array(_BUF, 198228),  // 0x64c6bc
  DAT_0064c6be: new Uint8Array(_BUF, 198230),  // 0x64c6be
  DAT_0064c6bf: new Uint8Array(_BUF, 198231),  // 0x64c6bf
  DAT_0064c6c0: new Uint8Array(_BUF, 198232),  // 0x64c6c0
  DAT_0064c6c1: new Uint8Array(_BUF, 198233),  // 0x64c6c1
  DAT_0064c6c2: new Uint8Array(_BUF, 198234),  // 0x64c6c2
  DAT_0064c6c3: new Uint8Array(_BUF, 198235),  // 0x64c6c3
  DAT_0064c6e0: new Uint8Array(_BUF, 198264),  // 0x64c6e0
  DAT_0064c6e8: new Uint8Array(_BUF, 198272),  // 0x64c6e8
  DAT_0064c6f0: new Uint8Array(_BUF, 198280),  // 0x64c6f0
  DAT_0064c6f8: new Uint8Array(_BUF, 198288),  // 0x64c6f8
  DAT_0064c706: new Uint8Array(_BUF, 198302),  // 0x64c706
  DAT_0064c708: new Uint8Array(_BUF, 198304),  // 0x64c708
  DAT_0064c70a: new Uint8Array(_BUF, 198306),  // 0x64c70a
  DAT_0064c70c: new Uint8Array(_BUF, 198308),  // 0x64c70c
  DAT_0064c70e: new Uint8Array(_BUF, 198310),  // 0x64c70e
  DAT_0064c710: new Uint8Array(_BUF, 198312),  // 0x64c710
  DAT_0064c712: new Uint8Array(_BUF, 198314),  // 0x64c712
  DAT_0064c714: new Uint8Array(_BUF, 198316),  // 0x64c714
  DAT_0064c778: new Uint8Array(_BUF, 198416),  // 0x64c778
  DAT_0064c779: new Uint8Array(_BUF, 198417),  // 0x64c779
  DAT_0064c785: new Uint8Array(_BUF, 198429),  // 0x64c785
  DAT_0064c793: new Uint8Array(_BUF, 198443),  // 0x64c793
  DAT_0064c794: new Uint8Array(_BUF, 198444),  // 0x64c794
  DAT_0064c795: new Uint8Array(_BUF, 198445),  // 0x64c795
  DAT_0064c796: new Uint8Array(_BUF, 198446),  // 0x64c796
  DAT_0064c797: new Uint8Array(_BUF, 198447),  // 0x64c797
  DAT_0064c798: new Uint8Array(_BUF, 198448),  // 0x64c798
  DAT_0064c799: new Uint8Array(_BUF, 198449),  // 0x64c799
  DAT_0064c79c: new Uint8Array(_BUF, 198452),  // 0x64c79c
  DAT_0064c79d: new Uint8Array(_BUF, 198453),  // 0x64c79d
  DAT_0064c79e: new Uint8Array(_BUF, 198454),  // 0x64c79e
  DAT_0064c79f: new Uint8Array(_BUF, 198455),  // 0x64c79f
  DAT_0064c7a0: new Uint8Array(_BUF, 198456),  // 0x64c7a0
  DAT_0064c7a1: new Uint8Array(_BUF, 198457),  // 0x64c7a1
  DAT_0064c7a4: new Uint8Array(_BUF, 198460),  // 0x64c7a4
  DAT_0064c7a5: new Uint8Array(_BUF, 198461),  // 0x64c7a5
  DAT_0064c7a6: new Uint8Array(_BUF, 198462),  // 0x64c7a6
  DAT_0064c7a7: new Uint8Array(_BUF, 198463),  // 0x64c7a7
  DAT_0064c7a8: new Uint8Array(_BUF, 198464),  // 0x64c7a8
  DAT_0064c7a9: new Uint8Array(_BUF, 198465),  // 0x64c7a9
  DAT_0064c7b6: new Uint8Array(_BUF, 198478),  // 0x64c7b6
  DAT_0064c7f4: new Uint8Array(_BUF, 198540),  // 0x64c7f4
  DAT_0064c80f: new Uint8Array(_BUF, 198567),  // 0x64c80f
  DAT_0064c812: new Uint8Array(_BUF, 198570),  // 0x64c812
  DAT_0064c832: new Uint8Array(_BUF, 198602),  // 0x64c832
  DAT_0064c8b2: new Uint8Array(_BUF, 198730),  // 0x64c8b2
  DAT_0064c932: new Uint8Array(_BUF, 198858),  // 0x64c932
  DAT_0064c971: new Uint8Array(_BUF, 198921),  // 0x64c971
  DAT_0064c972: new Uint8Array(_BUF, 198922),  // 0x64c972
  DAT_0064c9b2: new Uint8Array(_BUF, 198986),  // 0x64c9b2
  DAT_0064c9f2: new Uint8Array(_BUF, 199050),  // 0x64c9f2
  DAT_0064ca32: new Uint8Array(_BUF, 199114),  // 0x64ca32
  DAT_0064ca71: new Uint8Array(_BUF, 199177),  // 0x64ca71
  DAT_0064ca72: new Uint8Array(_BUF, 199178),  // 0x64ca72
  DAT_0064ca74: new Uint8Array(_BUF, 199180),  // 0x64ca74
  DAT_0064ca76: new Uint8Array(_BUF, 199182),  // 0x64ca76
  DAT_0064ca7a: new Uint8Array(_BUF, 199186),  // 0x64ca7a
  DAT_0064ca7c: new Uint8Array(_BUF, 199188),  // 0x64ca7c
  DAT_0064ca7e: new Uint8Array(_BUF, 199190),  // 0x64ca7e
  DAT_0064ca80: new Uint8Array(_BUF, 199192),  // 0x64ca80
  DAT_0064ca82: new Uint8Array(_BUF, 199194),  // 0x64ca82
  DAT_0064ca92: new Uint8Array(_BUF, 199210),  // 0x64ca92
  DAT_0064ca93: new Uint8Array(_BUF, 199211),  // 0x64ca93
  DAT_0064ca94: new Uint8Array(_BUF, 199212),  // 0x64ca94
  DAT_0064ca96: new Uint8Array(_BUF, 199214),  // 0x64ca96
  DAT_0064ca97: new Uint8Array(_BUF, 199215),  // 0x64ca97
  DAT_0064ca99: new Uint8Array(_BUF, 199217),  // 0x64ca99
  DAT_0064ca9a: new Uint8Array(_BUF, 199218),  // 0x64ca9a
  DAT_0064ca9b: new Uint8Array(_BUF, 199219),  // 0x64ca9b
  DAT_0064ca9e: new Uint8Array(_BUF, 199222),  // 0x64ca9e
  DAT_0064caa0: new Uint8Array(_BUF, 199224),  // 0x64caa0
  DAT_0064caa2: new Uint8Array(_BUF, 199226),  // 0x64caa2
  DAT_0064caa4: new Uint8Array(_BUF, 199228),  // 0x64caa4
  DAT_0064caa6: new Uint8Array(_BUF, 199230),  // 0x64caa6
  DAT_0064caa8: new Uint8Array(_BUF, 199232),  // 0x64caa8
  DAT_0064caaa: new Uint8Array(_BUF, 199234),  // 0x64caaa
  DAT_0064caac: new Uint8Array(_BUF, 199236),  // 0x64caac
  DAT_0064caae: new Uint8Array(_BUF, 199238),  // 0x64caae
  DAT_0064cab0: new Uint8Array(_BUF, 199240),  // 0x64cab0
  DAT_0064cab2: new Uint8Array(_BUF, 199242),  // 0x64cab2
  DAT_0064cab4: new Uint8Array(_BUF, 199244),  // 0x64cab4
  DAT_0064cab6: new Uint8Array(_BUF, 199246),  // 0x64cab6
  DAT_0064cab8: new Uint8Array(_BUF, 199248),  // 0x64cab8
  DAT_0064cab9: new Uint8Array(_BUF, 199249),  // 0x64cab9
  DAT_0064cbd4: new Uint8Array(_BUF, 199532),  // 0x64cbd4
  DAT_0064cbd6: new Uint8Array(_BUF, 199534),  // 0x64cbd6
  DAT_0064cbd8: new Uint8Array(_BUF, 199536),  // 0x64cbd8
  DAT_0064cbd9: new Uint8Array(_BUF, 199537),  // 0x64cbd9
  DAT_0064f340: new Uint8Array(_BUF, 209624),  // 0x64f340
  DAT_0064f342: new Uint8Array(_BUF, 209626),  // 0x64f342
  DAT_0064f344: new Uint8Array(_BUF, 209628),  // 0x64f344
  DAT_0064f345: new Uint8Array(_BUF, 209629),  // 0x64f345
  DAT_0064f346: new Uint8Array(_BUF, 209630),  // 0x64f346
  DAT_0064f347: new Uint8Array(_BUF, 209631),  // 0x64f347
  DAT_0064f348: new Uint8Array(_BUF, 209632),  // 0x64f348
  DAT_0064f349: new Uint8Array(_BUF, 209633),  // 0x64f349
  DAT_0064f34a: new Uint8Array(_BUF, 209634),  // 0x64f34a
  DAT_0064f34b: new Uint8Array(_BUF, 209635),  // 0x64f34b
  DAT_0064f34c: new Uint8Array(_BUF, 209636),  // 0x64f34c
  DAT_0064f34d: new Uint8Array(_BUF, 209637),  // 0x64f34d
  DAT_0064f356: new Uint8Array(_BUF, 209646),  // 0x64f356
  DAT_0064f35a: new Uint8Array(_BUF, 209650),  // 0x64f35a
  DAT_0064f35c: new Uint8Array(_BUF, 209652),  // 0x64f35c
  DAT_0064f35e: new Uint8Array(_BUF, 209654),  // 0x64f35e
  DAT_0064f360: new Uint8Array(_BUF, 209656),  // 0x64f360
  DAT_0064f370: new Uint8Array(_BUF, 209672),  // 0x64f370
  DAT_0064f374: new Uint8Array(_BUF, 209676),  // 0x64f374
  DAT_0064f379: new Uint8Array(_BUF, 209681),  // 0x64f379
  DAT_0064f37a: new Uint8Array(_BUF, 209682),  // 0x64f37a
  DAT_0064f37b: new Uint8Array(_BUF, 209683),  // 0x64f37b
  DAT_0064f37c: new Uint8Array(_BUF, 209684),  // 0x64f37c
  DAT_0064f37e: new Uint8Array(_BUF, 209686),  // 0x64f37e
  DAT_0064f37f: new Uint8Array(_BUF, 209687),  // 0x64f37f
  DAT_0064f381: new Uint8Array(_BUF, 209689),  // 0x64f381
  DAT_0064f382: new Uint8Array(_BUF, 209690),  // 0x64f382
  DAT_0064f384: new Uint8Array(_BUF, 209692),  // 0x64f384
  DAT_0064f386: new Uint8Array(_BUF, 209694),  // 0x64f386
  DAT_0064f38a: new Uint8Array(_BUF, 209698),  // 0x64f38a
  DAT_0064f38c: new Uint8Array(_BUF, 209700),  // 0x64f38c
  DAT_0064f38e: new Uint8Array(_BUF, 209702),  // 0x64f38e
  DAT_0064f390: new Uint8Array(_BUF, 209704),  // 0x64f390
  DAT_0064f391: new Uint8Array(_BUF, 209705),  // 0x64f391
  DAT_0064f392: new Uint8Array(_BUF, 209706),  // 0x64f392
  DAT_0064f393: new Uint8Array(_BUF, 209707),  // 0x64f393
  DAT_0064f394: new Uint8Array(_BUF, 209708),  // 0x64f394
  DAT_00654b40: new Uint8Array(_BUF, 232152),  // 0x654b40
  DAT_00654b50: new Uint8Array(_BUF, 232168),  // 0x654b50
  DAT_00654b60: new Uint8Array(_BUF, 232184),  // 0x654b60
  DAT_00654b74: new Uint8Array(_BUF, 232204),  // 0x654b74
  DAT_00654c7c: new Uint8Array(_BUF, 232468),  // 0x654c7c
  DAT_00654da4: new Uint8Array(_BUF, 232764),  // 0x654da4
  DAT_00654ea4: new Uint8Array(_BUF, 233020),  // 0x654ea4
  DAT_00654fb0: new Uint8Array(_BUF, 233288),  // 0x654fb0
  DAT_00654fe0: new Uint8Array(_BUF, 233336),  // 0x654fe0
  DAT_00654fe4: new Uint8Array(_BUF, 233340),  // 0x654fe4
  DAT_0065512a: new Uint8Array(_BUF, 233666),  // 0x65512a
  DAT_00655142: new Uint8Array(_BUF, 233690),  // 0x655142
  DAT_0065514e: new Uint8Array(_BUF, 233702),  // 0x65514e
  DAT_0065515a: new Uint8Array(_BUF, 233714),  // 0x65515a
  DAT_006552a4: new Uint8Array(_BUF, 234044),  // 0x6552a4
  DAT_006552a8: new Uint8Array(_BUF, 234048),  // 0x6552a8
  DAT_00655358: new Uint8Array(_BUF, 234224),  // 0x655358
  DAT_0065535c: new Uint8Array(_BUF, 234228),  // 0x65535c
  DAT_00655360: new Uint8Array(_BUF, 234232),  // 0x655360
  DAT_00655364: new Uint8Array(_BUF, 234236),  // 0x655364
  DAT_00655490: new Uint8Array(_BUF, 234536),  // 0x655490
  DAT_006554f8: new Uint8Array(_BUF, 234640),  // 0x6554f8
  DAT_006554f9: new Uint8Array(_BUF, 234641),  // 0x6554f9
  DAT_006554fa: new Uint8Array(_BUF, 234642),  // 0x6554fa
  DAT_006554fb: new Uint8Array(_BUF, 234643),  // 0x6554fb
  DAT_006554fc: new Uint8Array(_BUF, 234644),  // 0x6554fc
  DAT_006554fd: new Uint8Array(_BUF, 234645),  // 0x6554fd
  DAT_006554fe: new Uint8Array(_BUF, 234646),  // 0x6554fe
  DAT_00655500: new Uint8Array(_BUF, 234648),  // 0x655500
  DAT_00655502: new Uint8Array(_BUF, 234650),  // 0x655502
  DAT_00655504: new Uint8Array(_BUF, 234652),  // 0x655504
  DAT_00655506: new Uint8Array(_BUF, 234654),  // 0x655506
  DAT_00655508: new Uint8Array(_BUF, 234656),  // 0x655508
  DAT_0065550a: new Uint8Array(_BUF, 234658),  // 0x65550a
  DAT_0065550c: new Uint8Array(_BUF, 234660),  // 0x65550c
  DAT_0065550e: new Uint8Array(_BUF, 234662),  // 0x65550e
  DAT_00655aea: new Uint8Array(_BUF, 236162),  // 0x655aea
  DAT_00655af8: new Uint8Array(_BUF, 236176),  // 0x655af8
  DAT_00655b03: new Uint8Array(_BUF, 236187),  // 0x655b03
  DAT_00655b06: new Uint8Array(_BUF, 236190),  // 0x655b06
  DAT_00655b1e: new Uint8Array(_BUF, 236214),  // 0x655b1e
  DAT_00655b82: new Uint8Array(_BUF, 236314),  // 0x655b82
  DAT_00655b98: new Uint8Array(_BUF, 236336),  // 0x655b98
  DAT_00655bcb: new Uint8Array(_BUF, 236387),  // 0x655bcb
  DAT_00655bce: new Uint8Array(_BUF, 236390),  // 0x655bce
  DAT_00655be6: new Uint8Array(_BUF, 236414),  // 0x655be6
  DAT_00655c22: new Uint8Array(_BUF, 236474),  // 0x655c22
  DAT_00655c2a: new Uint8Array(_BUF, 236482),  // 0x655c2a
  DAT_00655c38: new Uint8Array(_BUF, 236496),  // 0x655c38
  DAT_006560f0: new Uint8Array(_BUF, 237704),  // 0x6560f0
  DAT_006560f2: new Uint8Array(_BUF, 237706),  // 0x6560f2
  DAT_006560f4: new Uint8Array(_BUF, 237708),  // 0x6560f4
  DAT_006560f6: new Uint8Array(_BUF, 237710),  // 0x6560f6
  DAT_006560f7: new Uint8Array(_BUF, 237711),  // 0x6560f7
  DAT_006560f8: new Uint8Array(_BUF, 237712),  // 0x6560f8
  DAT_006560f9: new Uint8Array(_BUF, 237713),  // 0x6560f9
  DAT_006560fa: new Uint8Array(_BUF, 237714),  // 0x6560fa
  DAT_006560fb: new Uint8Array(_BUF, 237715),  // 0x6560fb
  DAT_006560fc: new Uint8Array(_BUF, 237716),  // 0x6560fc
  DAT_006560fd: new Uint8Array(_BUF, 237717),  // 0x6560fd
  DAT_006560fe: new Uint8Array(_BUF, 237718),  // 0x6560fe
  DAT_006560ff: new Uint8Array(_BUF, 237719),  // 0x6560ff
  DAT_00656100: new Uint8Array(_BUF, 237720),  // 0x656100
  DAT_00656102: new Uint8Array(_BUF, 237722),  // 0x656102
  DAT_00656104: new Uint8Array(_BUF, 237724),  // 0x656104
  DAT_00656106: new Uint8Array(_BUF, 237726),  // 0x656106
  DAT_00656108: new Uint8Array(_BUF, 237728),  // 0x656108
  DAT_0065610a: new Uint8Array(_BUF, 237730),  // 0x65610a
  DAT_00666130: new Uint8Array(_BUF, 303304),  // 0x666130
  DAT_00666132: new Uint8Array(_BUF, 303306),  // 0x666132
  DAT_00666134: new Uint8Array(_BUF, 303308),  // 0x666134
  DAT_00666137: new Uint8Array(_BUF, 303311),  // 0x666137
  DAT_0066664a: new Uint8Array(_BUF, 304610),  // 0x66664a
  DAT_0066be80: new Uint8Array(_BUF, 327192),  // 0x66be80
  DAT_0066be90: new Uint8Array(_BUF, 327208),  // 0x66be90
  DAT_0066c720: new Uint8Array(_BUF, 329400),  // 0x66c720
  DAT_0066c8cc: new Uint8Array(_BUF, 329828),  // 0x66c8cc
  DAT_0066c8d0: new Uint8Array(_BUF, 329832),  // 0x66c8d0
  DAT_0066c988: new Uint8Array(_BUF, 330016),  // 0x66c988
  DAT_0066ca84: new Uint8Array(_BUF, 330268),  // 0x66ca84
  DAT_0066ca86: new Uint8Array(_BUF, 330270),  // 0x66ca86
  DAT_0066ca90: new Uint8Array(_BUF, 330280),  // 0x66ca90
  DAT_0066ca94: new Uint8Array(_BUF, 330284),  // 0x66ca94
  DAT_0066cab0: new Uint8Array(_BUF, 330312),  // 0x66cab0
  DAT_0066cab4: new Uint8Array(_BUF, 330316),  // 0x66cab4
  DAT_0066cabc: new Uint8Array(_BUF, 330324),  // 0x66cabc
  DAT_0066cac0: new Uint8Array(_BUF, 330328),  // 0x66cac0
  DAT_0066cacc: new Uint8Array(_BUF, 330340),  // 0x66cacc
  DAT_0066cb00: new Uint8Array(_BUF, 330392),  // 0x66cb00
  DAT_0066ed98: new Uint8Array(_BUF, 339248),  // 0x66ed98
  DAT_0066fd98: new Uint8Array(_BUF, 343344),  // 0x66fd98
  DAT_00670da0: new Uint8Array(_BUF, 347448),  // 0x670da0
  DAT_00671da0: new Uint8Array(_BUF, 351544),  // 0x671da0
  DAT_00673a78: new Uint8Array(_BUF, 358928),  // 0x673a78
  DAT_00673a98: new Uint8Array(_BUF, 358960),  // 0x673a98
  DAT_00673ab8: new Uint8Array(_BUF, 358992),  // 0x673ab8
  DAT_00673ad8: new Uint8Array(_BUF, 359024),  // 0x673ad8
  DAT_00673af8: new Uint8Array(_BUF, 359056),  // 0x673af8
  DAT_00673afc: new Uint8Array(_BUF, 359060),  // 0x673afc
  DAT_00673b30: new Uint8Array(_BUF, 359112),  // 0x673b30
  DAT_00673d18: new Uint8Array(_BUF, 359600),  // 0x673d18
  DAT_00673d38: new Uint8Array(_BUF, 359632),  // 0x673d38
  DAT_00673d70: new Uint8Array(_BUF, 359688),  // 0x673d70
  DAT_00673fc8: new Uint8Array(_BUF, 360288),  // 0x673fc8
  DAT_006763c8: new Uint8Array(_BUF, 369504),  // 0x6763c8
  DAT_0067963f: new Uint8Array(_BUF, 382423),  // 0x67963f
  DAT_0067a410: new Uint8Array(_BUF, 385960),  // 0x67a410
  DAT_0067a414: new Uint8Array(_BUF, 385964),  // 0x67a414
  DAT_0067a41c: new Uint8Array(_BUF, 385972),  // 0x67a41c
  DAT_0067a420: new Uint8Array(_BUF, 385976),  // 0x67a420
  DAT_0067a424: new Uint8Array(_BUF, 385980),  // 0x67a424
  DAT_0067a98c: new Uint8Array(_BUF, 387364),  // 0x67a98c
  DAT_0067ab90: new Uint8Array(_BUF, 387880),  // 0x67ab90
  DAT_00682ba8: new Uint8Array(_BUF, 420672),  // 0x682ba8
  DAT_00684bac: new Uint8Array(_BUF, 428868),  // 0x684bac
  DAT_0068ae90: new Uint8Array(_BUF, 454184),  // 0x68ae90
  DAT_0068aee8: new Uint8Array(_BUF, 454272),  // 0x68aee8
  DAT_0068af08: new Uint8Array(_BUF, 454304),  // 0x68af08
  DAT_006a1880: new Uint8Array(_BUF, 546840),  // 0x6a1880
  DAT_006a1884: new Uint8Array(_BUF, 546844),  // 0x6a1884
  DAT_006a1888: new Uint8Array(_BUF, 546848),  // 0x6a1888
  DAT_006a188c: new Uint8Array(_BUF, 546852),  // 0x6a188c
  DAT_006a1ba6: new Uint8Array(_BUF, 547646),  // 0x6a1ba6
  DAT_006a1ce1: new Uint8Array(_BUF, 547961),  // 0x6a1ce1
  DAT_006a1d78: new Uint8Array(_BUF, 548112),  // 0x6a1d78
  DAT_006a1d9f: new Uint8Array(_BUF, 548151),  // 0x6a1d9f
  DAT_006a1daf: new Uint8Array(_BUF, 548167),  // 0x6a1daf
  DAT_006a2a00: new Uint8Array(_BUF, 551320),  // 0x6a2a00
  DAT_006a2d28: new Uint8Array(_BUF, 552128),  // 0x6a2d28
  DAT_006a2d2c: new Uint8Array(_BUF, 552132),  // 0x6a2d2c
  DAT_006a2d30: new Uint8Array(_BUF, 552136),  // 0x6a2d30
  DAT_006a2d34: new Uint8Array(_BUF, 552140),  // 0x6a2d34
  DAT_006a2d38: new Uint8Array(_BUF, 552144),  // 0x6a2d38
  DAT_006a2d3c: new Uint8Array(_BUF, 552148),  // 0x6a2d3c
  DAT_006a2d40: new Uint8Array(_BUF, 552152),  // 0x6a2d40
  DAT_006a2d44: new Uint8Array(_BUF, 552156),  // 0x6a2d44
  DAT_006a2d48: new Uint8Array(_BUF, 552160),  // 0x6a2d48
  DAT_006a2d4c: new Uint8Array(_BUF, 552164),  // 0x6a2d4c
  DAT_006a2d50: new Uint8Array(_BUF, 552168),  // 0x6a2d50
  DAT_006a2d54: new Uint8Array(_BUF, 552172),  // 0x6a2d54
  DAT_006a2d58: new Uint8Array(_BUF, 552176),  // 0x6a2d58
  DAT_006a2d59: new Uint8Array(_BUF, 552177),  // 0x6a2d59
  DAT_006a2d5c: new Uint8Array(_BUF, 552180),  // 0x6a2d5c
  DAT_006a2d80: new Uint8Array(_BUF, 552216),  // 0x6a2d80
  DAT_006a4f88: new Uint8Array(_BUF, 560928),  // 0x6a4f88
  DAT_006a5b10: new Uint8Array(_BUF, 563880),  // 0x6a5b10
  DAT_006a6530: new Uint8Array(_BUF, 566472),  // 0x6a6530
  DAT_006a6550: new Uint8Array(_BUF, 566504),  // 0x6a6550
  DAT_006a6590: new Uint8Array(_BUF, 566568),  // 0x6a6590
  DAT_006a659c: new Uint8Array(_BUF, 566580),  // 0x6a659c
  DAT_006a65a8: new Uint8Array(_BUF, 566592),  // 0x6a65a8
  DAT_006a65b8: new Uint8Array(_BUF, 566608),  // 0x6a65b8
  DAT_006a65c8: new Uint8Array(_BUF, 566624),  // 0x6a65c8
  DAT_006a65cc: new Uint8Array(_BUF, 566628),  // 0x6a65cc
  DAT_006a65f0: new Uint8Array(_BUF, 566664),  // 0x6a65f0
  DAT_006a6620: new Uint8Array(_BUF, 566712),  // 0x6a6620
  DAT_006a6628: new Uint8Array(_BUF, 566720),  // 0x6a6628
  DAT_006a6794: new Uint8Array(_BUF, 567084),  // 0x6a6794
  DAT_006a6924: new Uint8Array(_BUF, 567484),  // 0x6a6924
  DAT_006a6ab4: new Uint8Array(_BUF, 567884),  // 0x6a6ab4
  DAT_006a74bc: new Uint8Array(_BUF, 570452),  // 0x6a74bc
  DAT_006ab144: new Uint8Array(_BUF, 585948),  // 0x6ab144
  DAT_006ab148: new Uint8Array(_BUF, 585952),  // 0x6ab148
  DAT_006ab5c0: new Uint8Array(_BUF, 587096),  // 0x6ab5c0
  DAT_006aca14: new Uint8Array(_BUF, 592300),  // 0x6aca14
  DAT_006acb58: new Uint8Array(_BUF, 592624),  // 0x6acb58
  DAT_006acbd0: new Uint8Array(_BUF, 592744),  // 0x6acbd0
  DAT_006acd38: new Uint8Array(_BUF, 593104),  // 0x6acd38
  DAT_006ad108: new Uint8Array(_BUF, 594080),  // 0x6ad108
  DAT_006ad10c: new Uint8Array(_BUF, 594084),  // 0x6ad10c
  DAT_006ad17c: new Uint8Array(_BUF, 594196),  // 0x6ad17c
  DAT_006ad30c: new Uint8Array(_BUF, 594596),  // 0x6ad30c
  DAT_006ad354: new Uint8Array(_BUF, 594668),  // 0x6ad354
  DAT_006ad358: new Uint8Array(_BUF, 594672),  // 0x6ad358
  DAT_006ad359: new Uint8Array(_BUF, 594673),  // 0x6ad359
  DAT_006ad35c: new Uint8Array(_BUF, 594676),  // 0x6ad35c
  DAT_006ad558: new Uint8Array(_BUF, 595184),  // 0x6ad558
  DAT_006ad644: new Uint8Array(_BUF, 595420),  // 0x6ad644
  DAT_006ad678: new Uint8Array(_BUF, 595472),  // 0x6ad678
  DAT_006ad920: new Uint8Array(_BUF, 596152),  // 0x6ad920
  DAT_006ad924: new Uint8Array(_BUF, 596156),  // 0x6ad924
  DAT_006ad928: new Uint8Array(_BUF, 596160),  // 0x6ad928
  DAT_006ad92c: new Uint8Array(_BUF, 596164),  // 0x6ad92c
  DAT_006ad930: new Uint8Array(_BUF, 596168),  // 0x6ad930
  DAT_006ad934: new Uint8Array(_BUF, 596172),  // 0x6ad934
  DAT_006af220: new Uint8Array(_BUF, 602552),  // 0x6af220
  DAT_006af240: new Uint8Array(_BUF, 602584),  // 0x6af240
  DAT_006af260: new Uint8Array(_BUF, 602616),  // 0x6af260
  DAT_006af280: new Uint8Array(_BUF, 602648),  // 0x6af280
  DAT_006af2a0: new Uint8Array(_BUF, 602680),  // 0x6af2a0
  DAT_006af2a2: new Uint8Array(_BUF, 602682),  // 0x6af2a2
  DAT_006af2a4: new Uint8Array(_BUF, 602684),  // 0x6af2a4
  DAT_006af2a6: new Uint8Array(_BUF, 602686),  // 0x6af2a6
  DAT_006af2a8: new Uint8Array(_BUF, 602688),  // 0x6af2a8
  DAT_006c3168: new Uint8Array(_BUF, 684288),  // 0x6c3168
  DAT_006c3188: new Uint8Array(_BUF, 684320),  // 0x6c3188
  DAT_006c8fc0: new Uint8Array(_BUF, 708440),  // 0x6c8fc0
  DAT_006c8fe0: new Uint8Array(_BUF, 708472),  // 0x6c8fe0
  DAT_006cec84: new Uint8Array(_BUF, 732188),  // 0x6cec84
  DAT_006cec98: new Uint8Array(_BUF, 732208),  // 0x6cec98
  DAT_006ced20: new Uint8Array(_BUF, 732344),  // 0x6ced20
  DAT_006ced4c: new Uint8Array(_BUF, 732388),  // 0x6ced4c
  DAT_006ced60: new Uint8Array(_BUF, 732408),  // 0x6ced60
  DAT_006d1168: new Uint8Array(_BUF, 741632),  // 0x6d1168
  DAT_006d1188: new Uint8Array(_BUF, 741664),  // 0x6d1188
  DAT_006d1190: new Uint8Array(_BUF, 741672),  // 0x6d1190
  DAT_006d1da0: new Uint8Array(_BUF, 744760),  // 0x6d1da0
  DAT_006d1db8: new Uint8Array(_BUF, 744784),  // 0x6d1db8
  DAT_006d1dbc: new Uint8Array(_BUF, 744788),  // 0x6d1dbc
  DAT_006d4700: new Uint8Array(_BUF, 755352),  // 0x6d4700
  DAT_006d4704: new Uint8Array(_BUF, 755356),  // 0x6d4704
  DAT_006d4708: new Uint8Array(_BUF, 755360),  // 0x6d4708
  DAT_006d470c: new Uint8Array(_BUF, 755364),  // 0x6d470c
  DAT_006e47c8: new Uint8Array(_BUF, 821088),  // 0x6e47c8
  DAT_006e4f60: new Uint8Array(_BUF, 823032),  // 0x6e4f60
  DAT_006e4f64: new Uint8Array(_BUF, 823036),  // 0x6e4f64
  DAT_006e5478: new Uint8Array(_BUF, 824336),  // 0x6e5478
  DAT_006e54a4: new Uint8Array(_BUF, 824380),  // 0x6e54a4
  DAT_006e5694: new Uint8Array(_BUF, 824876),  // 0x6e5694
  DAT_006e69f0: new Uint8Array(_BUF, 829832),  // 0x6e69f0

  // ═══ Scalar globals ═══
  DAT_0061c744: 0,
  DAT_0061cce0: 0,
  DAT_0061ce58: 0,
  DAT_0061d204: 0,
  DAT_0061d2ac: 0,
  DAT_0061d2b4: 0,
  DAT_0061d790: 0,
  DAT_0061d7b0: 0,
  DAT_0061dc40: 0,
  DAT_0061e2fc: 0,
  DAT_0061e724: 0,
  DAT_00624000: 0,
  DAT_006245a8: 0,
  DAT_006246ac: 0,
  DAT_006248bc: 0,
  DAT_006249c0: 0,
  DAT_00624bc8: 0,
  DAT_00624ccc: 0,
  DAT_00624dd0: 0,
  DAT_00624ee0: 0,
  DAT_00624ee8: 0,
  DAT_00624eec: 0,
  DAT_00624ef0: 0,
  DAT_00624ef4: 0,
  DAT_00624ef8: 0,
  DAT_00624efc: 0,
  DAT_00624f00: 0,
  DAT_00624f04: 0,
  DAT_00624f1c: 0,
  DAT_00624f20: 0,
  DAT_00624f30: 0,
  DAT_00624f54: 0,
  DAT_00624f58: 0,
  DAT_00624f5c: 0,
  DAT_00624f60: 0,
  DAT_00624f68: 0,
  DAT_00625090: 0,
  DAT_006250d8: 0,
  DAT_00625114: 0,
  DAT_00625118: 0,
  DAT_00625130: 0,
  DAT_00625134: 0,
  DAT_00625138: 0,
  DAT_0062513c: 0,
  DAT_00625140: 0,
  DAT_00625144: 0,
  DAT_00625148: 0,
  DAT_00625158: 0,
  DAT_0062515c: 0,
  DAT_006251a8: 0,
  DAT_006251ac: 0,
  DAT_006251b0: 0,
  DAT_006251b4: 0,
  DAT_006251b8: 0,
  DAT_006251c4: 0,
  DAT_00625210: 0,
  DAT_00625220: 0,
  DAT_0062523c: 0,
  DAT_0062524c: 0,
  DAT_00625250: 0,
  DAT_00625254: 0,
  DAT_006252c0: 0,
  DAT_006252c4: 0,
  DAT_006252c8: 0,
  DAT_00625354: 0,
  DAT_006253e0: 0,
  DAT_006253e4: 0,
  DAT_006253e8: 0,
  DAT_006253f8: 0,
  DAT_006253fc: 0,
  DAT_00625400: 0,
  DAT_00625404: 0,
  DAT_00625408: 0,
  DAT_0062540c: 0,
  DAT_00625470: 0,
  DAT_006254a0: 0,
  DAT_0062551c: 0,
  DAT_00625548: 0,
  DAT_0062554c: 0,
  DAT_0062559c: 0,
  DAT_006255a4: 0,
  DAT_006255a8: 0,
  DAT_00625610: 0,
  DAT_00625634: 0,
  DAT_00625638: 0,
  DAT_00625644: 0,
  DAT_0062564c: 0,
  DAT_00625668: 0,
  DAT_0062566c: 0,
  DAT_00625670: 0,
  DAT_00625674: 0,
  DAT_00625800: 0,
  DAT_00625858: 0,
  DAT_00625a04: 0,
  DAT_00625d14: 0,
  DAT_00625d18: 0,
  DAT_00625d1c: 0,
  DAT_00625d20: 0,
  DAT_00625d24: 0,
  DAT_00625d28: 0,
  DAT_00625d2c: 0,
  DAT_00625d30: 0,
  DAT_00625d34: 0,
  DAT_00625d38: 0,
  DAT_00625d3c: 0,
  DAT_00625d40: 0,
  DAT_00625d44: 0,
  DAT_00625d48: 0,
  DAT_00625d4c: 0,
  DAT_00625d50: 0,
  DAT_00625d54: 0,
  DAT_00625d58: 0,
  DAT_00625d5c: 0,
  DAT_00625d60: 0,
  DAT_00625d64: 0,
  DAT_00625d68: 0,
  DAT_00625d6c: 0,
  DAT_00625d70: 0,
  DAT_00625e50: 0,
  DAT_00625e54: 0,
  DAT_00625e58: 0,
  DAT_00625e60: 0,
  DAT_00625e64: 0,
  DAT_00625e78: 0,
  DAT_00625e7c: 0,
  DAT_00625e80: 0,
  DAT_00625e84: 0,
  DAT_00625e90: 0,
  DAT_00625ec4: 0,
  DAT_00625ec8: 0,
  DAT_00625ecc: 0,
  DAT_00625ed0: 0,
  DAT_00625efc: 0,
  DAT_00625f1c: 0,
  DAT_00625f20: 0,
  DAT_00625f24: 0,
  DAT_00625f28: 0,
  DAT_00625f2c: 0,
  DAT_00626000: 0,
  DAT_00626004: 0,
  DAT_00626030: 0,
  DAT_00626040: 0,
  DAT_00626044: 0,
  DAT_00626048: 0,
  DAT_0062604c: 0,
  DAT_00626054: 0,
  DAT_00626058: 0,
  DAT_00626064: 0,
  DAT_0062606c: 0,
  DAT_00626070: 0,
  DAT_00626074: 0,
  DAT_00626078: 0,
  DAT_0062607c: 0,
  DAT_00626080: 0,
  DAT_00626084: 0,
  DAT_00626088: 0,
  DAT_0062608c: 0,
  DAT_00626090: 0,
  DAT_00626098: 0,
  DAT_0062609c: 0,
  DAT_006260a4: 0,
  DAT_006260b0: 0,
  DAT_006260b4: 0,
  DAT_00626110: 0,
  DAT_00626114: 0,
  DAT_00626118: 0,
  DAT_00626120: 0,
  DAT_00626134: 0,
  DAT_00626194: 0,
  DAT_00626198: 0,
  DAT_006261a0: 0,
  DAT_00626238: 0,
  DAT_0062623c: 0,
  DAT_00626248: 0,
  DAT_0062624c: 0,
  DAT_00626258: 0,
  DAT_00626260: 0,
  DAT_006264ec: 0,
  DAT_006265b4: 0,
  DAT_0062660c: 0,
  DAT_00626610: 0,
  DAT_0062665c: 0,
  DAT_0062681c: 0,
  DAT_00626820: 0,
  DAT_0062682c: 0,
  DAT_0062683c: 0,
  DAT_00626840: 0,
  DAT_00626844: 0,
  DAT_00626850: 0,
  DAT_00626854: 0,
  DAT_006268f4: 0,
  DAT_0062691c: 0,
  DAT_00626960: 0,
  DAT_006269e4: 0,
  DAT_00626a00: 0,
  DAT_00626a04: 0,
  DAT_00626a10: 0,
  DAT_00626a14: 0,
  DAT_00626a1c: 0,
  DAT_00626a20: 0,
  DAT_00626a24: 0,
  DAT_00626a2c: 0,
  DAT_00626a30: 0,
  DAT_00626a34: 0,
  DAT_00626a38: 0,
  DAT_00626a48: 0,
  DAT_00626a4c: 0,
  DAT_00626b5c: 0,
  DAT_00626b60: 0,
  DAT_00627008: 0,
  DAT_00627220: 0,
  DAT_00627228: 0,
  DAT_00627664: 0,
  DAT_00627668: 0,
  DAT_0062766c: 0,
  DAT_00627670: 0,
  DAT_00627879: 0,
  DAT_00627c14: 0,
  DAT_00627fd8: 0,
  DAT_00627fdc: 0,
  DAT_00628044: 0,
  DAT_00628048: 0,
  DAT_0062804c: 0,
  DAT_00628054: 0,
  DAT_00628058: 0,
  DAT_0062805c: 0,
  DAT_00628060: 0,
  DAT_00628064: 0,
  DAT_00628068: 0,
  DAT_0062832c: 0,
  DAT_00628330: 0,
  DAT_0062840c: 0,
  DAT_00628410: 0,
  DAT_00628414: 0,
  DAT_00628418: 0,
  DAT_0062841c: 0,
  DAT_00628424: 0,
  DAT_00628468: 0,
  DAT_0062a78c: 0,
  DAT_0062af0c: 0,
  DAT_0062af10: 0,
  DAT_0062af14: 0,
  DAT_0062af44: 0,
  DAT_0062af48: 0,
  DAT_0062b420: 0,
  DAT_0062b424: 0,
  DAT_0062b428: 0,
  DAT_0062b42c: 0,
  DAT_0062b438: 0,
  DAT_0062b640: 0,
  DAT_0062b674: 0,
  DAT_0062b678: 0,
  DAT_0062b748: 0,
  DAT_0062b74c: 0,
  DAT_0062b804: 0,
  DAT_0062b824: 0,
  DAT_0062b828: 0,
  DAT_0062b850: 0,
  DAT_0062b864: 0,
  DAT_0062b8d0: 0,
  DAT_0062b8d4: 0,
  DAT_0062b900: 0,
  DAT_0062b924: 0,
  DAT_0062b928: 0,
  DAT_0062b944: 0,
  DAT_0062b970: 0,
  DAT_0062b974: 0,
  DAT_0062ba38: 0,
  DAT_0062ba40: 0,
  DAT_0062ba48: 0,
  DAT_0062ba50: 0,
  DAT_0062ba58: 0,
  DAT_0062ba7c: 0,
  DAT_0062bad4: 0,
  DAT_0062bad8: 0,
  DAT_0062bae0: 0,
  DAT_0062bae4: 0,
  DAT_0062baf8: 0,
  DAT_0062bb00: 0,
  DAT_0062bb08: 0,
  DAT_0062bb0c: 0,
  DAT_0062bb10: 0,
  DAT_0062bb14: 0,
  DAT_0062bb18: 0,
  DAT_0062bb1c: 0,
  DAT_0062bb20: 0,
  DAT_0062bb24: 0,
  DAT_0062bb28: 0,
  DAT_0062bb2c: 0,
  DAT_0062bb30: 0,
  DAT_0062bb34: 0,
  DAT_0062bb60: 0,
  DAT_0062bb64: 0,
  DAT_0062bb68: 0,
  DAT_0062bb6c: 0,
  DAT_0062bcb0: 0,
  DAT_0062bcd8: 0,
  DAT_0062bcec: 0,
  DAT_0062c488: 0,
  DAT_0062c5b0: 0,
  DAT_0062c5b4: 0,
  DAT_0062c5b8: 0,
  DAT_0062c5bc: 0,
  DAT_0062c5c0: 0,
  DAT_0062c608: 0,
  DAT_0062c60c: 0,
  DAT_0062c610: 0,
  DAT_0062c614: 0,
  DAT_0062c650: 0,
  DAT_0062c944: 0,
  DAT_0062c950: 0,
  DAT_0062c968: 0,
  DAT_0062c96c: 0,
  DAT_0062c970: 0,
  DAT_0062c974: 0,
  DAT_0062c97c: 0,
  DAT_0062c980: 0,
  DAT_0062c998: 0,
  DAT_0062c99c: 0,
  DAT_0062c9a0: 0,
  DAT_0062ca34: 0,
  DAT_0062ca38: 0,
  DAT_0062ca3c: 0,
  DAT_0062ca40: 0,
  DAT_0062ca44: 0,
  DAT_0062ca5c: 0,
  DAT_0062cb7c: 0,
  DAT_0062cb80: 0,
  DAT_0062cb84: 0,
  DAT_0062cb88: 0,
  DAT_0062cb8c: 0,
  DAT_0062cb90: 0,
  DAT_0062cba0: 0,
  DAT_0062cba8: 0,
  DAT_0062cbb0: 0,
  DAT_0062cbc8: 0,
  DAT_0062cbcc: 0,
  DAT_0062cc48: 0,
  DAT_0062cc64: 0,
  DAT_0062cc74: 0,
  DAT_0062cc90: 0,
  DAT_0062ccc0: 0,
  DAT_0062ccc4: 0,
  DAT_0062cd20: 0,
  DAT_0062cd24: 0,
  DAT_0062cd28: 0,
  DAT_0062cd2c: 0,
  DAT_0062cd40: 0,
  DAT_0062cd44: 0,
  DAT_0062cd48: 0,
  DAT_0062cd4c: 0,
  DAT_0062cd50: 0,
  DAT_0062cd54: 0,
  DAT_0062cd58: 0,
  DAT_0062cd5c: 0,
  DAT_0062cd90: 0,
  DAT_0062cd94: 0,
  DAT_0062cd98: 0,
  DAT_0062cd9c: 0,
  DAT_0062cda0: 0,
  DAT_0062cda4: 0,
  DAT_0062cda8: 0,
  DAT_0062cdac: 0,
  DAT_0062cdb0: 0,
  DAT_0062cdb4: 0,
  DAT_0062cdb8: 0,
  DAT_0062cdbc: 0,
  DAT_0062cdc0: 0,
  DAT_0062cdc4: 0,
  DAT_0062cdc8: 0,
  DAT_0062ce6c: 0,
  DAT_0062ce74: 0,
  DAT_0062cee4: 0,
  DAT_0062cee8: 0,
  DAT_0062ceec: 0,
  DAT_0062cef0: 0,
  DAT_0062d03c: 0,
  DAT_0062d040: 0,
  DAT_0062d044: 0,
  DAT_0062d048: 0,
  DAT_0062d04c: 0,
  DAT_0062d050: 0,
  DAT_0062d064: 0,
  DAT_0062d068: 0,
  DAT_0062d06c: 0,
  DAT_0062d070: 0,
  DAT_0062d074: 0,
  DAT_0062d078: 0,
  DAT_0062d07c: 0,
  DAT_0062d080: 0,
  DAT_0062d084: 0,
  DAT_0062d088: 0,
  DAT_0062d08c: 0,
  DAT_0062d090: 0,
  DAT_0062d094: 0,
  DAT_0062d098: 0,
  DAT_0062d0a4: 0,
  DAT_0062d0a8: 0,
  DAT_0062d0ac: 0,
  DAT_0062d0b0: 0,
  DAT_0062d0b8: 0,
  DAT_0062d0bc: 0,
  DAT_0062d0c0: 0,
  DAT_0062d7e0: 0,
  DAT_0062d7e4: 0,
  DAT_0062d7e8: 0,
  DAT_0062d7ec: 0,
  DAT_0062d7f8: 0,
  DAT_0062d7fc: 0,
  DAT_0062d858: 0,
  DAT_0062d85c: 0,
  DAT_0062d860: 0,
  DAT_0062d864: 0,
  DAT_0062d868: 0,
  DAT_0062d86c: 0,
  DAT_0062d8b4: 0,
  DAT_0062d920: 0,
  DAT_0062d9e8: 0,
  DAT_0062d9ec: 0,
  DAT_0062d9f0: 0,
  DAT_0062d9f4: 0,
  DAT_0062d9f8: 0,
  DAT_0062d9fc: 0,
  DAT_0062da00: 0,
  DAT_0062da04: 0,
  DAT_0062da08: 0,
  DAT_0062dacc: 0,
  DAT_0062dad4: 0,
  DAT_0062db00: 0,
  DAT_0062db88: 0,
  DAT_0062db8c: 0,
  DAT_0062dba4: 0,
  DAT_0062dba8: 0,
  DAT_0062dbd8: 0,
  DAT_0062dbdc: 0,
  DAT_0062dcf4: 0,
  DAT_0062dd5c: 0,
  DAT_0062de78: 0,
  DAT_0062ded0: 0,
  DAT_0062e014: 0,
  DAT_0062e018: 0,
  DAT_0062e01c: 0,
  DAT_0062e020: 0,
  DAT_0062e024: 0,
  DAT_0062e030: 0,
  DAT_0062e03c: 0,
  DAT_0062e040: 0,
  DAT_0062e078: 0,
  DAT_0062e088: 0,
  DAT_0062e08c: 0,
  DAT_0062e0a8: 0,
  DAT_0062e0e4: 0,
  DAT_0062e114: 0,
  DAT_0062e124: 0,
  DAT_0062e134: 0,
  DAT_0062e144: 0,
  DAT_0062e148: 0,
  DAT_0062e14c: 0,
  DAT_0062e150: 0,
  DAT_0062e198: 0,
  DAT_0062e1a8: 0,
  DAT_0062e1ac: 0,
  DAT_0062e1d4: 0,
  DAT_0062e1d8: 0,
  DAT_0062e1dc: 0,
  DAT_0062e2dc: 0,
  DAT_0062e2e0: 0,
  DAT_0062e2ec: 0,
  DAT_0062e2f0: 0,
  DAT_0062e2f4: 0,
  DAT_0062e2f8: 0,
  DAT_0062e304: 0,
  DAT_0062e308: 0,
  DAT_0062e30c: 0,
  DAT_0062e310: 0,
  DAT_0062e314: 0,
  DAT_0062e318: 0,
  DAT_0062e31c: 0,
  DAT_0062e320: 0,
  DAT_0062e34c: 0,
  DAT_0062e3a0: 0,
  DAT_0062e3a4: 0,
  DAT_0062e3a8: 0,
  DAT_0062e3ac: 0,
  DAT_0062e3b8: 0,
  DAT_0062e3bc: 0,
  DAT_0062e3f8: 0,
  DAT_0062e3fc: 0,
  DAT_0062e400: 0,
  DAT_0062e40c: 0,
  DAT_0062e410: 0,
  DAT_0062e414: 0,
  DAT_0062e478: 0,
  DAT_0062e494: 0,
  DAT_0062e4b0: 0,
  DAT_0062e4b4: 0,
  DAT_0062e508: 0,
  DAT_0062e60c: 0,
  DAT_0062e610: 0,
  DAT_0062e614: 0,
  DAT_0062e618: 0,
  DAT_0062e61c: 0,
  DAT_0062e854: 0,
  DAT_0062e8ac: 0,
  DAT_0062e8b4: 0,
  DAT_0062e8b8: 0,
  DAT_0062e8c0: 0,
  DAT_0062e8c4: 0,
  DAT_0062e8cc: 0,
  DAT_0062e8d0: 0,
  DAT_0062e8d8: 0,
  DAT_0062e8dc: 0,
  DAT_0062e8e4: 0,
  DAT_0062e8f4: 0,
  DAT_0062e8fc: 0,
  DAT_0062e900: 0,
  DAT_0062e908: 0,
  DAT_0062e910: 0,
  DAT_0062e918: 0,
  DAT_0062e91c: 0,
  DAT_0062e92c: 0,
  DAT_0062e930: 0,
  DAT_0062e934: 0,
  DAT_0062e938: 0,
  DAT_0062e93c: 0,
  DAT_0062e940: 0,
  DAT_0062e944: 0,
  DAT_0062e948: 0,
  DAT_0062e958: 0,
  DAT_0062e95c: 0,
  DAT_0062e960: 0,
  DAT_0062e964: 0,
  DAT_0062e968: 0,
  DAT_0062e9bc: 0,
  DAT_0062e9c0: 0,
  DAT_0062e9c4: 0,
  DAT_0062e9c8: 0,
  DAT_0062e9cc: 0,
  DAT_0062e9d0: 0,
  DAT_0062e9d4: 0,
  DAT_0062e9d8: 0,
  DAT_0062e9dc: 0,
  DAT_0062e9e0: 0,
  DAT_0062e9e4: 0,
  DAT_0062e9e8: 0,
  DAT_0062e9ec: 0,
  DAT_0062e9f0: 0,
  DAT_0062e9f4: 0,
  DAT_0062e9f8: 0,
  DAT_0062e9fc: 0,
  DAT_0062ea00: 0,
  DAT_0062ea5c: 0,
  DAT_0062eb30: 0,
  DAT_0062eb34: 0,
  DAT_0062eb88: 0,
  DAT_0062ed2c: 0,
  DAT_0062ed34: 0,
  DAT_0062ed44: 0,
  DAT_0062edf4: 0,
  DAT_0062edf8: 0,
  DAT_0062edfc: 0,
  DAT_0062ee00: 0,
  DAT_0062ee04: 0,
  DAT_0062ee08: 0,
  DAT_0062ee0c: 0,
  DAT_0062ee48: 0,
  DAT_0062f004: 0,
  DAT_0062f00c: 0,
  DAT_0062f010: 0,
  DAT_0062f018: 0,
  DAT_0062f01c: 0,
  DAT_0062f104: 0,
  DAT_0062f120: 0,
  DAT_0062f160: 0,
  DAT_0062f2c0: 0,
  DAT_0062f338: 0,
  DAT_0062fa84: 0,
  DAT_0062fd00: 0,
  DAT_0062fff8: 0,
  DAT_0062fffc: 0,
  DAT_00630004: 0,
  DAT_006302e4: 0,
  DAT_0063073c: 0,
  DAT_00630d18: 0,
  DAT_00630d1c: 0,
  DAT_00630d20: 0,
  DAT_00630d24: 0,
  DAT_00630d28: 0,
  DAT_00630d2c: 0,
  DAT_00630d30: 0,
  DAT_00630d34: 0,
  DAT_00630d68: 0,
  DAT_00630d90: 0,
  DAT_00630dd4: 0,
  DAT_00630dd8: 0,
  DAT_00630ec0: 0,
  DAT_00630ee0: 0,
  DAT_00630f28: 0,
  DAT_00630f2c: 0,
  DAT_00630f30: 0,
  DAT_00630f34: 0,
  DAT_00630f38: 0,
  DAT_00630f3c: 0,
  DAT_00630f40: 0,
  DAT_00630f44: 0,
  DAT_00631130: 0,
  DAT_00631134: 0,
  DAT_00631138: 0,
  DAT_0063113c: 0,
  DAT_00631320: 0,
  DAT_00631340: 0,
  DAT_00631a98: 0,
  DAT_00631a9c: 0,
  DAT_00631aac: 0,
  DAT_00631ab0: 0,
  DAT_00631ab4: 0,
  DAT_00631abc: 0,
  DAT_00631ad0: 0,
  DAT_00631ad4: 0,
  DAT_00631b08: 0,
  DAT_00631b0c: 0,
  DAT_00631b10: 0,
  DAT_00631b14: 0,
  DAT_00631b18: 0,
  DAT_00631b2c: 0,
  DAT_00631b3c: 0,
  DAT_00631b58: 0,
  DAT_00631b78: 0,
  DAT_00631b88: 0,
  DAT_00631b8c: 0,
  DAT_00631b90: 0,
  DAT_00631b94: 0,
  DAT_00631b98: 0,
  DAT_00631b9c: 0,
  DAT_00631ba8: 0,
  DAT_00631bac: 0,
  DAT_00631bb8: 0,
  DAT_00631bbc: 0,
  DAT_00631bc0: 0,
  DAT_00631bc4: 0,
  DAT_00631bc8: 0,
  DAT_00631bcc: 0,
  DAT_00631bd0: 0,
  DAT_00631bd4: 0,
  DAT_00631bd8: 0,
  DAT_00631bdc: 0,
  DAT_00631be0: 0,
  DAT_00631be4: 0,
  DAT_00631be8: 0,
  DAT_00631bec: 0,
  DAT_00631cd0: 0,
  DAT_00631cd4: 0,
  DAT_00631ce0: 0,
  DAT_00631cec: 0,
  DAT_00631cf0: 0,
  DAT_00631cfc: 0,
  DAT_00631d00: 0,
  DAT_00631d04: 0,
  DAT_00631d08: 0,
  DAT_00631d0c: 0,
  DAT_00631d10: 0,
  DAT_00631d14: 0,
  DAT_00631d20: 0,
  DAT_00631d70: 0,
  DAT_00631d8c: 0,
  DAT_00631da8: 0,
  DAT_00631dcc: 0,
  DAT_00631de8: 0,
  DAT_00631e04: 0,
  DAT_00631e28: 0,
  DAT_00631e38: 0,
  DAT_00631ed8: 0,
  DAT_00631edc: 0,
  DAT_00631ee4: 0,
  DAT_00631ee8: 0,
  DAT_00631eec: 0,
  DAT_00631ef0: 0,
  DAT_00631f24: 0,
  DAT_00631f74: 0,
  DAT_00631fc4: 0,
  DAT_006320b4: 0,
  DAT_006321f8: 0,
  DAT_0063223c: 0,
  DAT_00632268: 0,
  DAT_006322a0: 0,
  DAT_006322a4: 0,
  DAT_006322a8: 0,
  DAT_00632330: 0,
  DAT_00632334: 0,
  DAT_00632338: 0,
  DAT_00632428: 0,
  DAT_006324dc: 0,
  DAT_00632544: 0,
  DAT_00632558: 0,
  DAT_00632578: 0,
  DAT_0063258c: 0,
  DAT_006325d4: 0,
  DAT_00632638: 0,
  DAT_006326bc: 0,
  DAT_00632710: 0,
  DAT_0063275c: 0,
  DAT_00632760: 0,
  DAT_00632a1c: 0,
  DAT_00632a4c: 0,
  DAT_00632a5c: 0,
  DAT_00632be4: 0,
  DAT_00632cc8: 0,
  DAT_00632cd8: 0,
  DAT_00632ebc: 0,
  DAT_00632ee8: 0,
  DAT_00633168: 0,
  DAT_00633250: 0,
  DAT_00633280: 0,
  DAT_0063328c: 0,
  DAT_006332cc: 0,
  DAT_0063357c: 0,
  DAT_00633580: 0,
  DAT_00633584: 0,
  DAT_00633588: 0,
  DAT_0063358c: 0,
  DAT_00633590: 0,
  DAT_00633594: 0,
  DAT_00633598: 0,
  DAT_0063359c: 0,
  DAT_006335a0: 0,
  DAT_006335a4: 0,
  DAT_006335a8: 0,
  DAT_006335ac: 0,
  DAT_006335b0: 0,
  DAT_006335b4: 0,
  DAT_006335b8: 0,
  DAT_006335bc: 0,
  DAT_006335c0: 0,
  DAT_006335c4: 0,
  DAT_006335c8: 0,
  DAT_006335cc: 0,
  DAT_006335d0: 0,
  DAT_006335d4: 0,
  DAT_006335d8: 0,
  DAT_006335dc: 0,
  DAT_006335e0: 0,
  DAT_00633678: 0,
  DAT_0063367c: 0,
  DAT_00633684: 0,
  DAT_00633688: 0,
  DAT_0063368c: 0,
  DAT_00633690: 0,
  DAT_00633694: 0,
  DAT_006336cc: 0,
  DAT_006336d0: 0,
  DAT_006336ec: 0,
  DAT_006336fc: 0,
  DAT_00633754: 0,
  DAT_00633780: 0,
  DAT_00633784: 0,
  DAT_006338f4: 0,
  DAT_006338f8: 0,
  DAT_00633a74: 0,
  DAT_00633a78: 0,
  DAT_00633a80: 0,
  DAT_00633a84: 0,
  DAT_00633a88: 0,
  DAT_00633a90: 0,
  DAT_00633ac8: 0,
  DAT_00633c98: 0,
  DAT_00633cdc: 0,
  DAT_00633d6c: 0,
  DAT_00633df4: 0,
  DAT_00633df8: 0,
  DAT_00633dfc: 0,
  DAT_00633e00: 0,
  DAT_00633e04: 0,
  DAT_00633e08: 0,
  DAT_00633e0c: 0,
  DAT_00633e10: 0,
  DAT_00633e14: 0,
  DAT_00633e18: 0,
  DAT_00633e1c: 0,
  DAT_00633e20: 0,
  DAT_00633e24: 0,
  DAT_00633e28: 0,
  DAT_00633e2c: 0,
  DAT_00633e3c: 0,
  DAT_00633e40: 0,
  DAT_00633e44: 0,
  DAT_00633e48: 0,
  DAT_00633e4c: 0,
  DAT_00633e50: 0,
  DAT_00633e54: 0,
  DAT_00633e58: 0,
  DAT_00633e5c: 0,
  DAT_00633edc: 0,
  DAT_00634000: 0,
  DAT_00634004: 0,
  DAT_00634008: 0,
  DAT_0063400c: 0,
  DAT_006341f0: 0,
  DAT_006341f4: 0,
  DAT_0063427c: 0,
  DAT_00634280: 0,
  DAT_00634304: 0,
  DAT_00634308: 0,
  DAT_0063430c: 0,
  DAT_00634310: 0,
  DAT_00634440: 0,
  DAT_00634444: 0,
  DAT_0063465c: 0,
  DAT_006346d0: 0,
  DAT_00634718: 0,
  DAT_00634768: 0,
  DAT_00634770: 0,
  DAT_006347c0: 0,
  DAT_00634810: 0,
  DAT_00634814: 0,
  DAT_00634818: 0,
  DAT_0063481c: 0,
  DAT_00634820: 0,
  DAT_00634824: 0,
  DAT_00634840: 0,
  DAT_00634868: 0,
  DAT_0063486c: 0,
  DAT_00634894: 0,
  DAT_00634898: 0,
  DAT_006348d0: 0,
  DAT_006348d4: 0,
  DAT_00634930: 0,
  DAT_00634948: 0,
  DAT_0063494c: 0,
  DAT_00634950: 0,
  DAT_00634988: 0,
  DAT_006349a8: 0,
  DAT_006349ac: 0,
  DAT_006349b4: 0,
  DAT_00634ba4: 0,
  DAT_00634c9c: 0,
  DAT_00634ca0: 0,
  DAT_00634d38: 0,
  DAT_00634e50: 0,
  DAT_00634f70: 0,
  DAT_00634f7c: 0,
  DAT_00634f88: 0,
  DAT_00634f94: 0,
  DAT_00634fa0: 0,
  DAT_00634fc0: 0,
  DAT_00634fcc: 0,
  DAT_00634fd0: 0,
  DAT_00634fd4: 0,
  DAT_00634fd8: 0,
  DAT_00634fe0: 0,
  DAT_00634fe8: 0,
  DAT_00634ff0: 0,
  DAT_0063506c: 0,
  DAT_00635070: 0,
  DAT_00635094: 0,
  DAT_00635098: 0,
  DAT_00635108: 0,
  DAT_00635168: 0,
  DAT_006351c4: 0,
  DAT_00635220: 0,
  DAT_0063527c: 0,
  DAT_006352c4: 0,
  DAT_006356d0: 0,
  DAT_006356d4: 0,
  DAT_006356d8: 0,
  DAT_006359c0: 0,
  DAT_006359c4: 0,
  DAT_006359c8: 0,
  DAT_006359cc: 0,
  DAT_006359d0: 0,
  DAT_006359d4: 0,
  DAT_006359f4: 0,
  DAT_006359f8: 0,
  DAT_006359fc: 0,
  DAT_00635a00: 0,
  DAT_00635a04: 0,
  DAT_00635a08: 0,
  DAT_00635a0c: 0,
  DAT_00635a10: 0,
  DAT_00635a14: 0,
  DAT_00635a18: 0,
  DAT_00635a1c: 0,
  DAT_00635a20: 0,
  DAT_00635a24: 0,
  DAT_00635a28: 0,
  DAT_00635a2c: 0,
  DAT_00635a30: 0,
  DAT_00635a34: 0,
  DAT_00635a38: 0,
  DAT_00635a3c: 0,
  DAT_00635a40: 0,
  DAT_00635a44: 0,
  DAT_00635a9c: 0,
  DAT_00635aa0: 0,
  DAT_00635aa4: 0,
  DAT_00635b18: 0,
  DAT_00635b1c: 0,
  DAT_00635b70: 0,
  DAT_00635b84: 0,
  DAT_00635bb8: 0,
  DAT_00635bbc: 0,
  DAT_00635c64: 0,
  DAT_00635d94: 0,
  DAT_00635d98: 0,
  DAT_00635d9c: 0,
  DAT_00635da0: 0,
  DAT_00635da4: 0,
  DAT_00635da8: 0,
  DAT_00635de0: 0,
  DAT_00635e00: 0,
  DAT_00635e04: 0,
  DAT_00635e08: 0,
  DAT_00635e0c: 0,
  DAT_00635e10: 0,
  DAT_00635e14: 0,
  DAT_00635e18: 0,
  DAT_00635e28: 0,
  DAT_00635e2c: 0,
  DAT_00635e30: 0,
  DAT_00635e38: 0,
  DAT_00635e3c: 0,
  DAT_00635e40: 0,
  DAT_00635e44: 0,
  DAT_00635e48: 0,
  DAT_00635e4c: 0,
  DAT_00635e50: 0,
  DAT_00635e54: 0,
  DAT_00635e58: 0,
  DAT_00635e5c: 0,
  DAT_00635f08: 0,
  DAT_00635f0c: 0,
  DAT_00635f10: 0,
  DAT_00635f14: 0,
  DAT_00635f18: 0,
  DAT_00635f1c: 0,
  DAT_00635f20: 0,
  DAT_00635f24: 0,
  DAT_00635f28: 0,
  DAT_00635f2c: 0,
  DAT_00635f30: 0,
  DAT_00635f34: 0,
  DAT_00635f38: 0,
  DAT_00635f40: 0,
  DAT_00635fbc: 0,
  DAT_00635fe0: 0,
  DAT_00636058: 0,
  DAT_0063605c: 0,
  DAT_00636598: 0,
  DAT_006365c4: 0,
  DAT_006365c8: 0,
  DAT_006365cc: 0,
  DAT_006365d0: 0,
  DAT_006365d4: 0,
  DAT_006365d8: 0,
  DAT_006365dc: 0,
  DAT_006365e0: 0,
  DAT_006365e4: 0,
  DAT_006365e8: 0,
  DAT_006365ec: 0,
  DAT_006365f0: 0,
  DAT_006365f4: 0,
  DAT_006366a0: 0,
  DAT_006366a8: 0,
  DAT_006366ac: 0,
  DAT_006366b0: 0,
  DAT_006366b4: 0,
  DAT_006366b8: 0,
  DAT_006366bc: 0,
  DAT_006366c0: 0,
  DAT_006366cc: 0,
  DAT_006367dc: 0,
  DAT_00636838: 0,
  DAT_00636840: 0,
  DAT_006368a0: 0,
  DAT_006368d4: 0,
  DAT_006368dc: 0,
  DAT_00636c94: 0,
  DAT_00636e04: 0,
  DAT_006375ec: 0,
  DAT_00637758: 0,
  DAT_00637c9c: 0,
  DAT_00637ca0: 0,
  DAT_00637ca4: 0,
  DAT_00637d6c: 0,
  DAT_00637e30: 0,
  DAT_00637e44: 0,
  DAT_00637e58: 0,
  DAT_00637e78: 0,
  DAT_00637e7c: 0,
  DAT_00637e80: 0,
  DAT_00637e84: 0,
  DAT_00637e88: 0,
  DAT_00637e8c: 0,
  DAT_00637e90: 0,
  DAT_00637e94: 0,
  DAT_00637e98: 0,
  DAT_00637e9c: 0,
  DAT_00637ea0: 0,
  DAT_00637ea4: 0,
  DAT_00637ea8: 0,
  DAT_00637ef4: 0,
  DAT_00637ef8: 0,
  DAT_00637efc: 0,
  DAT_00637f00: 0,
  DAT_00637f01: 0,
  DAT_00637f02: 0,
  DAT_00637f03: 0,
  DAT_00637f04: 0,
  DAT_00637f05: 0,
  DAT_00637f06: 0,
  DAT_00637f07: 0,
  DAT_00637f08: 0,
  DAT_00637f0c: 0,
  DAT_00637f58: 0,
  DAT_00637f5c: 0,
  DAT_00637f80: 0,
  DAT_00637f98: 0,
  DAT_00637f9c: 0,
  DAT_00637fa0: 0,
  DAT_00637fa4: 0,
  DAT_00637fa8: 0,
  DAT_00637fac: 0,
  DAT_00638304: 0,
  DAT_00638308: 0,
  DAT_00638314: 0,
  DAT_00638318: 0,
  DAT_0063831c: 0,
  DAT_00638334: 0,
  DAT_00638348: 0,
  DAT_0063834c: 0,
  DAT_0063836c: 0,
  DAT_00638380: 0,
  DAT_00638384: 0,
  DAT_00638388: 0,
  DAT_006383a4: 0,
  DAT_006383b8: 0,
  DAT_006383bc: 0,
  DAT_00638578: 0,
  DAT_0063857c: 0,
  DAT_00638580: 0,
  DAT_00638584: 0,
  DAT_00638588: 0,
  DAT_0063858c: 0,
  DAT_006385a0: 0,
  DAT_006385a4: 0,
  DAT_006385a8: 0,
  DAT_006385ac: 0,
  DAT_006385b0: 0,
  DAT_006385bc: 0,
  DAT_006385c0: 0,
  DAT_006385cc: 0,
  DAT_0063863c: 0,
  DAT_00638698: 0,
  DAT_006386f0: 0,
  DAT_006386f4: 0,
  DAT_006386f5: 0,
  DAT_006386f6: 0,
  DAT_006386f7: 0,
  DAT_006386f8: 0,
  DAT_006386f9: 0,
  DAT_006386fa: 0,
  DAT_006386fb: 0,
  DAT_006386fc: 0,
  DAT_00638700: 0,
  DAT_00638704: 0,
  DAT_00638718: 0,
  DAT_006387cc: 0,
  DAT_006389d4: 0,
  DAT_006389d8: 0,
  DAT_006389dc: 0,
  DAT_006389e0: 0,
  DAT_00638a44: 0,
  DAT_00638b40: 0,
  DAT_00638b48: 0,
  DAT_00638b50: 0,
  DAT_00638b90: 0,
  DAT_00638b94: 0,
  DAT_00638b98: 0,
  DAT_00638b9c: 0,
  DAT_00638ba0: 0,
  DAT_00638ba4: 0,
  DAT_00638ba8: 0,
  DAT_00638bac: 0,
  DAT_00638bb0: 0,
  DAT_00638bb4: 0,
  DAT_00638be0: 0,
  DAT_00638d7c: 0,
  DAT_00638d80: 0,
  DAT_00638d84: 0,
  DAT_00638d90: 0,
  DAT_00638d9c: 0,
  DAT_00638da0: 0,
  DAT_00638da8: 0,
  DAT_00638dac: 0,
  DAT_00638db0: 0,
  DAT_00638db4: 0,
  DAT_00638db8: 0,
  DAT_00638dc0: 0,
  DAT_00638dc4: 0,
  DAT_00638dc8: 0,
  DAT_00638dcc: 0,
  DAT_00638dd0: 0,
  DAT_00638dd4: 0,
  DAT_00638dd8: 0,
  DAT_00638ddc: 0,
  DAT_00638de0: 0,
  DAT_00638de4: 0,
  DAT_00638de8: 0,
  DAT_00638e18: 0,
  DAT_00638e1c: 0,
  DAT_00639218: 0,
  DAT_006394c0: 0,
  DAT_00639be8: 0,
  DAT_00639c50: 0,
  DAT_00639c7c: 0,
  DAT_00639cd8: 0,
  DAT_00639cdc: 0,
  DAT_00639d0c: 0,
  DAT_00639d74: 0,
  DAT_00639dc4: 0,
  DAT_00639dc8: 0,
  DAT_00639e3c: 0,
  DAT_00639e40: 0,
  DAT_00639e44: 0,
  DAT_00639e50: 0,
  DAT_00639f14: 0,
  DAT_00639f18: 0,
  DAT_00639f1c: 0,
  DAT_00639f20: 0,
  DAT_00639f28: 0,
  DAT_00639f3c: 0,
  DAT_00639f40: 0,
  DAT_00639f44: 0,
  DAT_00639f4c: 0,
  DAT_00639f54: 0,
  DAT_00639f5c: 0,
  DAT_00639f60: 0,
  DAT_00639f74: 0,
  DAT_00639f78: 0,
  DAT_00639f7c: 0,
  DAT_00639f80: 0,
  DAT_00639f84: 0,
  DAT_00639fa8: 0,
  DAT_00639fc0: 0,
  DAT_00639fcc: 0,
  DAT_00639fd0: 0,
  DAT_0063a018: 0,
  DAT_0063a01c: 0,
  DAT_0063a020: 0,
  DAT_0063a024: 0,
  DAT_0063a030: 0,
  DAT_0063a040: 0,
  DAT_0063a064: 0,
  DAT_0063a068: 0,
  DAT_0063a06c: 0,
  DAT_0063a078: 0,
  DAT_0063a088: 0,
  DAT_0063a29c: 0,
  DAT_0063a2a0: 0,
  DAT_0063a2b8: 0,
  DAT_0063a420: 0,
  DAT_0063a428: 0,
  DAT_0063ac48: 0,
  DAT_0063ac50: 0,
  DAT_0063ac54: 0,
  DAT_0063ac78: 0,
  DAT_0063ac98: 0,
  DAT_0063aef8: 0,
  DAT_0063aefc: 0,
  DAT_0063af00: 0,
  DAT_0063af08: 0,
  DAT_0063af80: 0,
  DAT_0063af84: 0,
  DAT_0063af88: 0,
  DAT_0063af8c: 0,
  DAT_0063af90: 0,
  DAT_0063af94: 0,
  DAT_0063af98: 0,
  DAT_0063b0a4: 0,
  DAT_0063b0a8: 0,
  DAT_0063b0bc: 0,
  DAT_0063b0c8: 0,
  DAT_0063b0d8: 0,
  DAT_0063b248: 0,
  DAT_0063b24c: 0,
  DAT_0063b250: 0,
  DAT_0063b254: 0,
  DAT_0063b258: 0,
  DAT_0063b25c: 0,
  DAT_0063b260: 0,
  DAT_0063b264: 0,
  DAT_0063b268: 0,
  DAT_0063b26c: 0,
  DAT_0063b270: 0,
  DAT_0063b274: 0,
  DAT_0063b280: 0,
  DAT_0063b298: 0,
  DAT_0063b2b0: 0,
  DAT_0063b2b4: 0,
  DAT_0063b2b8: 0,
  DAT_0063b348: 0,
  DAT_0063b350: 0,
  DAT_0063b354: 0,
  DAT_0063b358: 0,
  DAT_0063b360: 0,
  DAT_0063b364: 0,
  DAT_0063b368: 0,
  DAT_0063b380: 0,
  DAT_0063b3dc: 0,
  DAT_0063b4e0: 0,
  DAT_0063b69c: 0,
  DAT_0063b6a0: 0,
  DAT_0063c800: 0,
  DAT_0063c804: 0,
  DAT_0063c808: 0,
  DAT_0063c80c: 0,
  DAT_0063c810: 0,
  DAT_0063c814: 0,
  DAT_0063c818: 0,
  DAT_0063c870: 0,
  DAT_0063c93c: 0,
  DAT_0063c940: 0,
  DAT_0063c944: 0,
  DAT_0063c948: 0,
  DAT_0063caf4: 0,
  DAT_0063cb94: 0,
  DAT_0063cb98: 0,
  DAT_0063cb9c: 0,
  DAT_0063cba0: 0,
  DAT_0063cba4: 0,
  DAT_0063cbb0: 0,
  DAT_0063cbc0: 0,
  DAT_0063cbc4: 0,
  DAT_0063cbd0: 0,
  DAT_0063cc48: 0,
  DAT_0063cc49: 0,
  DAT_0063cd4c: 0,
  DAT_0063ce50: 0,
  DAT_0063cf54: 0,
  DAT_0063d058: 0,
  DAT_0063d15c: 0,
  DAT_0063d260: 0,
  DAT_0063d364: 0,
  DAT_0063d468: 0,
  DAT_0063d56c: 0,
  DAT_0063d670: 0,
  DAT_0063d774: 0,
  DAT_0063e4b8: 0,
  DAT_0063e4c0: 0,
  DAT_0063e4c8: 0,
  DAT_0063e4e0: 0,
  DAT_0063e4ec: 0,
  DAT_0063e4f0: 0,
  DAT_0063e4f4: 0,
  DAT_0063e4f8: 0,
  DAT_0063e540: 0,
  DAT_0063e61c: 0,
  DAT_0063e620: 0,
  DAT_0063e624: 0,
  DAT_0063e7bc: 0,
  DAT_0063e948: 0,
  DAT_0063e954: 0,
  DAT_0063e958: 0,
  DAT_0063e95c: 0,
  DAT_0063e960: 0,
  DAT_0063e968: 0,
  DAT_0063e990: 0,
  DAT_0063ea18: 0,
  DAT_0063ea20: 0,
  DAT_0063eaa0: 0,
  DAT_0063eaa8: 0,
  DAT_0063eaac: 0,
  DAT_0063eab0: 0,
  DAT_0063eab4: 0,
  DAT_0063eab8: 0,
  DAT_0063eac0: 0,
  DAT_0063eac8: 0,
  DAT_0063eaca: 0,
  DAT_0063eada: 0,
  DAT_0063eae0: 0,
  DAT_0063eaf8: 0,
  DAT_0063eb10: 0,
  DAT_0063eb58: 0,
  DAT_0063ec34: 0,
  DAT_0063ec38: 0,
  DAT_0063ec3c: 0,
  DAT_0063edcc: 0,
  DAT_0063edd4: 0,
  DAT_0063ef60: 0,
  DAT_0063ef6c: 0,
  DAT_0063ef70: 0,
  DAT_0063ef74: 0,
  DAT_0063ef80: 0,
  DAT_0063ef8c: 0,
  DAT_0063ef94: 0,
  DAT_0063ef98: 0,
  DAT_0063efa4: 0,
  DAT_0063efa8: 0,
  DAT_0063efac: 0,
  DAT_0063f030: 0,
  DAT_0063f038: 0,
  DAT_0063f040: 0,
  DAT_0063f278: 0,
  DAT_0063f548: 0,
  DAT_0063f554: 0,
  DAT_0063f558: 0,
  DAT_0063f55c: 0,
  DAT_0063f564: 0,
  DAT_0063f568: 0,
  DAT_0063f56c: 0,
  DAT_0063f574: 0,
  DAT_0063f578: 0,
  DAT_0063f57c: 0,
  DAT_0063f660: 0,
  DAT_0063f670: 0,
  DAT_0063f674: 0,
  DAT_0063f678: 0,
  DAT_0063f67c: 0,
  DAT_0063f680: 0,
  DAT_0063f684: 0,
  DAT_0063f688: 0,
  DAT_0063f68c: 0,
  DAT_0063f690: 0,
  DAT_0063f694: 0,
  DAT_0063f698: 0,
  DAT_0063f69c: 0,
  DAT_0063f6a0: 0,
  DAT_0063f6a4: 0,
  DAT_0063f6f0: 0,
  DAT_0063f72c: 0,
  DAT_0063f768: 0,
  DAT_0063f7a4: 0,
  DAT_0063f7e0: 0,
  DAT_0063f81c: 0,
  DAT_0063f858: 0,
  DAT_0063fc18: 0,
  DAT_0063fc58: 0,
  DAT_0063fc98: 0,
  DAT_0063fcd8: 0,
  DAT_0063fd18: 0,
  DAT_0063fe08: 0,
  DAT_0063fe50: 0,
  DAT_0063fe8c: 0,
  DAT_00640990: 0,
  DAT_006409d8: 0,
  DAT_00640b98: 0,
  DAT_00640bd8: 0,
  DAT_00641808: 0,
  DAT_00641848: 0,
  DAT_00641884: 0,
  DAT_00641b54: 0,
  DAT_00642710: 0,
  DAT_0064292c: 0,
  DAT_00642d48: 0,
  DAT_00643798: 0,
  DAT_00643af8: 0,
  DAT_00643b38: 0,
  DAT_00643b74: 0,
  DAT_00643bb0: 0,
  DAT_00643bec: 0,
  DAT_006442b8: 0,
  DAT_006442f8: 0,
  DAT_00644334: 0,
  DAT_006446b8: 0,
  DAT_006446f4: 0,
  DAT_00644730: 0,
  DAT_00644770: 0,
  DAT_006447b0: 0,
  DAT_00644b70: 0,
  DAT_00644e08: 0,
  DAT_00644e48: 0,
  DAT_00644e88: 0,
  DAT_00644f00: 0,
  DAT_00644f3c: 0,
  DAT_00644fb4: 0,
  DAT_00645068: 0,
  DAT_00645120: 0,
  DAT_00645160: 0,
  DAT_006451d8: 0,
  DAT_00645700: 0,
  DAT_006458e0: 0,
  DAT_00645a84: 0,
  DAT_00645fe8: 0,
  DAT_00646118: 0,
  DAT_00646158: 0,
  DAT_00646198: 0,
  DAT_006461d8: 0,
  DAT_00646598: 0,
  DAT_006465d8: 0,
  DAT_00646650: 0,
  DAT_0064668c: 0,
  DAT_006466c8: 0,
  DAT_00646704: 0,
  DAT_00646740: 0,
  DAT_0064677c: 0,
  DAT_00646878: 0,
  DAT_006468b4: 0,
  DAT_006468f0: 0,
  DAT_0064692c: 0,
  DAT_00646968: 0,
  DAT_006469a4: 0,
  DAT_006469e0: 0,
  DAT_00646a20: 0,
  DAT_00646cb8: 0,
  DAT_00647168: 0,
  DAT_00647348: 0,
  DAT_00647388: 0,
  DAT_00647748: 0,
  DAT_00647788: 0,
  DAT_006477c8: 0,
  DAT_00647b50: 0,
  DAT_00647b8c: 0,
  DAT_00647bc8: 0,
  DAT_00647c40: 0,
  DAT_00647ed8: 0,
  DAT_00647f18: 0,
  DAT_00647f60: 0,
  DAT_00647fa0: 0,
  DAT_00647fdc: 0,
  DAT_00648018: 0,
  DAT_00648058: 0,
  DAT_00648098: 0,
  DAT_006480d8: 0,
  DAT_00648118: 0,
  DAT_00648208: 0,
  DAT_006482f8: 0,
  DAT_00648334: 0,
  DAT_00648820: 0,
  DAT_00648860: 0,
  DAT_006488d8: 0,
  DAT_00648918: 0,
  DAT_0064a730: 0,
  DAT_0064b0d0: 0,
  DAT_0064b0d4: 0,
  DAT_0064b0d8: 0,
  DAT_0064b0dc: 0,
  DAT_0064b0e8: 0,
  DAT_0064b0ec: 0,
  DAT_0064b0f4: 0,
  DAT_0064b0f8: 0,
  DAT_0064b0fc: 0,
  DAT_0064b100: 0,
  DAT_0064b108: 0,
  DAT_0064b10c: 0,
  DAT_0064b110: 0,
  DAT_0064b114: 0,
  DAT_0064b118: 0,
  DAT_0064b11c: 0,
  DAT_0064b120: 0,
  DAT_0064b124: 0,
  DAT_0064b128: 0,
  DAT_0064b12c: 0,
  DAT_0064b130: 0,
  DAT_0064b134: 0,
  DAT_0064b138: 0,
  DAT_0064b13c: 0,
  DAT_0064b140: 0,
  DAT_0064b144: 0,
  DAT_0064b148: 0,
  DAT_0064b1ac: 0,
  DAT_0064b1b0: 0,
  DAT_0064b1b4: 0,
  DAT_0064b1df: 0,
  DAT_0064b207: 0,
  DAT_0064b22f: 0,
  DAT_0064b251: 0,
  DAT_0064b257: 0,
  DAT_0064b2a7: 0,
  DAT_0064b2cf: 0,
  DAT_0064b30b: 0,
  DAT_0064b31f: 0,
  DAT_0064b333: 0,
  DAT_0064b340: 0,
  DAT_0064b341: 0,
  DAT_0064b347: 0,
  DAT_0064b36f: 0,
  DAT_0064b383: 0,
  DAT_0064b3bf: 0,
  DAT_0064b3d3: 0,
  DAT_0064b3f4: 0,
  DAT_0064b3fb: 0,
  DAT_0064b44b: 0,
  DAT_0064b45f: 0,
  DAT_0064b487: 0,
  DAT_0064b527: 0,
  DAT_0064b563: 0,
  DAT_0064b690: 0,
  DAT_0064b984: 0,
  DAT_0064b98c: 0,
  DAT_0064b992: 0,
  DAT_0064b994: 0,
  DAT_0064b998: 0,
  DAT_0064b99c: 0,
  DAT_0064b9bc: 0,
  DAT_0064bb08: 0,
  DAT_0064bc10: 0,
  DAT_0064bc14: 0,
  DAT_0064bc16: 0,
  DAT_0064bc18: 0,
  DAT_0064bc1a: 0,
  DAT_0064bc1c: 0,
  DAT_0064bc1e: 0,
  DAT_0064bc22: 0,
  DAT_0064bc24: 0,
  DAT_0064bc26: 0,
  DAT_0064bc28: 0,
  DAT_0064bc2c: 0,
  DAT_0064bc2e: 0,
  DAT_0064bc30: 0,
  DAT_0064bc32: 0,
  DAT_0064bc34: 0,
  DAT_0064bc54: 0,
  DAT_0064bc56: 0,
  DAT_0064bc60: 0,
  DAT_0064bc62: 0,
  DAT_0064bcb2: 0,
  DAT_0064bcb6: 0,
  DAT_0064bcb8: 0,
  DAT_0064bcba: 0,
  DAT_0064bcbe: 0,
  DAT_0064bcc0: 0,
  DAT_0064bcc2: 0,
  DAT_0064bcc8: 0,
  DAT_0064bcc9: 0,
  DAT_0064bcca: 0,
  DAT_0064bccb: 0,
  DAT_0064bccc: 0,
  DAT_0064bccd: 0,
  DAT_0064bcce: 0,
  DAT_0064bccf: 0,
  DAT_0064bcd0: 0,
  DAT_0064bcd1: 0,
  DAT_0064bcd2: 0,
  DAT_0064bcd3: 0,
  DAT_0064bcd4: 0,
  DAT_0064bcd5: 0,
  DAT_0064bcd6: 0,
  DAT_0064bcd7: 0,
  DAT_0064bcd8: 0,
  DAT_0064bcd9: 0,
  DAT_0064bcda: 0,
  DAT_0064bcdb: 0,
  DAT_0064bcdc: 0,
  DAT_0064bcdd: 0,
  DAT_0064bcf4: 0,
  DAT_0064bcfa: 0,
  DAT_0064bd12: 0,
  DAT_0064bd2a: 0,
  DAT_0064bd42: 0,
  DAT_0064c49c: 0,
  DAT_0064c4a4: 0,
  DAT_0064c4b6: 0,
  DAT_0064c4be: 0,
  DAT_0064c4d6: 0,
  DAT_0064c4de: 0,
  DAT_0064c4e4: 0,
  DAT_0064c4ee: 0,
  DAT_0064c506: 0,
  DAT_0064c510: 0,
  DAT_0064c546: 0,
  DAT_0064c54e: 0,
  DAT_0064c55c: 0,
  DAT_0064c588: 0,
  DAT_0064c58e: 0,
  DAT_0064c594: 0,
  DAT_0064c59e: 0,
  DAT_0064c5ae: 0,
  DAT_0064c5b6: 0,
  DAT_0064c5e0: 0,
  DAT_0064c630: 0,
  DAT_0064cc61: 0,
  DAT_0064e854: 0,
  DAT_00654b70: 0,
  DAT_00654c73: 0,
  DAT_00654c74: 0,
  DAT_00654c76: 0,
  DAT_00654c78: 0,
  DAT_00654c7a: 0,
  DAT_00654c7e: 0,
  DAT_00654fa4: 0,
  DAT_00654fa6: 0,
  DAT_00654fa8: 0,
  DAT_00654faa: 0,
  DAT_00654fac: 0,
  DAT_00654fae: 0,
  DAT_00654fd4: 0,
  DAT_00654fd8: 0,
  DAT_00654ff0: 0,
  DAT_00655020: 0,
  DAT_00655128: 0,
  DAT_00655280: 0,
  DAT_00655284: 0,
  DAT_00655288: 0,
  DAT_0065528c: 0,
  DAT_00655290: 0,
  DAT_00655294: 0,
  DAT_00655324: 0,
  DAT_00655328: 0,
  DAT_00655334: 0,
  DAT_00655338: 0,
  DAT_00655344: 0,
  DAT_00655348: 0,
  DAT_006553d8: 0,
  DAT_006553e8: 0,
  DAT_006558e8: 0,
  DAT_006559e8: 0,
  DAT_00655ae8: 0,
  DAT_00655aee: 0,
  DAT_00655af0: 0,
  DAT_00655af2: 0,
  DAT_00655af4: 0,
  DAT_00655afa: 0,
  DAT_00655afc: 0,
  DAT_00655afe: 0,
  DAT_00655b00: 0,
  DAT_00655b02: 0,
  DAT_00655b04: 0,
  DAT_00655b05: 0,
  DAT_00655b07: 0,
  DAT_00655b08: 0,
  DAT_00655b09: 0,
  DAT_00655b0a: 0,
  DAT_00655b0b: 0,
  DAT_00655b0c: 0,
  DAT_00655b0d: 0,
  DAT_00655b0e: 0,
  DAT_00655b0f: 0,
  DAT_00655b10: 0,
  DAT_00655b12: 0,
  DAT_00655b14: 0,
  DAT_00655b16: 0,
  DAT_00655b18: 0,
  DAT_00655b1a: 0,
  DAT_00655b40: 0,
  DAT_00655b44: 0,
  DAT_00655b8d: 0,
  DAT_00655b90: 0,
  DAT_00655b91: 0,
  DAT_00655b93: 0,
  DAT_00655b9e: 0,
  DAT_00655ba4: 0,
  DAT_00655ba5: 0,
  DAT_00655ba7: 0,
  DAT_00655ba9: 0,
  DAT_00655bac: 0,
  DAT_00655baf: 0,
  DAT_00655bb5: 0,
  DAT_00655bb9: 0,
  DAT_00655bbb: 0,
  DAT_00655bbc: 0,
  DAT_00655bc2: 0,
  DAT_00655bca: 0,
  DAT_00655bd3: 0,
  DAT_00655c14: 0,
  DAT_00655c16: 0,
  DAT_00655c18: 0,
  DAT_00655c1e: 0,
  DAT_00655c20: 0,
  DAT_00655c21: 0,
  DAT_00655c31: 0,
  DAT_006660f0: 0,
  DAT_006660f2: 0,
  DAT_006660f4: 0,
  DAT_006660f6: 0,
  DAT_006660f7: 0,
  DAT_006660f8: 0,
  DAT_006660f9: 0,
  DAT_006660fd: 0,
  DAT_006660fe: 0,
  DAT_006660ff: 0,
  DAT_00666100: 0,
  DAT_00666102: 0,
  DAT_00666104: 0,
  DAT_00666106: 0,
  DAT_00666108: 0,
  DAT_00666110: 0,
  DAT_00666112: 0,
  DAT_00666117: 0,
  DAT_00666126: 0,
  DAT_00666128: 0,
  DAT_00666538: 0,
  DAT_0066653a: 0,
  DAT_0066653c: 0,
  DAT_0066653e: 0,
  DAT_00666542: 0,
  DAT_00666544: 0,
  DAT_00666546: 0,
  DAT_00666548: 0,
  DAT_0066654a: 0,
  DAT_0066654c: 0,
  DAT_0066654e: 0,
  DAT_00666550: 0,
  DAT_00666570: 0,
  DAT_00666590: 0,
  DAT_006665b0: 0,
  DAT_006665d0: 0,
  DAT_006665d2: 0,
  DAT_006665d8: 0,
  DAT_006665da: 0,
  DAT_006665ea: 0,
  DAT_006665fa: 0,
  DAT_006665fc: 0,
  DAT_006665fe: 0,
  DAT_00666600: 0,
  DAT_00666602: 0,
  DAT_0066661a: 0,
  DAT_00666632: 0,
  DAT_0066be78: 0,
  DAT_0066bfc0: 0,
  DAT_0066bfc4: 0,
  DAT_0066bfd0: 0,
  DAT_0066c408: 0,
  DAT_0066c4e8: 0,
  DAT_0066c4e9: 0,
  DAT_0066c4f8: 0,
  DAT_0066c600: 0,
  DAT_0066c602: 0,
  DAT_0066c60a: 0,
  DAT_0066c652: 0,
  DAT_0066c65a: 0,
  DAT_0066c662: 0,
  DAT_0066c670: 0,
  DAT_0066c7a8: 0,
  DAT_0066ca54: 0,
  DAT_0066ca58: 0,
  DAT_0066ca5c: 0,
  DAT_0066ca68: 0,
  DAT_0066ca88: 0,
  DAT_0066ca8a: 0,
  DAT_0066ca8c: 0,
  DAT_0066ca98: 0,
  DAT_0066ca9c: 0,
  DAT_0066caa0: 0,
  DAT_0066caa4: 0,
  DAT_0066cab8: 0,
  DAT_0066cad0: 0,
  DAT_0066cad4: 0,
  DAT_0066cad8: 0,
  DAT_0066cadc: 0,
  DAT_0066cae0: 0,
  DAT_00673b04: 0,
  DAT_00673b08: 0,
  DAT_00673e10: 0,
  DAT_00673f14: 0,
  DAT_00673f54: 0,
  DAT_00673f58: 0,
  DAT_00673f5c: 0,
  DAT_00673f60: 0,
  DAT_00673f64: 0,
  DAT_00673f68: 0,
  DAT_00673f6c: 0,
  DAT_00673f70: 0,
  DAT_00673f74: 0,
  DAT_00673f78: 0,
  DAT_00673f7c: 0,
  DAT_00673f80: 0,
  DAT_00673f84: 0,
  DAT_00673f88: 0,
  DAT_00673f8c: 0,
  DAT_00673fa0: 0,
  DAT_00673fa4: 0,
  DAT_00673fa8: 0,
  DAT_00673fac: 0,
  DAT_00673fb0: 0,
  DAT_00673fb4: 0,
  DAT_00673fb8: 0,
  DAT_00673fbc: 0,
  DAT_00673fc0: 0,
  DAT_00673fc4: 0,
  DAT_006787cc: 0,
  DAT_00679640: 0,
  DAT_00679641: 0,
  DAT_00679642: 0,
  DAT_00679643: 0,
  DAT_00679fe8: 0,
  DAT_00679ff0: 0,
  DAT_0067a01c: 0,
  DAT_0067a400: 0,
  DAT_0067a404: 0,
  DAT_0067a408: 0,
  DAT_0067a428: 0,
  DAT_0067a438: 0,
  DAT_0067a43c: 0,
  DAT_0067a440: 0,
  DAT_0067a454: 0,
  DAT_0067a458: 0,
  DAT_0067a46c: 0,
  DAT_0067a4b8: 0,
  DAT_0067a4cc: 0,
  DAT_0067a4e8: 0,
  DAT_0067a4fc: 0,
  DAT_0067a518: 0,
  DAT_0067a52c: 0,
  DAT_0067a530: 0,
  DAT_0067a544: 0,
  DAT_0067a588: 0,
  DAT_0067a638: 0,
  DAT_0067a64c: 0,
  DAT_0067a798: 0,
  DAT_0067a7a0: 0,
  DAT_0067a7a8: 0,
  DAT_0067a7f0: 0,
  DAT_0067a8bc: 0,
  DAT_0067a8c0: 0,
  DAT_0067a8c4: 0,
  DAT_0067a8c8: 0,
  DAT_0067a8d4: 0,
  DAT_0067a8f8: 0,
  DAT_0067a8fc: 0,
  DAT_0067a994: 0,
  DAT_0067a998: 0,
  DAT_0067a99c: 0,
  DAT_0067a9a0: 0,
  DAT_0067a9a4: 0,
  DAT_0067a9b0: 0,
  DAT_0067a9b8: 0,
  DAT_0067a9bc: 0,
  DAT_0067a9c4: 0,
  DAT_0067a9c8: 0,
  DAT_0067a9dc: 0,
  DAT_0067ab64: 0,
  DAT_0067ab65: 0,
  DAT_0067ab66: 0,
  DAT_0067ab67: 0,
  DAT_0067ab94: 0,
  DAT_0068abd8: 0,
  DAT_0068abe0: 0,
  DAT_0068ac30: 0,
  DAT_0068acfc: 0,
  DAT_0068ad04: 0,
  DAT_0068ad08: 0,
  DAT_0068ad14: 0,
  DAT_0068ad38: 0,
  DAT_0068ad3c: 0,
  DAT_0068aeb0: 0,
  DAT_0068aed0: 0,
  DAT_0068aed4: 0,
  DAT_0068aed8: 0,
  DAT_0068aedc: 0,
  DAT_0068aee0: 0,
  DAT_0068aee4: 0,
  DAT_0069b018: 0,
  DAT_0069b020: 0,
  DAT_0069b028: 0,
  DAT_0069b030: 0,
  DAT_0069b03c: 0,
  DAT_006a1864: 0,
  DAT_006a1870: 0,
  DAT_006a18c0: 0,
  DAT_006a1908: 0,
  DAT_006a19d8: 0,
  DAT_006a19dc: 0,
  DAT_006a19e0: 0,
  DAT_006a19e4: 0,
  DAT_006a19e8: 0,
  DAT_006a19ec: 0,
  DAT_006a19f0: 0,
  DAT_006a19f4: 0,
  DAT_006a1b7c: 0,
  DAT_006a1b98: 0,
  DAT_006a1cd8: 0,
  DAT_006a1d7c: 0,
  DAT_006a1d80: 0,
  DAT_006a1d88: 0,
  DAT_006a2d84: 0,
  DAT_006a2d88: 0,
  DAT_006a2d8c: 0,
  DAT_006a2d90: 0,
  DAT_006a2d94: 0,
  DAT_006a2d98: 0,
  DAT_006a2d9c: 0,
  DAT_006a2da0: 0,
  DAT_006a2da4: 0,
  DAT_006a2da8: 0,
  DAT_006a2dac: 0,
  DAT_006a2db0: 0,
  DAT_006a2db4: 0,
  DAT_006a2db8: 0,
  DAT_006a2dbc: 0,
  DAT_006a2dc0: 0,
  DAT_006a2dc4: 0,
  DAT_006a2dc8: 0,
  DAT_006a2dcc: 0,
  DAT_006a2dd0: 0,
  DAT_006a2dd4: 0,
  DAT_006a4f90: 0,
  DAT_006a4f98: 0,
  DAT_006a4f9c: 0,
  DAT_006a5b14: 0,
  DAT_006a5b38: 0,
  DAT_006a5b40: 0,
  DAT_006a5b48: 0,
  DAT_006a5b58: 0,
  DAT_006a6528: 0,
  DAT_006a654c: 0,
  DAT_006a6554: 0,
  DAT_006a6558: 0,
  DAT_006a655c: 0,
  DAT_006a6560: 0,
  DAT_006a6564: 0,
  DAT_006a6568: 0,
  DAT_006a656c: 0,
  DAT_006a6570: 0,
  DAT_006a6574: 0,
  DAT_006a6578: 0,
  DAT_006a657c: 0,
  DAT_006a6580: 0,
  DAT_006a6584: 0,
  DAT_006a6588: 0,
  DAT_006a65a0: 0,
  DAT_006a65a4: 0,
  DAT_006a65ac: 0,
  DAT_006a65b0: 0,
  DAT_006a65bc: 0,
  DAT_006a65c0: 0,
  DAT_006a65c4: 0,
  DAT_006a65d0: 0,
  DAT_006a65d4: 0,
  DAT_006a65d8: 0,
  DAT_006a65dc: 0,
  DAT_006a65e0: 0,
  DAT_006a65e4: 0,
  DAT_006a65e8: 0,
  DAT_006a65f1: 0,
  DAT_006a65f3: 0,
  DAT_006a65f4: 0,
  DAT_006a65f8: 0,
  DAT_006a65fc: 0,
  DAT_006a6600: 0,
  DAT_006a6604: 0,
  DAT_006a6608: 0,
  DAT_006a660c: 0,
  DAT_006a6618: 0,
  DAT_006a661c: 0,
  DAT_006a6621: 0,
  DAT_006a6623: 0,
  DAT_006a6624: 0,
  DAT_006a6668: 0,
  DAT_006a66b0: 0,
  DAT_006a677c: 0,
  DAT_006a6780: 0,
  DAT_006a6784: 0,
  DAT_006a6788: 0,
  DAT_006a678c: 0,
  DAT_006a6790: 0,
  DAT_006a6c60: 0,
  DAT_006a6c80: 0,
  DAT_006a6cc0: 0,
  DAT_006a6fe4: 0,
  DAT_006a7120: 0,
  DAT_006a7204: 0,
  DAT_006a73f8: 0,
  DAT_006a7434: 0,
  DAT_006a7540: 0,
  DAT_006a7d44: 0,
  DAT_006a7d48: 0,
  DAT_006a7d4c: 0,
  DAT_006a7d50: 0,
  DAT_006a7d54: 0,
  DAT_006a7d58: 0,
  DAT_006a7d5c: 0,
  DAT_006a8188: 0,
  DAT_006a818c: 0,
  DAT_006a8190: 0,
  DAT_006a8194: 0,
  DAT_006a8198: 0,
  DAT_006a819c: 0,
  DAT_006a85a0: 0,
  DAT_006a85a4: 0,
  DAT_006a85a8: 0,
  DAT_006a85ac: 0,
  DAT_006a85b0: 0,
  DAT_006a8c00: 0,
  DAT_006a9110: 0,
  DAT_006a9120: 0,
  DAT_006a9170: 0,
  DAT_006a91b8: 0,
  DAT_006a9200: 0,
  DAT_006aa75c: 0,
  DAT_006aa760: 0,
  DAT_006aa764: 0,
  DAT_006aa768: 0,
  DAT_006aa76c: 0,
  DAT_006aa78c: 0,
  DAT_006aa790: 0,
  DAT_006aa7a4: 0,
  DAT_006aa7a8: 0,
  DAT_006aa864: 0,
  DAT_006aad58: 0,
  DAT_006ab178: 0,
  DAT_006ab180: 0,
  DAT_006ab184: 0,
  DAT_006ab188: 0,
  DAT_006ab18c: 0,
  DAT_006ab190: 0,
  DAT_006ab198: 0,
  DAT_006ab19c: 0,
  DAT_006ab1a0: 0,
  DAT_006ab1b8: 0,
  DAT_006ab498: 0,
  DAT_006ab4b8: 0,
  DAT_006ab5ac: 0,
  DAT_006ab5b4: 0,
  DAT_006ab5e0: 0,
  DAT_006ab5e4: 0,
  DAT_006ab5e8: 0,
  DAT_006ab5ec: 0,
  DAT_006ab600: 0,
  DAT_006ab680: 0,
  DAT_006ab681: 0,
  DAT_006ab6a8: 0,
  DAT_006abae0: 0,
  DAT_006abc18: 0,
  DAT_006abc1c: 0,
  DAT_006abc20: 0,
  DAT_006abc24: 0,
  DAT_006abc28: 0,
  DAT_006abc2c: 0,
  DAT_006abc30: 0,
  DAT_006abc34: 0,
  DAT_006abc38: 0,
  DAT_006abc50: 0,
  DAT_006abc58: 0,
  DAT_006abc5c: 0,
  DAT_006abc60: 0,
  DAT_006abc68: 0,
  DAT_006abcc0: 0,
  DAT_006abd8c: 0,
  DAT_006abd90: 0,
  DAT_006abd94: 0,
  DAT_006abd98: 0,
  DAT_006abf24: 0,
  DAT_006abf2c: 0,
  DAT_006abf30: 0,
  DAT_006abf40: 0,
  DAT_006abf44: 0,
  DAT_006abf48: 0,
  DAT_006abf90: 0,
  DAT_006abf98: 0,
  DAT_006abfa8: 0,
  DAT_006abfac: 0,
  DAT_006abfb0: 0,
  DAT_006abfb4: 0,
  DAT_006abfb8: 0,
  DAT_006abfbc: 0,
  DAT_006abfc0: 0,
  DAT_006abfc4: 0,
  DAT_006ac090: 0,
  DAT_006ac0a0: 0,
  DAT_006ac0a4: 0,
  DAT_006ac0a8: 0,
  DAT_006ac0f0: 0,
  DAT_006ac0f4: 0,
  DAT_006ac0f8: 0,
  DAT_006ac108: 0,
  DAT_006ac118: 0,
  DAT_006ac11c: 0,
  DAT_006ac120: 0,
  DAT_006ac124: 0,
  DAT_006ac128: 0,
  DAT_006ac170: 0,
  DAT_006ac1b0: 0,
  DAT_006ac1f8: 0,
  DAT_006ac208: 0,
  DAT_006ac2c8: 0,
  DAT_006ac2cc: 0,
  DAT_006ac2d0: 0,
  DAT_006ac2d4: 0,
  DAT_006ac2d8: 0,
  DAT_006ac2dc: 0,
  DAT_006ac2e4: 0,
  DAT_006ac46c: 0,
  DAT_006ac488: 0,
  DAT_006ac4d0: 0,
  DAT_006ac5a0: 0,
  DAT_006ac5a4: 0,
  DAT_006ac5a8: 0,
  DAT_006ac5bc: 0,
  DAT_006ac874: 0,
  DAT_006ac878: 0,
  DAT_006ac87c: 0,
  DAT_006ac880: 0,
  DAT_006ac884: 0,
  DAT_006ac888: 0,
  DAT_006ac88c: 0,
  DAT_006ac890: 0,
  DAT_006ac894: 0,
  DAT_006ac898: 0,
  DAT_006ac89c: 0,
  DAT_006ac8a0: 0,
  DAT_006ac8a4: 0,
  DAT_006ac8a8: 0,
  DAT_006ac8e8: 0,
  DAT_006ac924: 0,
  DAT_006acb08: 0,
  DAT_006acb0c: 0,
  DAT_006acb30: 0,
  DAT_006acb34: 0,
  DAT_006acb38: 0,
  DAT_006acb68: 0,
  DAT_006acbb0: 0,
  DAT_006acbf8: 0,
  DAT_006acd3c: 0,
  DAT_006acd50: 0,
  DAT_006acd58: 0,
  DAT_006acda0: 0,
  DAT_006ace70: 0,
  DAT_006ace74: 0,
  DAT_006ace78: 0,
  DAT_006ace7c: 0,
  DAT_006ace80: 0,
  DAT_006ace84: 0,
  DAT_006ace8c: 0,
  DAT_006ad014: 0,
  DAT_006ad0cc: 0,
  DAT_006ad0d0: 0,
  DAT_006ad0dc: 0,
  DAT_006ad0e0: 0,
  DAT_006ad0e4: 0,
  DAT_006ad0e8: 0,
  DAT_006ad0ec: 0,
  DAT_006ad0f0: 0,
  DAT_006ad0f4: 0,
  DAT_006ad110: 0,
  DAT_006ad130: 0,
  DAT_006ad148: 0,
  DAT_006ad160: 0,
  DAT_006ad224: 0,
  DAT_006ad228: 0,
  DAT_006ad22c: 0,
  DAT_006ad24c: 0,
  DAT_006ad28c: 0,
  DAT_006ad2ac: 0,
  DAT_006ad2ec: 0,
  DAT_006ad2f0: 0,
  DAT_006ad2f5: 0,
  DAT_006ad2f6: 0,
  DAT_006ad2f7: 0,
  DAT_006ad2f8: 0,
  DAT_006ad2fc: 0,
  DAT_006ad300: 0,
  DAT_006ad304: 0,
  DAT_006ad308: 0,
  DAT_006ad310: 0,
  DAT_006ad330: 0,
  DAT_006ad578: 0,
  DAT_006ad57c: 0,
  DAT_006ad59c: 0,
  DAT_006ad5bc: 0,
  DAT_006ad5dc: 0,
  DAT_006ad5fc: 0,
  DAT_006ad63c: 0,
  DAT_006ad640: 0,
  DAT_006ad664: 0,
  DAT_006ad668: 0,
  DAT_006ad66c: 0,
  DAT_006ad670: 0,
  DAT_006ad684: 0,
  DAT_006ad685: 0,
  DAT_006ad690: 0,
  DAT_006ad694: 0,
  DAT_006ad698: 0,
  DAT_006ad699: 0,
  DAT_006ad69a: 0,
  DAT_006ad6a0: 0,
  DAT_006ad6a4: 0,
  DAT_006ad6a8: 0,
  DAT_006ad6ac: 0,
  DAT_006ad6ae: 0,
  DAT_006ad7b2: 0,
  DAT_006ad8b8: 0,
  DAT_006ad8bc: 0,
  DAT_006ad8c0: 0,
  DAT_006ad8c4: 0,
  DAT_006ad8c8: 0,
  DAT_006ad8cc: 0,
  DAT_006ad8d0: 0,
  DAT_006ad8d4: 0,
  DAT_006ad8d8: 0,
  DAT_006ad8dc: 0,
  DAT_006ad8e0: 0,
  DAT_006ad8e4: 0,
  DAT_006ad8e8: 0,
  DAT_006ad8ec: 0,
  DAT_006ad8f0: 0,
  DAT_006ad8f4: 0,
  DAT_006ad8f8: 0,
  DAT_006ad8fc: 0,
  DAT_006ad900: 0,
  DAT_006ad904: 0,
  DAT_006ad908: 0,
  DAT_006ad90c: 0,
  DAT_006ad910: 0,
  DAT_006ad914: 0,
  DAT_006ad918: 0,
  DAT_006ad91c: 0,
  DAT_006af2c1: 0,
  DAT_006c3160: 0,
  DAT_006c3164: 0,
  DAT_006c31a8: 0,
  DAT_006c31a9: 0,
  DAT_006c31ac: 0,
  DAT_006c31c4: 0,
  DAT_006c31c8: 0,
  DAT_006c31d0: 0,
  DAT_006c31d4: 0,
  DAT_006c8fa0: 0,
  DAT_006c8fac: 0,
  DAT_006c8fb0: 0,
  DAT_006c8fb4: 0,
  DAT_006c8fb8: 0,
  DAT_006c8fbc: 0,
  DAT_006c8ff0: 0,
  DAT_006c8ff4: 0,
  DAT_006c8ffc: 0,
  DAT_006c9004: 0,
  DAT_006c900c: 0,
  DAT_006c9010: 0,
  DAT_006c9024: 0,
  DAT_006c902c: 0,
  DAT_006c9038: 0,
  DAT_006c9078: 0,
  DAT_006c907c: 0,
  DAT_006c9088: 0,
  DAT_006c9090: 0,
  DAT_006c9098: 0,
  DAT_006c90a8: 0,
  DAT_006c90b4: 0,
  DAT_006c90c0: 0,
  DAT_006c90c8: 0,
  DAT_006c90d0: 0,
  DAT_006c90d8: 0,
  DAT_006c90e0: 0,
  DAT_006c90e8: 0,
  DAT_006c90f0: 0,
  DAT_006c90f8: 0,
  DAT_006c9100: 0,
  DAT_006c9108: 0,
  DAT_006c9110: 0,
  DAT_006c9118: 0,
  DAT_006c9120: 0,
  DAT_006c914c: 0,
  DAT_006c9164: 0,
  DAT_006c9168: 0,
  DAT_006c9178: 0,
  DAT_006c918c: 0,
  DAT_006c91e4: 0,
  DAT_006c91e8: 0,
  DAT_006c91ec: 0,
  DAT_006c91f0: 0,
  DAT_006c91f4: 0,
  DAT_006c920c: 0,
  DAT_006c9210: 0,
  DAT_006c9214: 0,
  DAT_006c9218: 0,
  DAT_006c921c: 0,
  DAT_006c9250: 0,
  DAT_006c926c: 0,
  DAT_006c9284: 0,
  DAT_006c9288: 0,
  DAT_006cec78: 0,
  DAT_006cec88: 0,
  DAT_006cec90: 0,
  DAT_006ceca8: 0,
  DAT_006cecb0: 0,
  DAT_006ced50: 0,
  DAT_006d1160: 0,
  DAT_006d1162: 0,
  DAT_006d1164: 0,
  DAT_006d1166: 0,
  DAT_006d116a: 0,
  DAT_006d116c: 0,
  DAT_006d1170: 0,
  DAT_006d1174: 0,
  DAT_006d1178: 0,
  DAT_006d117c: 0,
  DAT_006d1180: 0,
  DAT_006d1da8: 0,
  DAT_006d1ec8: 0,
  DAT_006d46f4: 0,
  DAT_006d46f8: 0,
  DAT_006e47c0: 0,
  DAT_006e47c4: 0,
  DAT_006e47d8: 0,
  DAT_006e47dc: 0,
  DAT_006e47e4: 0,
  DAT_006e47ec: 0,
  DAT_006e47f0: 0,
  DAT_006e47f4: 0,
  DAT_006e47fc: 0,
  DAT_006e4800: 0,
  DAT_006e4804: 0,
  DAT_006e4808: 0,
  DAT_006e480c: 0,
  DAT_006e4810: 0,
  DAT_006e4818: 0,
  DAT_006e4840: 0,
  DAT_006e4850: 0,
  DAT_006e4fec: 0,
  DAT_006e4ff0: 0,
  DAT_006e4ff8: 0,
  DAT_006e5000: 0,
  DAT_006e5004: 0,
  DAT_006e500c: 0,
  DAT_006e5014: 0,
  DAT_006e5018: 0,
  DAT_006e501c: 0,
  DAT_006e5020: 0,
  DAT_006e5028: 0,
  DAT_006e5098: 0,
  DAT_006e50c4: 0,
  DAT_006e50c8: 0,
  DAT_006e50cc: 0,
  DAT_006e50e8: 0,
  DAT_006e50ec: 0,
  DAT_006e50ee: 0,
  DAT_006e50ef: 0,
  DAT_006e5224: 0,
  DAT_006e5225: 0,
  DAT_006e5226: 0,
  DAT_006e5228: 0,
  DAT_006e5368: 0,
  DAT_006e5470: 0,
  DAT_006e5474: 0,
  DAT_006e547c: 0,
  DAT_006e5480: 0,
  DAT_006e5488: 0,
  DAT_006e5490: 0,
  DAT_006e5494: 0,
  DAT_006e5498: 0,
  DAT_006e549c: 0,
  DAT_006e54a0: 0,
  DAT_006e54a8: 0,
  DAT_006e55ac: 0,
  DAT_006e55b0: 0,
  DAT_006e55b2: 0,
  DAT_006e55d0: 0,
  DAT_006e55e0: 0,
  DAT_006e55e8: 0,
  DAT_006e55ec: 0,
  DAT_006e562c: 0,
  DAT_006e562e: 0,
  DAT_006e5630: 0,
  DAT_006e5632: 0,
  DAT_006e5634: 0,
  DAT_006e5636: 0,
  DAT_006e5638: 0,
  DAT_006e563a: 0,
  DAT_006e563c: 0,
  DAT_006e5640: 0,
  DAT_006e5680: 0,
  DAT_006e5682: 0,
  DAT_006e5684: 0,
  DAT_006e5686: 0,
  DAT_006e5688: 0,
  DAT_006e568a: 0,
  DAT_006e568c: 0,
  DAT_006e568e: 0,
  DAT_006e5690: 0,
  DAT_006e69e0: 0,
  DAT_006e69e4: 0,
  DAT_006e6b2c: 0,
  DAT_006e6b30: 0,
  DAT_006e6b3c: 0,
  DAT_006e6b48: 0,
  DAT_006e6b54: 0,
  DAT_006e6b68: 0,
};

// Memory base offset for debugging: 0x61c068
// To read raw memory: G._MEM[address - 0x61c068]
