# Ghidra headless script: decompile all functions in civ2.exe to C pseudocode
# Run with: analyzeHeadless <project_dir> <project_name> -import civ2.exe -postScript decompile_all.py
#
# This script runs inside Ghidra's Jython environment.
# It iterates all functions, decompiles each, and writes the output to files.

import os
from ghidra.app.decompiler import DecompInterface, DecompileOptions
from ghidra.util.task import ConsoleTaskMonitor
from ghidra.program.model.listing import FunctionManager

OUTPUT_DIR = r"C:\Users\stuar\Documents\Stu\Code\civ2research\reverse_engineering\decompiled"

def run():
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    program = currentProgram
    fm = program.getFunctionManager()
    monitor = ConsoleTaskMonitor()

    # Set up decompiler
    decomp = DecompInterface()
    opts = DecompileOptions()
    decomp.setOptions(opts)
    decomp.openProgram(program)

    functions = list(fm.getFunctions(True))  # True = forward iteration
    total = len(functions)
    print("Total functions to decompile: %d" % total)

    # We'll split output into files by address range (64KB blocks)
    # Also create one master index file
    current_block = None
    current_file = None
    index_lines = []

    # Sort functions by entry point
    functions.sort(key=lambda f: f.getEntryPoint().getOffset())

    skipped = 0
    decompiled = 0
    errors = 0

    for i, func in enumerate(functions):
        if monitor.isCancelled():
            break

        addr = func.getEntryPoint().getOffset()
        name = func.getName()
        block_addr = addr & 0xFFFF0000

        # Skip thunk/external functions
        if func.isThunk() or func.isExternal():
            skipped += 1
            continue

        # Open new file for each 64KB block
        if block_addr != current_block:
            if current_file:
                current_file.close()
            current_block = block_addr
            filename = "block_%08X.c" % block_addr
            filepath = os.path.join(OUTPUT_DIR, filename)
            current_file = open(filepath, "w")
            current_file.write("// Decompiled functions in address range 0x%08X - 0x%08X\n" % (block_addr, block_addr + 0xFFFF))
            current_file.write("// Source: civ2.exe (Civilization II Multiplayer Gold Edition)\n")
            current_file.write("// Generated by Ghidra 12.0.3 headless decompiler\n\n")

        # Decompile
        try:
            results = decomp.decompileFunction(func, 60, monitor)  # 60 second timeout per function
            if results and results.depiledFunction():
                code = results.getDecompiledFunction().getC()
                current_file.write("// ============================================================\n")
                current_file.write("// Function: %s @ 0x%08X\n" % (name, addr))
                current_file.write("// Size: %d bytes\n" % (func.getBody().getNumAddresses()))
                current_file.write("// ============================================================\n")
                current_file.write(code)
                current_file.write("\n\n")
                index_lines.append("0x%08X  %6d  %s" % (addr, func.getBody().getNumAddresses(), name))
                decompiled += 1
            else:
                err_msg = results.getErrorMessage() if results else "null result"
                current_file.write("// ERROR decompiling %s @ 0x%08X: %s\n\n" % (name, addr, err_msg))
                index_lines.append("0x%08X  %6d  %s  [ERROR]" % (addr, func.getBody().getNumAddresses(), name))
                errors += 1
        except Exception as e:
            current_file.write("// EXCEPTION decompiling %s @ 0x%08X: %s\n\n" % (name, addr, str(e)))
            index_lines.append("0x%08X  %6d  %s  [EXCEPTION]" % (addr, func.getBody().getNumAddresses(), name))
            errors += 1

        if (i + 1) % 100 == 0:
            print("  Progress: %d/%d functions (decompiled=%d, skipped=%d, errors=%d)" % (i + 1, total, decompiled, skipped, errors))

    if current_file:
        current_file.close()

    # Write index file
    index_path = os.path.join(OUTPUT_DIR, "FUNCTION_INDEX.txt")
    with open(index_path, "w") as f:
        f.write("# Civ2.exe Function Index\n")
        f.write("# Generated by Ghidra headless decompiler\n")
        f.write("# Format: Address  Size  Name\n")
        f.write("# Total: %d decompiled, %d skipped (thunks/externals), %d errors\n\n" % (decompiled, skipped, errors))
        for line in index_lines:
            f.write(line + "\n")

    decomp.dispose()
    print("\nDone! Decompiled %d functions, skipped %d, errors %d" % (decompiled, skipped, errors))
    print("Output: %s" % OUTPUT_DIR)

run()
