// Ghidra headless script: decompile all functions in civ2.exe to C pseudocode
// Run with: analyzeHeadless <project_dir> <project_name> -process civ2.exe -postScript DecompileAll.java
//
// Iterates all functions, decompiles each, writes output to per-block .c files
// @category Analysis

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileOptions;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionIterator;
import ghidra.program.model.listing.FunctionManager;
import ghidra.util.task.ConsoleTaskMonitor;

import java.io.*;
import java.util.*;

public class DecompileAll extends GhidraScript {

    private static final String OUTPUT_DIR = "C:\\Users\\stuar\\Documents\\Stu\\Code\\civ2research\\reverse_engineering\\decompiled";

    @Override
    public void run() throws Exception {
        File outDir = new File(OUTPUT_DIR);
        if (!outDir.exists()) {
            outDir.mkdirs();
        }

        FunctionManager fm = currentProgram.getFunctionManager();

        // Set up decompiler
        DecompInterface decomp = new DecompInterface();
        DecompileOptions opts = new DecompileOptions();
        decomp.setOptions(opts);
        decomp.openProgram(currentProgram);

        // Collect all functions sorted by address
        List<Function> functions = new ArrayList<>();
        FunctionIterator iter = fm.getFunctions(true);
        while (iter.hasNext()) {
            functions.add(iter.next());
        }
        functions.sort((a, b) -> a.getEntryPoint().compareTo(b.getEntryPoint()));

        int total = functions.size();
        println("Total functions to decompile: " + total);

        long currentBlock = -1;
        PrintWriter currentFile = null;
        List<String> indexLines = new ArrayList<>();

        int skipped = 0;
        int decompiled = 0;
        int errors = 0;

        for (int i = 0; i < functions.size(); i++) {
            if (monitor.isCancelled()) break;

            Function func = functions.get(i);
            long addr = func.getEntryPoint().getOffset();
            String name = func.getName();
            long blockAddr = addr & 0xFFFF0000L;

            // Skip thunk/external functions
            if (func.isThunk() || func.isExternal()) {
                skipped++;
                continue;
            }

            // Open new file for each 64KB block
            if (blockAddr != currentBlock) {
                if (currentFile != null) {
                    currentFile.close();
                }
                currentBlock = blockAddr;
                String filename = String.format("block_%08X.c", blockAddr);
                File filepath = new File(outDir, filename);
                currentFile = new PrintWriter(new FileWriter(filepath));
                currentFile.printf("// Decompiled functions in address range 0x%08X - 0x%08X%n", blockAddr, blockAddr + 0xFFFF);
                currentFile.println("// Source: civ2.exe (Civilization II Multiplayer Gold Edition)");
                currentFile.println("// Generated by Ghidra 12.0.3 headless decompiler");
                currentFile.println();
            }

            // Decompile
            try {
                DecompileResults results = decomp.decompileFunction(func, 60, monitor);
                if (results != null && results.decompileCompleted()) {
                    String code = results.getDecompiledFunction().getC();
                    currentFile.println("// ============================================================");
                    currentFile.printf("// Function: %s @ 0x%08X%n", name, addr);
                    currentFile.printf("// Size: %d bytes%n", func.getBody().getNumAddresses());
                    currentFile.println("// ============================================================");
                    currentFile.println(code);
                    currentFile.println();
                    indexLines.add(String.format("0x%08X  %6d  %s", addr, func.getBody().getNumAddresses(), name));
                    decompiled++;
                } else {
                    String errMsg = results != null ? results.getErrorMessage() : "null result";
                    currentFile.printf("// ERROR decompiling %s @ 0x%08X: %s%n%n", name, addr, errMsg);
                    indexLines.add(String.format("0x%08X  %6d  %s  [ERROR]", addr, func.getBody().getNumAddresses(), name));
                    errors++;
                }
            } catch (Exception e) {
                currentFile.printf("// EXCEPTION decompiling %s @ 0x%08X: %s%n%n", name, addr, e.toString());
                indexLines.add(String.format("0x%08X  %6d  %s  [EXCEPTION]", addr, func.getBody().getNumAddresses(), name));
                errors++;
            }

            if ((i + 1) % 200 == 0) {
                println(String.format("  Progress: %d/%d functions (decompiled=%d, skipped=%d, errors=%d)", i + 1, total, decompiled, skipped, errors));
            }
        }

        if (currentFile != null) {
            currentFile.close();
        }

        // Write index file
        File indexFile = new File(outDir, "FUNCTION_INDEX.txt");
        PrintWriter indexWriter = new PrintWriter(new FileWriter(indexFile));
        indexWriter.println("# Civ2.exe Function Index");
        indexWriter.println("# Generated by Ghidra headless decompiler");
        indexWriter.println("# Format: Address  Size  Name");
        indexWriter.printf("# Total: %d decompiled, %d skipped (thunks/externals), %d errors%n%n", decompiled, skipped, errors);
        for (String line : indexLines) {
            indexWriter.println(line);
        }
        indexWriter.close();

        decomp.dispose();
        println(String.format("\nDone! Decompiled %d functions, skipped %d, errors %d", decompiled, skipped, errors));
        println("Output: " + OUTPUT_DIR);
    }
}
