// Decompiled functions in address range 0x00610000 - 0x0061FFFF
// Source: civ2.exe (Civilization II Multiplayer Gold Edition)
// Generated by Ghidra 12.0.3 headless decompiler

// ============================================================
// Function: FUN_0061a000 @ 0x0061A000
// Size: 326 bytes
// ============================================================

// /* WARNING: Unable to track spacebase fully for stack */

import '../globals-init.js';
import { s8, u8, s16, u16, s32, u32, v, wv, w16, w32, w16r, w32r, ptrAdd, _MEM, loopGuard, loopReset } from '../mem.js';
import { devLog } from '../devlog.js';
import { exe, segment } from '../extern-stubs.js';

export function FUN_0061a000(unaff_SI, unaff_DI) {


  let puVar1;
  let puVar2;
  let psVar3;
  let puVar4;
  let psVar5;
  let psVar6;
  let puVar7;
  let puVar8;
  let piVar9;
  let pcVar10;
  let puVar11;
  let puVar12;
  let cVar13;
  let sVar14;
  let sVar15;
  let uVar16;
  let sVar17;
  let sVar18;
  let sVar19;
  let sVar20;
  // unaff_SI → promoted to parameter
  // unaff_DI → promoted to parameter
  let in_SS;
  let in_DS;
  let uVar22;
  devLog('SEH', '');
  let auStack_2 = new Array(2).fill(0);
  let iVar21;
  
  sVar20 = ((auStack_2) << 16 >> 16);
  sVar18 = ((auStack_2) << 16 >> 16);
  iVar21 = ((((((auStack_2) >>> 0) >> 0x10) << 16 >> 16)) << 16 | (sVar20 + -0x16));
  w16(iVar21, -4, in_DS);
  w16(iVar21, -6, unaff_SI);
  w16(iVar21, -8, unaff_DI);
  puVar1 = segment(in_SS,sVar20 + 0x1a);
  uVar16 = s32(puVar1, 0);
  puVar1 = segment(in_SS,sVar20 + -8);
  w32(puVar1, 0, uVar16 & 0xffff);
  puVar2 = segment(in_SS,sVar20 + -2);
  w32(puVar2, 0, ((uVar16 >> 0x10) << 16 >> 16));
  puVar1 = segment(in_SS,sVar20 + 0x1e);
  uVar16 = s32(puVar1, 0);
  puVar1 = segment(in_SS,sVar20 + -0xc);
  w32(puVar1, 0, uVar16 & 0xffff);
  puVar2 = segment(in_SS,sVar20 + -4);
  w32(puVar2, 0, ((uVar16 >> 0x10) << 16 >> 16));
  segment(in_SS,sVar20 + 10);
  segment(in_SS,sVar20 + 0xe);
  psVar3 = segment(in_SS,sVar20 + 0x28);
  sVar19 = s32(psVar3, 0);
  do {
    loopGuard('FUN_0061a000', 66);
    psVar3 = segment(in_SS,sVar20 + -0x10);
    w32(psVar3, 0, sVar19);
    psVar3 = segment(in_SS,sVar20 + 0x24);
    sVar19 = s32(psVar3, 0);
    do {
      loopGuard('FUN_0061a000', 71);
      puVar4 = segment(in_SS,sVar20 + 0x16);
      uVar22 = ((((s32(puVar4, 0)) >>> 0) >> 0x10) & 0xFFFF);
      sVar17 = ((s32(puVar4, 0)) << 16 >> 16);
      psVar3 = segment(in_SS,sVar20 + 0x28);
      psVar5 = segment(in_SS,sVar20 + -0x10);
      psVar6 = segment(in_SS,sVar20 + 0x22);
      puVar12 = segment(uVar22,((s32(psVar3, 0) - s32(psVar5, 0)) + s32(psVar6, 0)) * 2 + sVar17);
      puVar2 = segment(in_SS,sVar20 + -0xe);
      w32(puVar2, 0, s32(puVar12, 0));
      psVar3 = segment(in_SS,sVar20 + 0x26);
      sVar14 = s32(psVar3, 0);
      psVar3 = segment(in_SS,sVar20 + 0x24);
      sVar15 = s32(psVar3, 0);
      psVar3 = segment(in_SS,sVar20 + -0x14);
      w32(psVar3, 0, sVar15 - sVar19);
      psVar5 = segment(uVar22,(sVar15 - sVar19) * 2 + sVar17 + sVar14);
      psVar3 = segment(in_SS,sVar20 + -0xe);
      puVar7 = segment(in_SS,sVar20 + 0x26);
      puVar8 = segment(in_SS,sVar20 + -0x12);
      w32(puVar8, 0, ((s32(psVar3, 0) + s32(psVar5, 0)) & 0xFFFF) % s32(puVar7, 0));
      psVar3 = segment(in_SS,sVar20 + -0x12);
      psVar5 = segment(in_SS,sVar20 + 0x2c);
      piVar9 = segment(in_SS,sVar20 + -8);
      segment(in_SS,sVar20 + -2);
      puVar7 = segment(in_SS,sVar20 + 0x2a);
      puVar8 = segment(in_SS,sVar20 + -0x14);
      devLog('SEH', '');
                                 /*JOINED*/
                        /*JOINED*/
      psVar3 = segment(in_SS,sVar20 + 0x32);
      if ((s32(psVar3, 0) < 0) || (cVar13 !== s8(s32(psVar3, 0)))) {
        pcVar10 = segment(in_SS,sVar20 + -0x16);
        w32(pcVar10, 0, cVar13);
        psVar3 = segment(in_SS,sVar18 + -0x12);
        psVar5 = segment(in_SS,sVar18 + 0x30);
        piVar9 = segment(in_SS,sVar18 + -0xc);
        segment(in_SS,sVar18 + -4);
        puVar7 = segment(in_SS,sVar18 + 0x2e);
        puVar8 = segment(in_SS,sVar18 + -0x14);
        puVar11 = segment(in_SS,sVar18 + -0x16);
        devLog('SEH', '');
         /*JOINED*/
          /*JOINED*/
      }
      sVar19 = sVar19 + -1;
    } while (0 < sVar19);
    psVar3 = segment(in_SS,sVar18 + -0x10);
    sVar19 = s32(psVar3, 0) + -1;
  } while (0 < sVar19);
  return;
}



// ============================================================
// Function: FUN_0061a759 @ 0x0061A759
// Size: 423 bytes
// ============================================================

// /* WARNING: Unable to track spacebase fully for stack */

export function FUN_0061a759(unaff_SI, unaff_DI) {


  let puVar1;
  let puVar2;
  let puVar3;
  let psVar4;
  let psVar5;
  let puVar6;
  let puVar7;
  let psVar8;
  let psVar9;
  let piVar10;
  let pcVar11;
  let cVar12;
  let cVar13;
  let uVar14;
  let uVar15;
  let uVar16;
  let sVar17;
  let sVar18;
  let uVar19;
  let iVar20;
  let uVar21;
  let iVar22;
  let sVar23;
  // unaff_SI → promoted to parameter
  let sVar25;
  // unaff_DI → promoted to parameter
  let pcVar26;
  let in_SS;
  let in_DS;
  let auStack_2 = new Array(2).fill(0);
  let iVar24;
  
  sVar23 = ((auStack_2) << 16 >> 16);
  sVar17 = ((auStack_2) << 16 >> 16);
  iVar24 = ((((((auStack_2) >>> 0) >> 0x10) << 16 >> 16)) << 16 | (sVar23 + -0x18));
  w16(iVar24, -4, in_DS);
  w16(iVar24, -6, unaff_SI);
  w16(iVar24, -8, unaff_DI);
  puVar1 = segment(in_SS,sVar23 + 10);
  uVar15 = s32(puVar1, 0);
  puVar2 = segment(in_SS,sVar23 + 0x12);
  uVar16 = s32(puVar2, 0);
  puVar3 = segment(in_SS,sVar23 + -6);
  w32(puVar3, 0, ((((uVar16) >>> 0) >> 0x10) << 16 >> 16));
  puVar3 = segment(in_SS,sVar23 + -8);
  w32(puVar3, 0, ((uVar16) << 16 >> 16));
  puVar2 = segment(in_SS,sVar23 + 0x16);
  uVar16 = s32(puVar2, 0);
  puVar3 = segment(in_SS,sVar23 + -10);
  w32(puVar3, 0, ((((uVar16) >>> 0) >> 0x10) << 16 >> 16));
  puVar3 = segment(in_SS,sVar23 + -0xc);
  w32(puVar3, 0, ((uVar16) << 16 >> 16));
  puVar1 = segment(in_SS,sVar23 + 0xe);
  psVar4 = segment(in_SS,sVar23 + 0x20);
  iVar22 = s32(psVar4, 0);
  if (iVar22 < 1) {
    iVar22 = -iVar22;
    psVar4 = segment(in_SS,sVar23 + 0x22);
    psVar5 = segment(in_SS,sVar23 + 0x1e);
    uVar19 = (s32(psVar4, 0) + -1) - s32(psVar5, 0);
  }
  else {
    puVar6 = segment(in_SS,sVar23 + 0x1e);
    uVar19 = s32(puVar6, 0);
  }
  puVar6 = segment(in_SS,sVar23 + 0x1c);
  pcVar26 = ((s32(puVar1, 0) & 0xffff) + ((uVar19) >>> 0) * iVar22 + ((s32(puVar6, 0)) >>> 0));
  puVar3 = segment(in_SS,sVar23 + 0x2e);
  puVar7 = segment(in_SS,sVar23 + -0xe);
  w32(puVar7, 0, s32(puVar3, 0));
  psVar4 = segment(in_SS,sVar23 + 0x2a);
  psVar5 = segment(in_SS,sVar23 + 0x32);
  psVar8 = segment(in_SS,sVar23 + -0xc);
  psVar9 = segment(in_SS,sVar17 + -0x10);
  w32(psVar9, 0, (s32(psVar4, 0) + s32(psVar5, 0)) * 2 + s32(psVar8, 0));
  piVar10 = segment(in_SS,sVar17 + -4);
  w32(piVar10, 0, (uVar15 & 0xffff) + 4);
  psVar4 = segment(in_SS,sVar17 + 0x26);
  sVar25 = s32(psVar4, 0);
  uVar21 = 0;
  do {
    loopGuard('FUN_0061a759', 216);
    w16(iVar24, -10, sVar25);
    piVar10 = segment(in_SS,sVar17 + -4);
    iVar22 = s32(piVar10, 0);
    puVar3 = segment(in_SS,sVar17 + -0xe);
    iVar20 = ((uVar21) << 16 | (s32(puVar3, 0)));
    puVar3 = segment(in_SS,sVar17 + -10);
    puVar7 = segment(in_SS,sVar17 + -0x10);
    while( true ) {
      loopGuard('FUN_0061a759', 224);
      psVar4 = segment(s32(puVar3, 0),s32(puVar7, 0));
      sVar25 = ((iVar20) << 16 >> 16);
      uVar21 = ((((iVar20) >>> 0) >> 0x10) & 0xFFFF);
      if (s32(psVar4, 0) <= sVar25) break;
      iVar22 = iVar22 + u16(iVar22, -2) + 4;
      iVar20 = ((uVar21) << 16 | (sVar25 + 1));
    }
    psVar4 = segment(in_SS,sVar17 + -0xe);
    w32(psVar4, 0, sVar25);
    piVar10 = segment(in_SS,sVar17 + -4);
    w32(piVar10, 0, iVar22);
    puVar3 = segment(in_SS,sVar17 + -0x14);
    w32(puVar3, 0, s16(iVar22, -4));
    sVar25 = s16(iVar22, -2);
    psVar4 = segment(in_SS,sVar17 + -0x16);
    w32(psVar4, 0, sVar25);
    if (sVar25 !== 0) {
      psVar4 = segment(in_SS,sVar17 + 0x28);
      psVar5 = segment(in_SS,sVar17 + 0x30);
      psVar8 = segment(in_SS,sVar17 + -8);
      psVar9 = segment(in_SS,sVar17 + -0x12);
      w32(psVar9, 0, (s32(psVar4, 0) + s32(psVar5, 0)) * 2 + s32(psVar8, 0));
      // DEVIATION: C pointer write — *(char **)(iVar24 + -0xe) = pcVar26;
      psVar4 = segment(in_SS,sVar17 + -0x14);
      iVar20 = ((uVar21) << 16 | (s32(psVar4, 0)));
      puVar3 = segment(in_SS,sVar23 + -6);
      uVar14 = s32(puVar3, 0);
      psVar5 = segment(in_SS,sVar23 + -0x12);
      sVar25 = s32(psVar5, 0);
      psVar5 = segment(in_SS,sVar23 + 0x24);
      sVar18 = s32(psVar5, 0);
      while (psVar5 = segment(uVar14,sVar25), s32(psVar5, 0) < s32(psVar4, 0)) {
        loopGuard('FUN_0061a759', 256);
        sVar25 = sVar25 + 2;
        pcVar26 = pcVar26 + 1;
        sVar18 = sVar18 + -1;
      }
      psVar4 = segment(in_SS,sVar23 + -0x12);
      w32(psVar4, 0, sVar25);
      psVar4 = segment(in_SS,sVar23 + -0x18);
      w32(psVar4, 0, sVar18);
      if (0 < sVar18) {
        iVar20 = ((uVar21) << 16 | (sVar18));
        pcVar11 = segment(in_SS,sVar23 + 0x1a);
        cVar12 = s32(pcVar11, 0);
        piVar10 = segment(in_SS,sVar23 + -4);
        iVar22 = s32(piVar10, 0);
        do {
          loopGuard('FUN_0061a759', 271);
          psVar8 = segment(uVar14,sVar25);
          psVar4 = segment(in_SS,sVar23 + -0x14);
          psVar5 = segment(in_SS,sVar23 + -0x16);
          if (s32(psVar5, 0) <= ((s32(psVar8, 0) - s32(psVar4, 0)) << 16 >> 16)) break;
          cVar13 = s8(((((s32(psVar8, 0) - s32(psVar4, 0)) & 0xFFFF) >>> 0) + iVar22)[0]);
          if (cVar13 !== cVar12) {
            w32(pcVar26, 0, cVar13);
          }
          sVar25 = sVar25 + 2;
          pcVar26 = pcVar26 + 1;
          iVar20 = iVar20 + -1;
        } while (iVar20 !== 0);
      }
      pcVar26 = true /* DEVIATION: C pointer — *(char **)(iVar24 + -0xe) */;
    }
    psVar4 = segment(in_SS,sVar23 + 0x20);
    pcVar26 = pcVar26 + s32(psVar4, 0);
    psVar4 = segment(in_SS,sVar23 + -0x10);
    psVar5 = segment(in_SS,sVar23 + -0x10);
    w32(psVar5, 0, s32(psVar4, 0) + 2);
    uVar21 = ((((iVar20) >>> 0) >> 0x10) & 0xFFFF);
    sVar25 = s16(iVar24, -10) + -1;
    if (sVar25 < 1) {
      return;
    }
  } while( true );
}



